### ISSUE TITLE
Access is Denied - Next Token Financial Events

### ISSUE THREAD

**Issue by jmawebtech** [abuzuhri/Amazon-SP-API-CSharp#100]
I am unable to call financial events, if there is a next token. The first call works and the second one fails. The only difference is the next token in the query string.

![Snag_246daec1](https://user-images.githubusercontent.com/1679993/152687073-797da912-5948-464d-b5b8-859b7a109030.png)

![Snag_246d6d72](https://user-images.githubusercontent.com/1679993/152687057-c8e769d3-5447-4517-9aaa-ab009ca97f0f.png)

![Snag_246d545c](https://user-images.githubusercontent.com/1679993/152687049-add8e0e5-8d03-4ce0-84e3-7823142440e3.png)

**Comment by jmawebtech** [comment]
In my Amazon app, I changed the IAM to my role. I have to wait a few minutes for it to work.

**Comment by abuzuhri** [comment]
How it as working with you first without roles , many developers as to support IAM NOT roles 

Please let know know if it's was working without role .
