### ISSUE TITLE
Rate limiting doesn't take burst into account

### ISSUE THREAD

**Issue by wizzardmr42** [abuzuhri/Amazon-SP-API-CSharp#107]
The delay between calls should only kick in if a 429 occurs, not after every call, otherwise we can't make use of the burst capacity.

eg. GET /reports/2021-06-30/reports has a rate per second of 0.0222, or 1 per 45 seconds, but there is a burst of 10.  That means that we can request this 10 times before the rate limit kicks in.  If the response takes around 250ms and we have 10 pages to get, it takes 2.5s to get them without the delay, and Amazon won't limit it because of the burst.  However, the delay between calls is slowing this down to make a 45s delay between each call, which works out at 6 mins and 45 secs, which is 162 times longer in this example!

**Comment by wizzardmr42** [comment]
I noticed that and have disabled it for now, but it is a shame not to use the rate limit handling feature you've built in - it is a great idea, just doesn't seem to work quite right.  Thanks!

**Comment by abuzuhri** [comment]
https://github.com/abuzuhri/Amazon-SP-API-CSharp/discussions/109

**Comment by wizzardmr42** [comment]
Might be a good idea to allow for different rate limiting policies and allow the end-user to provide an object that allows them to apply their own custom policy?

From reading up on it, I'm not sure that the headers are that much use.  I don't think it makes sense to directly use them anyway - eg. if you hit the limit on GetReport, based on the (previous) header, you'd wait 45 secs, but it might actually only be 1 second before the next one is available.  I've been experimenting with using a combination of 2 times - 1 for how often to retry, and the other is a timeout so if we haven't managed to do it in that time then we give up.  

If we are using the rate limit headers the way that you are storing them, I think we need a way to persist them, because some use cases will involve creating the AmazonConnection, doing 1 call and then it is destroyed - the AmazonConnection might not be kept in memory.

**Comment by abuzuhri** [comment]
> Might be a good idea to allow for different rate limiting policies and allow the end-user to provide an object that allows them to apply their own custom policy?

if need to allowed user to manage , then we need to open all method that have next token for user and he need to manage every thing for example getorderbyNextToken.

Many change needed in library I try to keep it very easy for developer to use , no need to care about next token .

but I'm open to all idea if this the best for all

**Comment by abuzuhri** [comment]
> From reading up on it, I'm not sure that the headers are that much use. I don't think it makes sense to directly use them anyway - eg. if you hit the limit on GetReport, based on the (previous) header, you'd wait 45 secs, but it might actually only be 1 second before the next one is available. I've been experimenting with using a combination of 2 times - 1 for how often to retry, and the other is a timeout so if we haven't managed to do it in that time then we give up.

Now i calc the time between the requests and if there is more times between requests then then the will increase the burst count , so this problem solved 

And also add NumberOfRetry in case of 429 error then system will wait and try again after rate time
