### ISSUE TITLE
Direct Fulfillment Shipping API

### ISSUE THREAD

**Issue by Tilted-Software** [abuzuhri/Amazon-SP-API-CSharp#112]
Hi

I see that you've implemented the Direct Fulfillment Orders API - GetOrder/GetOrders and SubmitAcknowledgement.

Have you or do you intend to implement the Direct Fulfillment Shipping API?

Thanks

Chris.

**Comment by abuzuhri** [comment]
Hello @Tilted-Software 

The plane to implement all methods but its depend on my free time , i will see if i will be free this weekend or next weekend.
or if you have time you can fork and add it and send pull request

**Comment by abuzuhri** [comment]
Hi @Tilted-Software 

Do you solve the problem ?

**Comment by Tilted-Software** [comment]
Hi

I'll see if I can to fork and add when I get to the point that I need it - thanks for your help.

Chris.
