### ISSUE TITLE
have any error for BigDecimalType type define？

### ISSUE THREAD

**Issue by heyuquan** [abuzuhri/Amazon-SP-API-CSharp#120]
the doc ：https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#bigdecimaltype
description BigDecimalType is number (double)
but，FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.BigDecimalType have noting about double transform define.
I have a problem : invoke CreateInboundShipmentPlan，error：Error converting value 0.15 to type 'FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.BigDecimalType'. Path 'payload.InboundShipmentPlans[0].EstimatedBoxContentsFee.FeePerUnit.Value', line 458, position 62

**Comment by abuzuhri** [comment]
Hello 

Please share the code you are useing when you get this error

**Comment by heyuquan** [comment]
like this:

 FulFillmentInboundService fbaInbound = AmazonConnection.FulFillmentInbound;

            var InboundShipmentPlanRequestItems = new InboundShipmentPlanRequestItemList();

            foreach (var item in items)
            {
                if (string.IsNullOrWhiteSpace(item.SellerSKU))
                {
                    return cres.Append($"当前{callerName}存在没有SellerSKU的发货项，无法创建发货计划，请咨询IT：[{callerId}][{item.SkuID}]");
                }

                InboundShipmentPlanRequestItem ispri = new InboundShipmentPlanRequestItem(item.SellerSKU, string.Empty, 0, item.Quantity);
                InboundShipmentPlanRequestItems.Add(ispri);
            }

            CreateInboundShipmentPlanRequest req = new CreateInboundShipmentPlanRequest(GetSPAPIAddress(from), LabelPrepPreference.SELLERLABEL,
            countryCode, null, InboundShipmentPlanRequestItems);
            CreateInboundShipmentPlanResult response;
            try
            {
                response = fbaInbound.CreateInboundShipmentPlan(req);
            }
            catch (Exception ex)
            {
                return cres.Append($"[Amazon] [{callerName}] {nameof(InnerCreateAmazonInboundShipmentPlan)} 异常返回{ex.Message}.");
            }

**Comment by abuzuhri** [comment]
Hello 

the example look need many variables  not exist in the code 

please try to give another external example that produces that error , then I will test and fix from my side and upload new nuget

**Comment by heyuquan** [comment]
hello. 
there is no external example，this CreateInboundShipmentPlan have product key param
this code is ok？
AmazonSpApiSDK.Models.FulfillmentInbound.Amount amount
                = new AmazonSpApiSDK.Models.FulfillmentInbound.Amount(AmazonSpApiSDK.Models.FulfillmentInbound.CurrencyCode.USD, 0.15);

now，BigDecimalType is useless，have nothing field

**Comment by heyuquan** [comment]
like this ：https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/84
i think instead of double or decimal can fix

**Comment by abuzuhri** [comment]
which NuGet version you are using ?

**Comment by heyuquan** [comment]
is use old version，update，i find this problem is fix

**Comment by abuzuhri** [comment]
Good , You welcome
