### ISSUE TITLE
ReportService missing Encoding

### ISSUE THREAD

**Issue by kevinvenclovas** [abuzuhri/Amazon-SP-API-CSharp#122]
Missing the Encoding on Reports like GetProductsAsync()

![image](https://user-images.githubusercontent.com/7681603/155277246-dd47e258-c895-4a6a-95f8-ec1a46d258cb.png)

**Comment by abuzuhri** [comment]
Hello @kevinvenclovas 

Its look like the problem from amazon not from our code

I debug the code until arrive to this `GetReportDocumentAsync(reportDocumentId)` this method will return url for zip file ,we do unzip and read the content of this file ,I see have same problem the file came from amazon without encoding 

we need to report this in amazon

**Comment by abuzuhri** [comment]
Hello @kevinvenclovas

Do you open case in amazon regarding this ?

**Comment by abuzuhri** [comment]
Hello @kevinvenclovas 

Any Update on this ?

**Comment by pandapknaepel** [comment]
I don't know if this can help anyone else, but we had a similar problem and the solution was to read resulting data with encoding Windows-1252.

My call:

~~~c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var encoding = Encoding.GetEncoding(1252);

var reportFilePath =
            await _amazonReportService.DownloadReportAsync(Constants.ReportTypes.GET_MERCHANT_LISTINGS_ALL_DATA,
                marketPlace);

var currentLines = File.ReadLines(reportFilePath, encoding).Skip(skip).Take(take).ToArray();
~~~
