### ISSUE TITLE
Sync method not being awaited (deadlock)

### ISSUE THREAD

**Issue by gcuadrado** [abuzuhri/Amazon-SP-API-CSharp#125]
From the change to async methods, the sync methods doesn't work in some projects (for example ASP Webforms).

It's caused by this way to wait the async methods:

` public OrderList GetOrders(ParameterOrderList searchOrderList) =>
            GetOrdersAsync(searchOrderList).ConfigureAwait(false).GetAwaiter().GetResult();`

It can be fixed if it's remplaced by

`public OrderList GetOrders(ParameterOrderList searchOrderList) =>
            Task.Run(() => GetOrdersAsync(searchOrderList)).ConfigureAwait(false).GetAwaiter().GetResult();`

**Comment by abuzuhri** [comment]
Ok I will change all today

**Comment by abuzuhri** [comment]
all are added to v1.2.1
