### ISSUE TITLE
is it possible to get a report into a memory stream

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#137]
hi, is it possible to get a report into a memory stream.

all methods work with downloading the file to a temp folder, we would like to have it in a memory stream

**Comment by abuzuhri** [comment]
Most of report are big and add it’s to memory stream not good idea

**Comment by nafberger** [comment]
first a HUGE Thanks for your library. it's an unbelievable help.

We have a software which manages tens of customers and we get reports and process them, why should it be saved in file then loaded back into memory for processing and insertion into database etc. this is how it was with the old MWS, i would really appreciate if you can add a method that downloads the reports as a stream
