### ISSUE TITLE
ListFinancialEventsByGroupId doesn't return NextToken

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#141]
ListFinancialEventsByGroupId doesn't return NextToken. can the automatic paging please be implemented on that, just like the ListFinancialEvents call its very important because users want to work on each settlement report separately.

to explain. a financial group id means a settlement report, usually those settlement reports run for 100 pages or more. using ListFinancialEvents is not so useful because it doesn't return any reference to the settlement report (or financial event) it belongs to.

**Comment by abuzuhri** [comment]
Hi @nafberger 

Fixed in repo update https://github.com/abuzuhri/Amazon-SP-API-CSharp/commit/ccbeca7cfcee609887fb7daf9b4764d3be2ebda6

Please check and test if its work i will publish to NuGet

**Comment by nafberger** [comment]
thanks big, it will take me till tomo to check. ok?

**Comment by abuzuhri** [comment]
Of course Its OK

**Comment by abuzuhri** [comment]
do you test this ?
Is it working ?

**Comment by abuzuhri** [comment]
Any Update here ?

**Comment by nafberger** [comment]
I tested it's working
