### ISSUE TITLE
Add another way to deal with rate limits when getting orders

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#142]
hi, thanks @abuzuhri  for your work, in our program we manage the stores of many amazon sellers, we don't want to use sleep or delay when getting orders, rather we would like to use up the burst rate and run the code again (via hangfire, etc.) in a minute of 2. as it is now in the library is it throws an exception when u reach the limits. so how can i catch that in code and deal with that gracefully.

**Comment by abuzuhri** [comment]
Hi @nafberger 

I don't think there another way best than the way we implement now, we use all burst and then wait , if you wait 2 min then the burst will count down .

Also you can increase MaxThrottledRetryCount more than 3 (default now)
```Csharp
var amazonConnection = new AmazonConnection(new AmazonCredential()
{
      .
      .
      MaxThrottledRetryCount=3
});
```

**Comment by nafberger** [comment]
lemme explain. we only want to use the burst and then process all the results we got. Waiting is not feasible in our program. So every 7 minutes we use up the 20 bursts to get the latest order updates, so my goal would be to have the program stop the requests as soon the burst is reached without throwing an exception. I believe many many developers use that way, when u deal with hundreds of stores waiting is not an option, and frankly is not needed.

**Comment by abuzuhri** [comment]
We can add option to return the result once arrived to full burst

**Comment by nafberger** [comment]
@abuzuhri sorry for bonging you today. what is the reason for the code in line-39-54 in the RateLimits.cs file.

**Comment by abuzuhri** [comment]
decrease number of burst if the wait time more that expected time mention from API, so you can get more orders without wait if you wait 2 min and order again

**Comment by abuzuhri** [comment]
Add new parameter **MaxNumberOfPages** to **ParameterOrderList** to solve this problem

**Comment by abuzuhri** [comment]
@nafberger  
Please check if this ok

**Comment by abuzuhri** [comment]
@nafberger can you check if the solution work with you

**Comment by nafberger** [comment]
I will be able to check tomorrow, we just had a holiday and I got busy with other stuff

**Comment by nafberger** [comment]
@abuzuhri I am getting back to this issue, in which i am trying to be able to make better decisions when calling amazon API, based on the throttling rates they impose.

your library deals with it beautifully. I would like to ask some improvements, is it okay to continue that on that issue?

1) Its very important to get back the raw header with the rate and burst info, to enable the user to make his own decisions how to code against those limitations.

2) Today I used the get /reports/2021-06-30/reports/{reportId} call and when hitting the max rate the program just starts hanging.  there must be a better way to response to that exception, either bubble up the exception back to the calling code or something else, not  hanging.
