### ISSUE TITLE
Resticted Data Tokens

### ISSUE THREAD

**Issue by jmawebtech** [abuzuhri/Amazon-SP-API-CSharp#145]
Do you support restricted data tokens? I am trying to pull the buyerInfo.BuyerName and ShippingAddress.Name fields on the order, but it fails to pull. 

Here is my path:

/orders/v0/orders/

POST https://sellingpartnerapi-na.amazon.com/tokens/2021-03-01/restrictedDataToken?
{"restrictedResources":{"method":"GET","path":"/orders/v0/orders/","dataElements":["buyerInfo","shippingAddress"]}}

https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide

Is the access token replaced with a restricted data token?

**Comment by abuzuhri** [comment]
Yes we support RDT

look here for all details 

https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/74
