### ISSUE TITLE
Missing GetMyFeesEstimateRequest

### ISSUE THREAD

**Issue by kevinvenclovas** [abuzuhri/Amazon-SP-API-CSharp#154]
Hi,

on the old MWS there is a function GetMyFeesEstimateRequest to calculate the product fees. Is there a new function or how can i request the fees now?

**Comment by abuzuhri** [comment]
Do you try this 
https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference

**Comment by kevinvenclovas** [comment]
Ah nice, is there a sample code for this function in this project?
