### ISSUE TITLE
Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]

### ISSUE THREAD

**Issue by jmawebtech** [abuzuhri/Amazon-SP-API-CSharp#155]
Hi

I am requesting an RDT, but I get this error. Is something wrong with the request or the app? Do I need certain permissions? In my app under roles, I have all the boxes checked.

POST https://sellingpartnerapi-na.amazon.com/tokens/2021-03-01/restrictedDataToken? HTTP/1.1
Accept: application/json
x-amz-access-token: X
x-amz-date: 20220330T131704Z
Authorization: X
Content-Type: application/json
Host: sellingpartnerapi-na.amazon.com
Content-Length: 116
Expect: 100-continue

{"restrictedResources":[{"method":"GET","path":"/orders/v0/orders","dataElements":["buyerInfo","shippingAddress"]}]}

HTTP/1.1 400 Bad Request

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]",
      "details": ""
    }
  ]
}

**Comment by abuzuhri** [comment]
Depending on error message you don’t have permission to access this data

**Comment by jmawebtech** [comment]
Hi,

What permissions are required?

Should this say yes?

![image](https://user-images.githubusercontent.com/1679993/160858344-899caf8e-1978-48ca-8d78-153cef38a3db.png)

**Comment by abuzuhri** [comment]
Can you open developer permission not application permission and check there

**Comment by jmawebtech** [comment]
![image](https://user-images.githubusercontent.com/1679993/160859402-ad3af7c5-ca25-4dd8-86db-d1f578ff6ae7.png)

**Comment by abuzuhri** [comment]
It's look like you have permission, only need to set that option yes in application permission

**Comment by ouzhiman** [comment]
I have the same problem as you, have you solved it?

**Comment by kevinvenclovas** [comment]
Maybe you need to create a new refresh token after receiving or changing permissions

![image](https://user-images.githubusercontent.com/7681603/161203637-3cec6c14-7f74-471e-ba1f-3e92ad7c25a5.png)

**Comment by ouzhiman** [comment]
![image](https://user-images.githubusercontent.com/62372546/161237386-784a9785-2a7e-47c7-96f8-d06b415c929b.png)
Same

**Comment by jmawebtech** [comment]
Hi,

I figured it out. Your old refresh token will fail, if the app and developer had the wrong permissions.

You must give access to the permissions in the developer and app area, which I supplied in my earlier message. Once complete, you must generate a new refresh token at https://api.amazon.com/auth/o2/token.
