### ISSUE TITLE
How can i update the API-Interfaces?

### ISSUE THREAD

**Issue by kevinvenclovas** [abuzuhri/Amazon-SP-API-CSharp#156]
Hi,

how can i update the API-Interfaces to the newest version from amazon?

**Comment by abuzuhri** [comment]
Which endpoint is s not updated ?

**Comment by kevinvenclovas** [comment]
The OrdersV0Api

**Comment by abuzuhri** [comment]
We already use this version

**Comment by kevinvenclovas** [comment]
https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-model -> Got an update 8 day ago

**Comment by abuzuhri** [comment]
Its look like only one marketplace for this changes 

https://github.com/amzn/selling-partner-api-docs/commit/24bcb9b6c6ca2fc827c0d9ae8fab2850fb3edb7d#diff-6b61ccc38ee3c9e61fdb0ad94dad87b05ccdeadaafeebf9b53e5124ededb733e
