### ISSUE TITLE
Exception Thrown Parsing MaterialType in ListCatalogItems

### ISSUE THREAD

**Issue by user6116** [abuzuhri/Amazon-SP-API-CSharp#160]
There is an error generated with many items pertaining to the MaterialType.  Here is the error that is thrown:

> Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path 'payload.Items[13].AttributeSets[0].MaterialType', line 2346, position 66.'

Here is the code that generates the error:

> FikaAmazonAPI.Parameter.CatalogItems.ParameterListCatalogItems plci = new FikaAmazonAPI.Parameter.CatalogItems.ParameterListCatalogItems();
>                     plci.UPC = "079325772114";
>                     plci.MarketplaceId = FikaAmazonAPI.Utils.MarketPlace.US.ID;
> 
> amazonConnection.CatalogItem.ListCatalogItems(plci);

**Comment by abuzuhri** [comment]
Ok I will check , please share the code use used when this error came

**Comment by abuzuhri** [comment]
After check i cant generate this error so need more info please

**Comment by abuzuhri** [comment]
can you share the code give you this error ?

**Comment by abuzuhri** [comment]
any chance to response @user6116

**Comment by user6116** [comment]
Hi there.  I just tested with the latest CSharpAmazonSpAPI and the error still happens.  Here is the code to replicate the issue.  Just replace out the X's with your values.


            var amazonConnection = new AmazonConnection(new AmazonCredential()
            {
                AccessKey = "XXXXXXXXXXXXXXXXXXXX",
                SecretKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                RoleArn = "arn:aws:iam::XXXXXXXXXXXX:role/XXXXXXXXXXXXXXXXXXXXX",
                ClientId = "amzn1.application-oa2-client.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                ClientSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                RefreshToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                MarketPlace = MarketPlace.US,
            });

            FikaAmazonAPI.Parameter.CatalogItems.ParameterListCatalogItems plci = new FikaAmazonAPI.Parameter.CatalogItems.ParameterListCatalogItems();
            plci.UPC = "079325772114";
            plci.MarketplaceId = FikaAmazonAPI.Utils.MarketPlace.US.ID;

            var response = amazonConnection.CatalogItem.ListCatalogItems(plci);

**Comment by TechyChap** [comment]
I'm curious to know what the MaterialType is for this listing.

**Comment by abuzuhri** [comment]
Hi @user6116  and @TechyChap 

I try to replicate the error but i don't have access to US market place i do it for another marketplace and i don't get any error as you can see
![image](https://user-images.githubusercontent.com/3703300/167030616-fa1e3fb3-e33e-49bd-8148-de790fb430d8.png)

**Comment by abuzuhri** [comment]
Please share more details here to be able to help

**Comment by user6116** [comment]
After loading the source code for your dll and stepping through it, I found the JSON that is throwing the exception.  Here it is the JSON:
[json.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/8735766/json.txt)

I've also narrowed it down to this empty MaterialType.  If I hijack the json and remove this node, it parses fine.  So this is the issue:
<img width="362" alt="MaterialType" src="https://user-images.githubusercontent.com/32724297/169447213-baaba34b-0769-49eb-bf53-f6c074f55d72.png">

**Comment by abuzuhri** [comment]
This Look like Bug in amazon the definition is clear as array of string but JOSN is not 

![image](https://user-images.githubusercontent.com/3703300/170447503-aeef0693-9540-4ced-bd77-2b69ef5b3fff.png)

**Comment by abuzuhri** [comment]
Please try to use new API its should work now


### Product GetCatalogItem Version 2022-04-01
```CSharp
var data = await amazonConnection.CatalogItem.GetCatalogItem202204Async(
    new Parameter.CatalogItems.ParameterGetCatalogItem
            {
                ASIN = "B00JK2YANC",
                includedData = new[] { IncludedData.attributes, 
                                       IncludedData.salesRanks,
                                       IncludedData.summaries, 
                                       IncludedData.productTypes, 
                                       IncludedData.relationships, 
                                       IncludedData.dimensions, 
                                       IncludedData.identifiers, 
                                       IncludedData.images }
            });
```

### Product SearchCatalogItems Version 2022-04-01
```CSharp
var data = await amazonConnection.CatalogItem.SearchCatalogItems202204Async(
    new Parameter.CatalogItems.ParameterSearchCatalogItems202204
            {
                keywords = new[] { "vitamin c" },
                includedData = new[] { IncludedData.attributes, 
                                       IncludedData.salesRanks,
                                       IncludedData.summaries, 
                                       IncludedData.productTypes, 
                                       IncludedData.relationships, 
                                       IncludedData.dimensions, 
                                       IncludedData.identifiers, 
                                       IncludedData.images }
            });
```
