### ISSUE TITLE
grant_type is WRONG in GetAccessTokenFromCodeAsync

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#162]
the grant_type  is supposed to be authorization_code

better to let the user decide what grant type to pass in. make it a enum from 3 possible values

authorization_code
client_credentials
refresh_token

but for this particular method, which is the website authorization workflow, it can only be "authorization_code"

**Comment by abuzuhri** [comment]
please check new api version
