### ISSUE TITLE
QUESTION: Fee report available

### ISSUE THREAD

**Issue by kevinvenclovas** [abuzuhri/Amazon-SP-API-CSharp#163]
Hi, on the FBA article there is an available statistic for some fees in the last X days/months. 

![image](https://user-images.githubusercontent.com/7681603/163845397-9d98402a-a6a1-4e17-b161-cd8dcd041e4f.png)

Is there an report to get this data?

**Comment by abuzuhri** [comment]
I can answer this question , its will be better result to get answer from https://github.com/amzn/selling-partner-api-docs and if any change needed in our API we can do it .
