### ISSUE TITLE
please add MaxNumberOfPages enhancement to ParameterListFinancialEvents

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#169]
this will enable to get only the allowed amount, which is the 30 specified in the burst rate

**Comment by abuzuhri** [comment]
Probably it's already in last version

**Comment by nafberger** [comment]
@abuzuhri  no it only has max results per page, i am looking for  MaxNumberOfPages

**Comment by abuzuhri** [comment]
please download last version v1.3.5 from nuget

**Comment by nafberger** [comment]
@abuzuhri ok big thanks

**Comment by abuzuhri** [comment]
Added with last version

**Comment by nafberger** [comment]
@abuzuhri it does not seem to work. 
the while clause is always false
![Screenshot_1](https://user-images.githubusercontent.com/26122027/168180938-01d66037-166e-4d28-9f32-f0b49bf2c4c8.png)


https://www.loom.com/share/a1b026f2ffc54e4090a03af1b6680875

**Comment by nafberger** [comment]
my proposed fix  in loom needs a fix

like this

                if (parameterListFinancials.MaxNumberOfPages.HasValue && countPages >= parameterListFinancials.MaxNumberOfPages)
                    break;

**Comment by abuzuhri** [comment]
Ok tomorrow will fix that
