### ISSUE TITLE
FulFillmentInboundService expects wrong parameters in GetShipmentItems method.

### ISSUE THREAD

**Issue by MMV-Code** [abuzuhri/Amazon-SP-API-CSharp#170]
Hi every one.

I was implementing a call to the GetShipmentItems sign in the AmazonConnection FulFillmentInbound service.

What I noticed, is that the parameters in sign is ParameterListReturnReasonCodes object, which defines next properties:

```
public class ParameterListReturnReasonCodes : ParameterBased
{
   public string SellerSku { get; set; }
   public string MarketplaceId { get; set; }
   public string SellerFulfillmentOrderId { get; set; }
   public string Language { get; set; }
}
```
But checking the documentation for ShipmentItems [endpoint](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#get-fbainboundv0shipmentitems), it needs:

QueryType (Required)
MarketplaceId (Required)
LastUpdatedAfter (Optional)
LastUpdatedBefore (Optional)
NextToken (Optional)

So, I don't know if it's an issue in the implementation or if is that I'm using wrong method, but again, checking the method implementation, it calls the URL for the method I mentioned above.

```
protected class FulFillmentInboundApiUrls
{
   private readonly static string _resourceBaseUrl = "/fba/inbound/v0";
   //Other stuff
   public static string GetShipmentItems
    {
        get => $"{_resourceBaseUrl}/shipmentItems";
    }
}
```

Thanks!, please let me know your comments.

**Comment by abuzuhri** [comment]
Hi @MMV-Code 

I confirm this Bug need to fix ASAP.

**Comment by MMV-Code** [comment]
Thanks @abuzuhri 

Just a question, does this process handle the next token?

I asked because result now is the list of items, and it's not returning the next token (in case that exists) and I checked the code and I don't see that administration, but I would like to confirm it with you!

Thanks!

**Comment by abuzuhri** [comment]
Yes it's handling next token automatically

**Comment by MMV-Code** [comment]
@abuzuhri  yes thank you I was checking wrong method with same name.

Thanks for your response.
