### ISSUE TITLE
Hi @abuzuhri, thanks for providing the rate limiting. But it looks like I am still getting throttled on this particular function:

### ISSUE THREAD

**Issue by abuzuhri** [abuzuhri/Amazon-SP-API-CSharp#178]
Hi @abuzuhri, thanks for providing the rate limiting. But it looks like I am still getting throttled on this particular function:
connection.CatalogItem.ListCatalogItemsAsync(). 
I am getting "You exceeded your quota for the requested resource." error after about 30 requests. I tried to rate limit myself to 1 request per second and still getting it even though the rate is supposed to be 5 times per second. Any ideas?  

It's a little hard to debug since the rate limit header is not exposed by the library.

_Originally posted by @igoryan-k in https://github.com/abuzuhri/Amazon-SP-API-CSharp/discussions/109#discussioncomment-2678703_

**Comment by abuzuhri** [comment]
If you change the setting to **IsActiveLimitRate = false** then the application will not handling the limit 
```CSHARP
AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
            {
                ..
                IsActiveLimitRate = false
            });
```
I do test for this method and it look like it working perfect 
![image](https://user-images.githubusercontent.com/3703300/167035570-5fd990f5-bb3d-40f0-8ec4-44311e9d2cda.png)

**Comment by abuzuhri** [comment]
@igoryan-k please recheck if you have another instance running in different server that take the limit or you share the Keys with another ...

**Comment by abuzuhri** [comment]
@TechyChap share this code that working perfectly with him in .net core 


`public class AmazonListingService : IAmazonListingService
    {
        private readonly AmazonConnection _connection;

        public AmazonListingService(AmazonConnection connection)
        {
            _connection = connection;
        }

        public async Task<ListingsItemSubmissionResponse> PutListingsItemAsync(ParameterPutListingItem listing)
        {
            return await _connection.ListingsItem.PutListingsItemAsync(listing);
        }
    } `

**Comment by TechyChap** [comment]
If you are changing settings then perhaps something like IOptionsMonitor might work - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0

I need to support multiple market places so my plan is to implement multiple connections, one for each marketplace. So won't be changing parameters once created. Not written the code for that yet but will likely be using a named instance.

https://stackoverflow.com/questions/39174989/how-to-register-multiple-implementations-of-the-same-interface-in-asp-net-core

**Comment by abuzuhri** [comment]
@rcalv002 are you still facing problem ?

**Comment by rcalv002** [comment]
> @rcalv002 are you still facing problem ?

Yes indeed

**Comment by rcalv002** [comment]
Yes

**Comment by abuzuhri** [comment]
Do you try last version we fix that

**Comment by rcalv002** [comment]
Hi abuzuhri I havent tried in a while, Actually I didn't respond 6 hours ago.. very strange.

**Comment by ProNotion** [comment]
I am currently getting this for requests that are made to the `/fba/inventory/v1/summaries` endpoint.

**Comment by RenzoF** [comment]
@ProNotion have you got multiple instances running at the same time? or do you restart the application every time it runs? 
The Throttle info is per instance, I have separate workers calling the API so I had to do a workaround to save the Throttle details in a file, ideally, we should split this into a database so that it can scale.

**Comment by ProNotion** [comment]
Only 1 instance but during development it is regularly restarted so perhaps that is the cause. I agree with the scalability of it needing to be addressed somehow.
