### ISSUE TITLE
amazonConnection.ProductPricing ignores IsActiveLimitRate

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#185]
I am using the amazonConnection.ProductPricing call and specifying  AmazonCredential.IsActiveLimitRate to 'true' but its not working the code keeps on running and we are getting throttling errors

**Comment by abuzuhri** [comment]
@nafberger is the problem with all methods ?

**Comment by nafberger** [comment]
no just that

**Comment by abuzuhri** [comment]
You don't mention which method or API in this service

**Comment by abuzuhri** [comment]
after 30 min testing and keep running I don't find any problem  

![image](https://user-images.githubusercontent.com/3703300/167950542-47370f6d-509b-4f6b-b450-1ad4955d22e6.png)


most probably you have another instance running use same keys in different server

**Comment by nafberger** [comment]
the issue is still here 

https://www.loom.com/share/93b955fc384a46d4adc483d87553217c

dono why its not respecting the limit.

can u please check again

**Comment by abuzuhri** [comment]
Even if it's throw exception it's will try for 3 times then throw , if your free want to connect to your laptop to debug and see from where this error came

**Comment by nafberger** [comment]
I am not sure if its your code or a bug in amazon. 

when u try the code with 1 Asin in the payload it will never crash. when u try it with the full 20 it will crash

**Comment by nafberger** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/368

**Comment by abuzuhri** [comment]
In old API MWS the rate was sharing between many methods and the documents was very clear which methods share same rate .

Maybe the case here same but they don't mention in documentation.

Personally I use getListingOffers with same api and it's keep running 24h/7d no stop and never have same problem 

https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getlistingoffers

**Comment by abuzuhri** [comment]
Hi @nafberger , 

Do you still facing this error ?

**Comment by nafberger** [comment]
didn't look u can close the issue, its not your code its amazon craziness
