### ISSUE TITLE
Restricted Reports not supported

### ISSUE THREAD

**Issue by wgcsteve** [abuzuhri/Amazon-SP-API-CSharp#186]
Hi abuzuhri,

I am trying to follow the examples for Orders, but I cannot call a Restricted Report.  The restricted report types are defined here:
- https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-report-types

One of the hurdles I am facing is that everything is Protected in ApiUrls.cs, so I am hardcoding the Reporting URL, but I have nowhere to pass the PII parameter.  

Am I silly, or is this not supported at the moment?

**Comment by abuzuhri** [comment]
please last version from nugget and then try the following code

```Csharp
var data2 = amazonConnection.Reports.CreateReportAndDownloadFile(ReportTypes.GET_EASYSHIP_DOCUMENTS, startDate, null, null);

// OR USER 

var data = amazonConnection.Reports.GetReportDocument("50039018869997",true);
```

**Comment by abuzuhri** [comment]
Please install nugget v1.3.9 , and test it , i cant test this because i don't have access to PII data

**Comment by wgcsteve** [comment]
Hi Tareq,  I'm still poking around but **CreateReportAndDownloadFile** does not work.

Line 70 in RequestService.cs, PiiObject comes through as Null.  And I get the same Unauthorized exception I normally would when ExecureRequestAsync fires.

I tried changing the tokenDataType to be PII when you call **RefreshTokenAsync** on line 75, but then I am presented with the following error:

```

Amazon Api didn't respond with Okay, see exception for more details{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Empty target resource arguement found",
      "details": ""
    }
  ]
}
```

Trying to debug this in my free time.  But if you have any ideas, let me know.

**Comment by wgcsteve** [comment]
That's fine. I'll poke around later this week when I have some spare cycles.  Might even submit my own pull request if I can get it working.

Thanks for taking a look at it.

**Comment by nafberger** [comment]
https://github.com/amzn/selling-partner-api-docs/issues/615

see here no need for RDT if your app has PII permissions u can just ask fir the report like regular report
