### ISSUE TITLE
Unauthorized response on feeds upload

### ISSUE THREAD

**Issue by davhol86** [abuzuhri/Amazon-SP-API-CSharp#190]
Hi @abuzuhri,

i used an older version of your solution, to upload pdf invoices with the feeds endpoints.
I had to change it a little bit so that i should work with the IAM user ARN insteat.

But I allways get the following error when trying to create the feed (/feeds/2021-06-30/feeds):

> {
>     "errors": [
>         {
>             "code": "Unauthorized",
>             "message": "Access to the resource is forbidden",
>             "details": ""
>         }
>     ]
> }

I've also tried with Postman, with the same result, allways when i try to create the feed.

Have you any idea what the problem could be?

On APP-registration process i've given all permissions.
The access parameters are also rigth cause i can for example call the MarketplaceParticipations with Postman and it works.

**Comment by abuzuhri** [comment]
There are many try to use user instead of roles and not work with them ، I can't do investigation here because the true way to use roles not user
