### ISSUE TITLE
Inventory feed 'restock date' field is asserted as DateTime, but Amazon doesn't like it

### ISSUE THREAD

**Issue by dooferorg** [abuzuhri/Amazon-SP-API-CSharp#206]
When doing the feed type ' POST_INVENTORY_AVAILABILITY_DATA', setting the RestockDate with an item quantity is apparently required for Amazon. However, using DateTime.Now for the value results in it being rejected by Amazon as invalid.

I would expect this API library to set the appropriate timestamp format that is acceptable by Amazon.

**Comment by abuzuhri** [comment]
The feed xml is totally your responsibility we are not going to change xml you submitted

**Comment by dooferorg** [comment]
The XML is generated from the GetXML() method of ConstructFeedService .. so, it actually is from your API library :)

Since YOU have defined the objects as DateTime in the InventoryMessage and not a string time, then i believe this issue is warranted. However, I worked around it by not specifying that date and just using a fulfillmentlatency.

**Comment by abuzuhri** [comment]
You should add date in UTC formate then it’s will work , it’s standard you need to use UTC time in the library
