### ISSUE TITLE
NotificationMessages nullable types

### ISSUE THREAD

**Issue by CrineTech** [abuzuhri/Amazon-SP-API-CSharp#222]
Hi, if you take a look on the [official Amazon documentation](https://spapi.cyou/en/use-case/notifications-use-case-guide-v1.html#any-offer-changed) for the ANY_OFFER_CHANGED notification, you can see that there are many optional fields.

Fields wich have a complex types (for example the Offer.SellerFeedbackRating) are handled correctly, but fields that are defined as optional by amazon documentation, but are of a simple type (for example the boolean Offer.IsFeaturedMerchant) have not been defined as nullable types. You can see for instance [there](https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI/NotificationMessages/Offer.cs).

This issue is present with every simple type optional field in the notification payload. This is important, without a nullable type it seems that, if not found, Offer.IsFeaturedMerchant defaults back to false, but this is a different information. If not present we don't know if it is a featured merchant or not. If it is present and false we know that it is not a featured merchant. The same thing happens with optional integers and doubles.

I would like to know your opinion, if you agree that those fields should be nullable, i can send a pull request, at least for the ANY_OFFER_CHANGED related classes.

**Comment by abuzuhri** [comment]
Hi @CrineTech 

This change come in May , and i try to finish all ASAP

https://github.com/abuzuhri/Amazon-SP-API-CSharp/discussions/191
