### ISSUE TITLE
Missing waittimeseconds parameter in SQS receiveMessageRequest

### ISSUE THREAD

**Issue by CrineTech** [abuzuhri/Amazon-SP-API-CSharp#223]
Hi, if you take a look at tihs block of code from [here](https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI/Services/NotificationService.cs) - starting on row 126 at the moment

```
            using (var amazonSQSClient = new AmazonSQSClient(awsAccessKeyId, awsSecretAccessKey, Region))
            {
                ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(SQS_URL);
                receiveMessageRequest.MaxNumberOfMessages = 10;
```

In the request the WaitTimeSeconds parameter have not been set. From what i know, this causes the request to return immediately if there is no message in the queue (possible situation in the nighttime, when there are really few price changes or for queues related to less frequent events, like reports). This will cause in those situations so much empty responses, that Amazon will be glad to bill at the end of the month

If we add this line `receiveMessageRequest.WaitTimeSeconds = 20;` We can use the long polling feature.
In this way, if there are more than 10 messages in the queue the response will come immediately, otherwise the response will be delayed and returned when 10 messages are received or 20 seconds timeout is elapsed.

This can drastically reduce the number of empty responses and subsequent requests, i cannot see any disadvantage of using it.
Please note that 20 seconds is the maximum value allowed from amazon for long polling, so is not possible to specify a greather value.

**Comment by abuzuhri** [comment]
Please check v1.3.21

**Comment by CrineTech** [comment]
This looks perfect, thank you so much!
