### ISSUE TITLE
Self-Authorize Implementation

### ISSUE THREAD

**Issue by dhart-ebsco** [abuzuhri/Amazon-SP-API-CSharp#224]
The video mentioned adding vendor (self-authorization).  Do you still have plans to implement the self-authorization to your API?  If so, do you know when?

**Comment by abuzuhri** [comment]
what you mean self-authorization ? its token you get from amazon not from library.

**Comment by Paul-J-Barrett** [comment]
There is extensive documentation on creating the credentials you need in the SP docs. start here https://developer-docs.amazon.com/sp-api/docs/registering-as-a-developer   It can get confusing just take it slow.
