### ISSUE TITLE
Getting a restrictedDataToken returns NullReferenceException

### ISSUE THREAD

**Issue by zinsmeik** [abuzuhri/Amazon-SP-API-CSharp#24]
Hi,

we have PII Approval and try to retrieved the customer information.
Error 

```
System.NullReferenceException
  Nachricht = Object reference not set to an instance of an object.
  Quelle = FikaAmazonAPI
   at FikaAmazonAPI.Services.RequestService.RefreshToken(TokenDataType tokenDataType, CreateRestrictedDataTokenRequest requestPII) in U:\VS2019\80_SellerAPI\CSharpAPI\Source\FikaAmazonAPI\Services\RequestService.cs:line 199
```

It seams the token returned from Amazon is not stored within the class. If I debug I get a valid restricedAccestoken

 response | "StatusCode: OK, Content-Type: application/json, Content-Length: 2289)" | RestSharp.IRestResponse<FikaAmazonAPI.AmazonSpApiSDK.Models.Token.CreateRestrictedDataTokenResponse> {RestSharp.RestResponse<FikaAmazonAPI.AmazonSpApiSDK.Models.Token.CreateRestrictedDataTokenResponse>}

  | Content | "{\"expiresIn\":3600,\"restrictedDataToken\":\"Atz.sprdt\|AYABeIAyqzW4Jhn1sfSt0PPWL+0AAAABAAdhd3Mta21zAEthcm46YXdzOmttczpldS13ZXN0LTE6NTM2MDA0NjQ5NjEwOmtleS9mODYzNDkxYy04MjMzLTRhYmEtYjAwMS1kY2I4NzQ3OTk2MGMAuAECAQB4d/LtWw/BabmPrZP02h8ksVpUDeZIcEQeXUpuUL9C+OoBgdnesVyT6gYqwwPvU8gzlwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9........

But the token is not stored as response.Data Payload is NULL

```
        public CreateRestrictedDataTokenData CreateRestrictedDataToken(CreateRestrictedDataTokenRequest createRestrictedDataTokenRequest)
        {
            CreateAuthorizedRequest(TokenApiUrls.RestrictedDataToken, RestSharp.Method.POST, postJsonObj: createRestrictedDataTokenRequest);
            var response = ExecuteRequest<CreateRestrictedDataTokenResponse>();
            if(response!=null && response.Payload!=null)
                return response.Payload;
            return null;
        }

```
Checking the code (I am not a professional programmer) it looks that the Response.Content is not parsed into the Response.Data

```
      protected T ExecuteRequest<T>() where T : new()
        {
            Request = TokenGeneration.SignWithSTSKeysAndSecurityToken(Request, RequestClient.BaseUrl.Host, AmazonCredential);
            var response = RequestClient.Execute<T>(Request);
            SleepForRateLimit(response.Headers);
            ParseResponse(response);            
            if (response.StatusCode==HttpStatusCode.OK && !string.IsNullOrEmpty(response.Content) && response.Data == null)
            {
                response.Data = JsonConvert.DeserializeObject<T>(response.Content);
            }
            return response.Data;
        }

```

JsonConvert.DeserializeObject is never called because response.Data is NULL
Therefore CreateRestrictedDataTokenData returns NULL and the token is not stored.

I hope this makes it clear, please feel free to ask for more details.

Kind Regards

**Comment by abuzuhri** [comment]
Hi @zinsmeik ,

When its come to **RestrictedDataToken** , I mention in readme file that we don't test this part we are not approved to access data token .

If you are interested you can fix this bug and send the correction or contact me at tareq.abuzuhri [a] gmail.com to help with more details and easy test this bug

**Comment by abuzuhri** [comment]
@zinsmeik  any update plz can you send email with all details

**Comment by abuzuhri** [comment]
Hi @zinsmeik Can you please give the required information ?

**Comment by zinsmeik** [comment]
Hi 

sorry was away a few days. I send you a email with the details. Hope thats fine for you.

**Comment by abuzuhri** [comment]
Thanks @zinsmeik for help to solve this bug
