### ISSUE TITLE
GetAuthorizationCode "The application isn't configured with roles"

### ISSUE THREAD

**Issue by tank104** [abuzuhri/Amazon-SP-API-CSharp#248]
Hi,
I am trying to use GetAuthorizationCode and have the below code.
I always get the error: "FikaAmazonAPI.AmazonSpApiSDK.Models.Exceptions.AmazonInvalidInputException: 'The application isn't configured with roles.'"

Any idea why this is?

I have the IAM ARN in our app set to the role "arn:aws:iam::XXX:role/Amazon-SP-API-Role"

Questions I have :
Should ClientId and ClientSecret by the LWA Credentials?  Or some other credentials?  (My App ID is different to the LWA Client Identifier.  In the code example it says to use "Your amazon app id", but elsewhere the example looks more like LWA ( "amzn1.application.xxx" vs "amzn1.sellerapps.app..xxx")?
If it is not LWA Credentials where do I get the ClientSecret for my app from? (I only can see LWA or MWS).

Any help appreciated - deadline looming from Amazon.  
Thanks!

```
AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
{
  AccessKey = "AKI",
  SecretKey = "KV",
  RoleArn = "arn:aws:iam::XXX:role/Amazon-SP-API-Role",
  //LWA Credetniasl
  ClientId = "amzn1.application-oa2-client.CCCC", //NOT "amzn1.sellerapps.app.XXXX",
  ClientSecret = "3e1CCCC",
  //Don't set for AuthCode - RefreshToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  MarketPlace = MarketPlace.Australia,
});

var result = amazonConnection.Authorization.GetAuthorizationCode(new ParameterAuthorizationCode { sellingPartnerId = "Axxxx", developerId = "5110-xxxx-xxxx", mwsAuthToken = "amzn.mws.6xxxxxxx" });
```

**Comment by abuzuhri** [comment]
Do you can get orders without problems ?

**Comment by JonKragh** [comment]
@tank104 are you trying to migrate MWS to SPAPI users as well? Deadline looming for us too :) This is not working for me either.

**Comment by tank104** [comment]
@abuzuhri sorry I replied via email but didn’t come through. We only have MWS users but will try that.

@JonKragh yup same with us, and getting very worried, left it too late!

**Comment by tank104** [comment]
@abuzuhri just wondered if you could answer these questions to help (although I have tried all combinations):

Should ClientId and ClientSecret by the LWA Credentials? Or some other credentials? (My App ID is different to the LWA Client Identifier. In the code example it says to use "Your amazon app id", but elsewhere the example looks more like LWA ( "amzn1.application.xxx" vs "amzn1.sellerapps.app..xxx")?
If it is not LWA Credentials where do I get the ClientSecret for my app from? (I only can see LWA or MWS).

**Comment by tank104** [comment]
Also I can confimr GetOrders work if I add valid RefreshToken - just not GetAuthorisationCode.

**Comment by abuzuhri** [comment]
Maybe we need to setup meeting to understand the problem and others guys can join .

I'm on vacation now but I will try my best to help as much as I can .

**Comment by tank104** [comment]
I have logged a ticket with Amazon, apparently 1 business day reply, so let’s see response and I will update here

**Comment by tank104** [comment]
@abuzuhri have you got GetAuthorizationCode to work before fine?

**Comment by tank104** [comment]
Ok this is working now - seem you have to wait until the Amazon App is fully published for this to woek (which took 10 days).

I use the token from this to call GetAccessTokenFromCodeAsync - this gives me an access token (not a refresh token), so not sure how I actually can use an access token in the code though?  I can see in AmazonConnection a RefreshToken (but we don't get that back.

Possibly if this issue is re-fixed: https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/123 then it might be I just use that refresh token?

**Comment by JonKragh** [comment]
@tank104 did you make any code updates to get this working? I just grabbed the latest merge and this is still failing for me.

**Comment by tank104** [comment]
I added a new method GetRefreshTokenFromCodeAsync - that gets access and refresh token.

(I didn't want to change the existing method, although I feel its not useful anymore, since you need refresh token to use this library)

**Comment by abuzuhri** [comment]
I'm ready work with this can we have meeting @JonKragh  @tank104

**Comment by tank104** [comment]
It’s all working for me now with the code change thanks!

**Comment by abuzuhri** [comment]
Please give us sample of code you use to help @JonKragh also

**Comment by tank104** [comment]
private string GetRefreshTokenForMerchant(AmazonCredential amazonCredentials, string amazonMerchantId, string amazonDeveloperId, string amazonAuthorisationToken)
    {
      AmazonConnection amazonConnection = new AmazonConnection(amazonCredentials);
      var result = amazonConnection.Authorization.GetAuthorizationCode(new ParameterAuthorizationCode
      {
        sellingPartnerId = amazonMerchantId,
        developerId = amazonDeveloperId,
        mwsAuthToken = amazonAuthorisationToken
      });
      var token = amazonConnection.Authorization.GetRrefreshTokenFromCodeAsync(result, "").GetAwaiter().GetResult();
      return token.refresh_token;
    }

**Comment by tank104** [comment]
I don't have any refresh tokens yet to try, we were just trying to get refresh token from MWS token but stuck on that.

Did you see my questions? Just wanted to confirm the credentials.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
