### ISSUE TITLE
GetOrders and NextToken

### ISSUE THREAD

**Issue by HakanL** [abuzuhri/Amazon-SP-API-CSharp#254]
In my integration I may download 10s of 1000s of orders. As these are downloaded I need to save them off to my database and then process the next batch. The GetOrdersAsync implementation is currently loading everything into memory until there are no more NextToken, and at the same time there is an exposed method called GetGetOrdersByNextTokenAsync, but there isn't a method to just get one "page"/batch of orders and then return the NextToken. How can this be achieved?

**Comment by wang2958** [comment]
Call the GetGetOrdersByNextTokenAsync method without passing the NextToken parameter in the first request, and you should get the first page you need.

**Comment by HakanL** [comment]
Thanks @wang2958, that should do it. Probably not the most user friendly way, perhaps some additional code comments/summary details could help future developers?

**Comment by abuzuhri** [comment]
If you still need it we can do something to fix

**Comment by HakanL** [comment]
Nah, just a suggestion to improve the API. Most APIs have a GetXXX and then GetXXXNextToken.

**Comment by abuzuhri** [comment]
We feel here it's more user friendly but if all agree we need it then we can do it .

**Comment by abuzuhri** [comment]
Here sample how you can handle it

```Csharp
            ParameterOrderList serachOrderList = new ParameterOrderList();
            serachOrderList.CreatedAfter = DateTime.UtcNow.AddMinutes(-600000);
            serachOrderList.MaxNumberOfPages = 1;
            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Shipped);

            serachOrderList.AmazonOrderIds = new List<string>();

            var orders = amazonConnection.Orders.GetOrders(serachOrderList);
            var nextPageToken = orders.NextToken;
            while (!string.IsNullOrEmpty(nextPageToken))
            {
                var moreOrders = amazonConnection.Orders.GetGetOrdersByNextToken(nextPageToken, serachOrderList);
                nextPageToken = moreOrders.NextToken;
            }
```

**Comment by HakanL** [comment]
Very good, thank you! IMHO this is what all methods in all services that handle paging should do, it's dangerous to load everything into memory in your library, it should be handled by the caller.
