### ISSUE TITLE
GetOrderMetrics fails when firstdayofweek added. 

### ISSUE THREAD

**Issue by MasterTyrr** [abuzuhri/Amazon-SP-API-CSharp#258]
When requesting data via getordermetrics the request fails with code "InvalidInput" with a message of "{getOrderMetrics.arg7\u003dmust match \"(monday|sunday)\"}". I believe this is because the constant values are capitalized when they should be lowercase.

**Comment by abuzuhri** [comment]
Can you share the code you use

**Comment by MasterTyrr** [comment]
`DateTime queryStart = DateTime.Now.AddDays(-7);
    DateTime queryEnd = DateTime.Now;
    var parameters = new ParameterGetOrderMetrics();
    parameters.marketplaceIds = new MarketplaceIds();
    parameters.marketplaceIds.Add(MarketPlace.US.ID);
    parameters.interval = queryStart.ToString("yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture) + "Z--" + queryEnd.ToString("yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture) + "Z";
    parameters.granularity = Constants.GranularityEnum.Total;
    parameters.firstDayOfWeek = Constants.FirstDayOfWeek.Sunday;

    var sales = amazonConnection.Sales.GetOrderMetrics(parameters);`

**Comment by MasterTyrr** [comment]
Thank you for the fix! It is working now.
