### ISSUE TITLE
AdjustmentBuyerPrice properties are all private

### ISSUE THREAD

**Issue by tank104** [abuzuhri/Amazon-SP-API-CSharp#260]
Hi,
Trying to do item adjustments via the feed and  I noticed that AdjustmentBuyerPrice are all private.

Have PR to fix this: (assume its not by design):
https://github.com/abuzuhri/Amazon-SP-API-CSharp/pull/259

**Comment by abuzuhri** [comment]
fixed  CSharpAmazonSpAPI -Version 1.4.8
