### ISSUE TITLE
SubmitFeed's messy code problem

### ISSUE THREAD

**Issue by Kofslime** [abuzuhri/Amazon-SP-API-CSharp#264]
Hello, I'm developing a program face to Japanese. I want to use the interface of SubmitFeed to Submit a feed which feedType is "_POST_FLAT_FILE_FULFILLMENT_DATA_" . At first , I choosed the "TXT" as the ContentType to submit , because the official document say this feedType can be sumit as a form text rather than "XML",but an error occured. I find the parameter needs local filepath, but my interface needs to run on a server. So I choosed the "XML" as the ContentType to submit , it seems this feed submitted successfully, but my Japanese consumer said the feed submitted was messy code  . What should I do ? (crying.jpg)

**Comment by abuzuhri** [comment]
Please share code you are use and we will try to help you

**Comment by Kofslime** [comment]
//paramfeedType is _POST_FLAT_FILE_FULFILLMENT_DATA_                
FeedType paramfeedType = (FeedType)System.Enum.Parse(typeof(FeedType), feedType);

//XmlContent = "order-id\torder-item-id\tquantity\tship-date\tcarrier-code\tcarrier-name\ttracking-number\tship-method\tcod-collection-method\t\r\n60X-XX03170-XXX9005\tXXX55041758382\t1\t2022-07-XXT00:00:00+09:00\tOther\tヤマトXX\t\tクロXXXX便\t\t\r\n\0"
//Some private information is covered with an "X"
          
string XmlContent = Encoding.GetEncoding("Shift_JIS").GetString(ms.ToArray());

 List<string> marketPlaceIds = new List<string>
{
    marketplaceId
};

var createFeedDocumentResult = amazonConnection.Feed.SubmitFeed(XmlContent, paramfeedType, marketPlaceIds, null, ContentType.XML);

**Comment by abuzuhri** [comment]
Try use this feed and check if its work with you 

#### Feed Submit for change FULFILLMENT DATA (add tracking number for shipment)
```CSharp

ConstructFeedService createDocument = new ConstructFeedService("{sellerId}", "1.02");

var list = new List<OrderFulfillmentMessage>();
list.Add(new OrderFulfillmentMessage()
    {
       AmazonOrderID = "{orderId}",
       FulfillmentDate = DateTime.Now.ToString("yyyy-MM-dd'T'HH:mm:ss.fffK"),
       FulfillmentData = new FulfillmentData()
          {
              CarrierName = "Correos Express",
              ShippingMethod = "ePaq",
              ShipperTrackingNumber = "{trackingNumber}"
           }
    });
    createDocument.AddOrderFulfillmentMessage(list);

    var xml = createDocument.GetXML();

    var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_ORDER_FULFILLMENT_DATA);

```

**Comment by Kofslime** [comment]
Thank you for your answer. I gave it a try,  it seemed to work. But because of the incomplete attribute of FulfillmentData (lack of "quantity", for example, I can't submit the number of items that buyers can buy). The feedType types to be submitted include _POST_FLAT_FILE_INVLOADER_DATA_ and _POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_. If you use the similar feedType method, Should "POST_PRODUCT_DATA" and "POST_PRODUCT_PRICING_DATA" be replaced? In addition, when getting upload status, feedDocument starts from the original "ProcessingSummary:

MessagesProcessed		1

MessagesSuccessful		1

"Becomes an XML document. It seems that the previous MWS interface does not submit the Feed in XML format. Is there a way to submit the Feed without XML format as MWS does? (Currently direct call can also upload, but there is garble)

**Comment by Kofslime** [comment]
Thank you for your answer. I gave it a try, and it seemed to work. But because of the incomplete attribute of FulfillmentData (lack of "quantity", for example, I can't submit the number of items that buyers can buy). The feedType types to be submitted include _POST_FLAT_FILE_INVLOADER_DATA_ and _POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_. If I use the similar feedType method, should "POST_PRODUCT_DATA" and "POST_PRODUCT_PRICING_DATA" be replaced? In addition, when getting upload status, feedDocument starts from the original 
"ProcessingSummary:

MessagesProcessed		1

MessagesSuccessful		1
"
becomes an XML document. It seems that the previous MWS interface does not submit the Feed in XML format. Is there a way to submit the Feed without XML format as MWS does? (Currently direct call can also upload, but there is messy code)

**Comment by abuzuhri** [comment]
Yes you can submit feed in many format you can take look to source code and check how we do that
