### ISSUE TITLE
Cancel Fulfillment Outbound service order?

### ISSUE THREAD

**Issue by HakanL** [abuzuhri/Amazon-SP-API-CSharp#266]
I'm looking for the method to cancel an outbound Fulfillment order (FulfullmentOutboundService) and I've found the code that seems to call the API for Cancel, but it's labeled Update(!):
https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/f9fea9878e30394dc77e18b8b764e582d4c0d52c/Source/FikaAmazonAPI/Services/FulFillmentOutboundService.cs#L125

**Comment by abuzuhri** [comment]
Here the documentation for this endpoint 


https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-api-v2020-07-01-reference

Please check it and let us know if you need more help

**Comment by HakanL** [comment]
The issue is that the API call is to cancel an order, but the name of the method in the service (linked above) says "UpdateFulfillmentOrderAsync, which is wrong.

**Comment by abuzuhri** [comment]
Yes but this how amazon name it 

https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/5bdf51fecb66325b58f7b1c548cc5946471da7f0/Source/FikaAmazonAPI/Services/FulFillmentOutboundService.cs#L125

**Comment by HakanL** [comment]
> Yes but this how amazon name it
> 
Hmm, not if you look at their API, it says operation CancelFulfillmentOrder:
https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-api-v2020-07-01-reference#cancelfulfillmentorder

**Comment by abuzuhri** [comment]
I'm Amazon the name true it's only the name in our library was mistake and changed now
