### ISSUE TITLE
Getting "Error getting LWA Access Token" on every call

### ISSUE THREAD

**Issue by r4vvy** [abuzuhri/Amazon-SP-API-CSharp#267]
I'm trying to access the SP API using the marketplace Germany. Even if i just run your sample code with own credentials the **System.SystemException: 'Error getting LWA Access Token'** is thrown. Inner Exception is: **IOException: Unsuccessful LWA token exchange** More in exception detail.
[exception_detail.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/9219481/exception_detail.txt)

I currently have a workaround where I modified the **SignWithSTSKeysAndSecurityTokenAsync()** function in **FikaAmazonAPI.Services.TokenGeneration** to always add the Region **EUCentral1** to the STSClient construction:
```
using (var STSClient = new AmazonSecurityTokenServiceClient(amazonCredential.AccessKey, amazonCredential.SecretKey, Amazon.RegionEndpoint.EUCentral1))
               
```
For some reason it works perfectly fine like this.

**Comment by abuzuhri** [comment]
Many client from Germany use library without any problem 

It's look like problem with setup AWS keys and roles .

**Comment by r4vvy** [comment]
I double checked my keys and actually found a mistake there. I'm still getting an error when trying to upload a feed using the right keys but role assumption seems to work. I wrongly assumed I was still getting the same error that was thrown when I was using an older version of the library before.
