### ISSUE TITLE
How to refund orders

### ISSUE THREAD

**Issue by Tajanos** [abuzuhri/Amazon-SP-API-CSharp#268]
Hi, I am using 1.4.13 and I get this error: "This is a malformed or invalid XML document. For more details, please see http://sellercentral.amazon.com/gp/help/22971" with the attached XML.

Do you have an example of how to refund orders? I am not even sure if I should be using .ItemPriceAdjustments or .DirectPaymentAdjustments

[xml.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/9223211/xml.txt)

**Comment by abuzuhri** [comment]
I can't see this url http://sellercentral.amazon.com/gp/help/22971

I don't have access to USA region .

**Comment by Tajanos** [comment]
It just says this:

Error 5000
This is a malformed or invalid XML document.

The XML document you are posting does not appear to be valid. Please use the appropriate XSD and plug-ins to verify the document's structure. XSDs describe the necessary structure of your XML document.

**Comment by Tajanos** [comment]
I've been researching this all day and there doesn't seem to be a working sample of an XML-based refund anywhere on the Internet. If anyone has one, please kindly share.

**Comment by abuzuhri** [comment]
Do you see this sample 


https://github.com/abuzuhri/Amazon-SP-API-CSharp#feed-submit-for-change-order-adjustments

**Comment by Tajanos** [comment]
Yes, in my first post here I attached xml that was produced by code based on this sample.

It seems that the xml doesn't validate against the xsd. I got this from an online validator: "Cannot Resolve The Name 'BaseCurrencyAmount' To A(n) 'type Definition' Component."

I am wondering if anyone is able to refund orders with xml.

**Comment by Tajanos** [comment]
I got it to work using the MWS Scratchpad. See attached XML. It seems to want the ItemPriceAdjustments node with various Component nodes in it.

[valid.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/9224077/valid.txt)

**Comment by abuzuhri** [comment]
Yes this xml was tested with one of developer who add it here also

**Comment by Tajanos** [comment]
Yeah, see my comment above. I am not sure about DirectPaymentAdjustments vs ItemPriceAdjustments. All the samples that I was able to find of other people doing this seem to use ItemPriceAdjustments. And the flat file also seems to require specifying various components of the refund, like the main amount, tax, shipping, shipping tax, etc.

**Comment by abuzuhri** [comment]
> Yeah, see my comment above. I am not sure about DirectPaymentAdjustments vs ItemPriceAdjustments. All the samples that I was able to find of other people doing this seem to use ItemPriceAdjustments. And the flat file also seems to require specifying various components of the refund, like the main amount, tax, shipping, shipping tax, etc.

As i know if the XML work in MWS Scratchpad then it should work in SP API

**Comment by abuzuhri** [comment]
do you found the true xml feed for refund ?
