### ISSUE TITLE
PurchaseShipment Returns faulty Label

### ISSUE THREAD

**Issue by FrederikAFS** [abuzuhri/Amazon-SP-API-CSharp#269]
Hello, iam using the PurchaseShipment function to create and buy a label from amazon.
The Labelstream is supposed to be a Base64Stream but it always looks like this: "iVBORw0KGgo...AAAARK5CYII=(Truncated)"
This is from using the Sandbox system.

Am I using the API wrong or why is the Stream not Base64?

**Comment by abuzuhri** [comment]
Please share the code we will try from our side but since the data came like that from amazon then its probably you need to open case in amazon not here

**Comment by FrederikAFS** [comment]
```
amazonCon = AuthorizationHelper.GetConnectionSandbox()
            Dim req = New PurchaseShipmentRequest(
                Constants.TestCase200,
                shipTo, shipFrom, shipDate.ToUniversalTime(),
                ServiceType.Standard,
                New ContainerList() From {containerItem},
                New LabelSpecification(LabelFormatEnum.PNG, LabelStockSizeEnum._4x6))
            Dim code = Await amazonCon.Shipping.PurchaseShipmentAsync(req)
            Dim byt = Convert.FromBase64String(SafeConvert.ToStr(code.LabelResults.First().Label.LabelStream))
```

I create my Sandbox AmazonConnection with the TestCase200 as ClientReferenceID. In the Container I also submit the TestCase200 as ContainerReferenceID. After that im calling the PurchaseShipment which returns me the PurchaseShipmentResult and everything seems fine besides the LabelStream which is not a Base64String.

**Comment by abuzuhri** [comment]
Do you solve this problem or still need us to look at it ?

**Comment by FrederikAFS** [comment]
I wrote the Amazon SP API Support but they did not respond yet. If i get an answer from them i will post my solution here. But I think the problem comes from the Amazon SP API not from your Wrapper.

**Comment by abuzuhri** [comment]
Any Update here @FrederikAFS

**Comment by FrederikAFS** [comment]
Sorry there is sadly no answer from Amazon yet. I will close this for now and maybe get back to you once i know more.
