### ISSUE TITLE
Sample code is wrong

### ISSUE THREAD

**Issue by GuybrushX** [abuzuhri/Amazon-SP-API-CSharp#27]
Hi,

This line from the README.md isn't working since the method doesn't exist:
var orders= amazonConnection.Orders.ListOrders();

I also didn't find a replacement - only getting orders with supplying filter criterias as your next example below that.

My suggestion:
Probably just remove it since it's outdated, isn't it?

**Comment by wheelersf** [comment]
Sample code works perfectly.  I have a basic application pulling orders/order/address/order_lines using the sample code provide.  If the current operation calls for a filter parameter, use a filter parameter.

**Comment by abuzuhri** [comment]
remove this line as its out dated sample 
var orders= amazonConnection.Orders.ListOrders();
