### ISSUE TITLE
Belgium

### ISSUE THREAD

**Issue by Tajanos** [abuzuhri/Amazon-SP-API-CSharp#275]
Please add BE:

https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html

**Comment by abuzuhri** [comment]
Please check NuGet v1.4.17

**Comment by Tajanos** [comment]
It was added to the class but I don't see it here:

        public static MarketPlace GetMarketPlaceByID(string id)
        {
            return new List<MarketPlace>
            {
                US, Canada, Mexico, Brazil, Spain, UnitedKingdom, France, Netherlands, Germany, Italy,
                Sweden, Egypt, Poland, Turkey, UnitedArabEmirates, India, SaudiArabia, Singapore, Australia, Japan
            }.FirstOrDefault((MarketPlace a) => a.ID == id);
        }

        public static MarketPlace GetMarketplaceByCountryCode(string countryCode)
        {
            return new List<MarketPlace>
            {
                US, Canada, Mexico, Brazil, Spain, UnitedKingdom, France, Netherlands, Germany, Italy,
                Sweden, Egypt, Poland, Turkey, UnitedArabEmirates, India, SaudiArabia, Singapore, Australia, Japan
            }.FirstOrDefault((MarketPlace a) => a.Country.Code == countryCode);
        }

**Comment by abuzuhri** [comment]
@RenzoF can you fix this

**Comment by RenzoF** [comment]
> @RenzoF can you fix this

Can do,  should we have a static list so the all the methods can be dynamic and this doesn't happen again? eg
`  public static List<MarketPlace> MarketPlaces { get { return new List<MarketPlace>() {
         new MarketPlace("ATVPDKIKX0DER", Region.NorthAmerica, Country.US),
         new MarketPlace("A2EUQ1WTGCTBG2", Region.NorthAmerica, Country.CA),
         //etc            }; }`
