### ISSUE TITLE
CreateScheduledPackageAsync is using the wrong API endpoint

### ISSUE THREAD

**Issue by mrkevinhsiao** [abuzuhri/Amazon-SP-API-CSharp#279]
It is trying to post to the timeslot endpoint /easyShip/2022-03-23/timeSlot where it should be posting to **/easyShip/2022-03-23/package**

![tmp_98f21714-4c11-4a15-a453-8cf03b7f8f88.png](https://user-images.githubusercontent.com/3969940/184282470-ec2325f1-9420-414e-a9be-fdd66981f5a6.png)

**Comment by abuzuhri** [comment]
check v1.4.19
