### ISSUE TITLE
error when getting inbound shipments, shipment status enum not good

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#282]
@abuzuhri 
it happans with the latest version 1.14.21 the statuses get passes in as INTRANSIT, not the string value of IN_TRANSIT

**Comment by abuzuhri** [comment]
Please double check now and let me know if that fix it

**Comment by nafberger** [comment]
@abuzuhri  i will check please make same fix for CHECKED_IN its now CHECKEDIN

big thanks

i will test both errors later

**Comment by nafberger** [comment]
push please to nuget both changes and i will confirm that it is fixed
