### ISSUE TITLE
error when gettig fba shipments when box content source is 2D_Barcode

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#283]
Newtonsoft.Json.JsonSerializationException: Error converting value "2D_BARCODE" to type 'System.Nullable`1[FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.BoxContentsSource]'. Path 'payload.ShipmentData[16].BoxContentsSource', line 601, position 62.
 ---> System.ArgumentException: Requested value '2D_BARCODE' was not found.

**Comment by abuzuhri** [comment]
Please double check now and let me know if that fix it
