### ISSUE TITLE
CreateInboundShipmentPlan isn't handling item condition correctly

### ISSUE THREAD

**Issue by gambit823** [abuzuhri/Amazon-SP-API-CSharp#284]
When creating an inbound shipment plan if you set the item condition to NewItem you get the following error:
`
Amazon Api didn't respond with Okay, see exception for more details{
      "errors": [
        {
         "message": "Invalid request body: [object has missing required properties ([\"Condition\"])]",
         "code": "InvalidInput"
        }
      ]
    }
`

In this scenario, it isn't sending the default enumeration value but Amazon requires it.

If you set item condition to NewWithWarranty you get this error:
`
    Amazon Api didn't respond with Okay, see exception for more details{
      "errors": [
        {
         "message": "Invalid request body: [instance value (1) not found in enum (possible values: [\"NewItem\",\"NewWithWarranty\",\"NewOEM\",\"NewOpenBox\",\"UsedLikeNew\",\"UsedVeryGood\",\"UsedGood\",\"UsedAcceptable\",\"UsedPoor\",\"UsedRefurbished\",\"CollectibleLikeNew\",\"CollectibleVeryGood\",\"CollectibleGood\",\"CollectibleAcceptable\",\"CollectiblePoor\",\"RefurbishedWithWarranty\",\"Refurbished\",\"Club\"]), instance type (integer) does not match any allowed primitive type (allowed: [\"string\"]), format attribute \"int32\" not supported]",
         "code": "InvalidInput"
        }
      ]
    }
`

In this scenario, it isn't translating from the enum integer value to the string value.

**Comment by abuzuhri** [comment]
can you share the code you are used

**Comment by RenzoF** [comment]
I have just seen this problem as well and just to add a note, in my case the issue here is that the body is being serialized using camelCase and amazon is expecting PascalCase, to test a workaround I have used a custom resolver in the RequestService.cs file and it works.
Just not sure if here the serializer should be respecting the DataMember attribute or what would be the right way to fix this without breaking anything else?

**Comment by abuzuhri** [comment]
its will be helpful if you debug and get result JSON because I cant produce same error

**Comment by gambit823** [comment]
> its will be helpful if you debug and get result JSON because I cant produce same error

The result JSON was in the original post, which I've included below with the formatting cleaned up a bit. Is this what you need or something else?

When creating an inbound shipment plan if you set the item condition to NewItem you get the following error:
    Amazon Api didn't respond with Okay, see exception for more details{
      "errors": [
        {
         "message": "Invalid request body: [object has missing required properties ([\"Condition\"])]",
         "code": "InvalidInput"
        }
      ]
    }

In this scenario, it isn't sending the default enumeration value but Amazon requires it.

If you set item condition to NewWithWarranty you get this error:
    Amazon Api didn't respond with Okay, see exception for more details{
      "errors": [
        {
         "message": "Invalid request body: [instance value (1) not found in enum (possible values: [\"NewItem\",\"NewWithWarranty\",\"NewOEM\",\"NewOpenBox\",\"UsedLikeNew\",\"UsedVeryGood\",\"UsedGood\",\"UsedAcceptable\",\"UsedPoor\",\"UsedRefurbished\",\"CollectibleLikeNew\",\"CollectibleVeryGood\",\"CollectibleGood\",\"CollectibleAcceptable\",\"CollectiblePoor\",\"RefurbishedWithWarranty\",\"Refurbished\",\"Club\"]), instance type (integer) does not match any allowed primitive type (allowed: [\"string\"]), format attribute \"int32\" not supported]",
         "code": "InvalidInput"
        }
      ]
    }

In this scenario, it isn't translating from the enum integer value to the string value.

**Comment by abuzuhri** [comment]
@gambit823 

please check nuget v1.4.25 and let me know if that solve the problem

**Comment by gambit823** [comment]
with item.Condition = AmazonSpApiSDK.Models.FulfillmentInbound.Condition.NewWithWarranty I am now getting:
Amazon Api didn't respond with Okay, see exception for more details[{"code":"InvalidInput","message":"Could not match input arguments"}]

With item.Condition = AmazonSpApiSDK.Models.FulfillmentInbound.Condition.NewItem I am getting:
Amazon Api didn't respond with Okay, see exception for more details{
      "errors": [
        {
         "message": "Invalid request body: [object has missing required properties ([\"Condition\"])]",
         "code": "InvalidInput"
        }
      ]
    }

**Comment by shashi-attri** [comment]
> its will be helpful if you debug and get result JSON because I cant produce same error

I'm getting same error, seems like amazon is returning response payload (I traced it through HTTP Debugger) but something is not right with the following code,

  protected void ParseResponse(IRestResponse response)
        {
            if (response.StatusCode == HttpStatusCode.OK || response.StatusCode == HttpStatusCode.Accepted || response.StatusCode == HttpStatusCode.Created)
                return;
            else if (response.StatusCode == HttpStatusCode.NotFound)
            {
                throw new AmazonNotFoundException("Resource that you are looking for is not found", response);
            }
            else
            {
                Console.WriteLine("Amazon Api didn't respond with Okay, see exception for more details" + response.Content);

                var errorResponse = response.Content.ConvertToErrorResponse();
                if (errorResponse != null)
                {
                    var error = errorResponse.Errors.FirstOrDefault();

                    switch (error.Code)
                    {
                        case "Unauthorized":
                            throw new AmazonUnauthorizedException(error.Message, response);
                        case "InvalidSignature":
                            throw new AmazonInvalidSignatureException(error.Message, response);
                        case "InvalidInput":
                            throw new AmazonInvalidInputException(error.Message, response);
                        case "QuotaExceeded":
                            throw new AmazonQuotaExceededException(error.Message, response);
                    }

                }
            }

            throw new AmazonException("Amazon Api didn't respond with Okay, see exception for more details", response);
        }

**Comment by gambit823** [comment]
This is giving me fits. Any idea when we'll have a fix? Anything I can do to assist?

**Comment by RenzoF** [comment]
@gambit823 can you add a breakpoint in requestservice.cs addjsonbody and have a look to see how the json is getting serialized? If you can post it here to double check.

**Comment by gambit823** [comment]
> @gambit823 can you add a breakpoint in requestservice.cs addjsonbody and have a look to see how the json is getting serialized? If you can post it here to double check.

with item.Condition = AmazonSpApiSDK.Models.FulfillmentInbound.Condition.NewItem it serializes:
"{\"LabelPrepPreference\":\"SELLER_LABEL\",\"ShipFromAddress\":{\"Name\":\"Name\",\"AddressLine1\":\"123 any st\",\"AddressLine2\":\"AddressLine2\",\"City\":\"Ann Arbor\",\"StateOrProvinceCode\":\"MI\",\"CountryCode\":\"US\",\"PostalCode\":\"48188\"},\"ShipToCountryCode\":\"ShipToCountryCode\",\"ShipToCountrySubdivisionCode\":\"ShipToCountrySubdivisionCode\",\"InboundShipmentPlanRequestItems\":[{\"SellerSKU\":\"SellerSKU\",\"ASIN\":\"ASIN\",\"Quantity\":1,\"QuantityInCase\":1,\"PrepDetailsList\":[{\"PrepInstruction\":\"Polybagging\",\"PrepOwner\":\"AMAZON\"}]}]}"

and Amazon returs:
{
      "errors": [
        {
         "message": "Invalid request body: [object has missing required properties ([\"Condition\"])]",
         "code": "InvalidInput"
        }
      ]
    }

**Comment by abuzuhri** [comment]
> > @gambit823 can you add a breakpoint in requestservice.cs addjsonbody and have a look to see how the json is getting serialized? If you can post it here to double check.
> 
> with item.Condition = AmazonSpApiSDK.Models.FulfillmentInbound.Condition.NewItem it serializes: "{"LabelPrepPreference":"SELLER_LABEL","ShipFromAddress":{"Name":"Name","AddressLine1":"123 any st","AddressLine2":"AddressLine2","City":"Ann Arbor","StateOrProvinceCode":"MI","CountryCode":"US","PostalCode":"48188"},"ShipToCountryCode":"ShipToCountryCode","ShipToCountrySubdivisionCode":"ShipToCountrySubdivisionCode","InboundShipmentPlanRequestItems":[{"SellerSKU":"SellerSKU","ASIN":"ASIN","Quantity":1,"QuantityInCase":1,"PrepDetailsList":[{"PrepInstruction":"Polybagging","PrepOwner":"AMAZON"}]}]}"
> 
> and Amazon returns: { "errors": [ { "message": "Invalid request body: [object has missing required properties (["Condition"])]", "code": "InvalidInput" } ] }

Can you share c# code for sample i will test from my side

**Comment by RenzoF** [comment]
@abuzuhri  it looks like the JsonSerializer doesn't serialize the enum with position 0 if the class has a DataContract decoration.
to recreate create a console app and try this 
`Console.WriteLine(JsonConvert.SerializeObject(new InboundShipmentPlanRequestItem() { Condition= Condition.NewItem }));
Console.WriteLine(JsonConvert.SerializeObject(new InboundShipmentPlanRequestItem() { Condition = Condition.CollectibleLikeNew }));`
![image](https://user-images.githubusercontent.com/1706557/190831208-af2a17b4-e2c5-4b01-b6c5-3af9a66de57c.png)

But if you change the position of the NewItem to start in 1 (rather than the default of zero) then it works
![image](https://user-images.githubusercontent.com/1706557/190831275-b718a674-b830-4994-b881-0492092a3eb9.png)


![image](https://user-images.githubusercontent.com/1706557/190831156-41eea5e6-e03c-4b58-a2de-a78130417dc9.png)

**Comment by abuzuhri** [comment]
Hi @RenzoF 

Its very strange , you are true
