### ISSUE TITLE
Could not load type 'RestSharp.IRestClient' from assembly 'RestSharp, Version=108.0.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75

### ISSUE THREAD

**Issue by zinsmeik** [abuzuhri/Amazon-SP-API-CSharp#296]
Hi,

I needed to update the RestSharp Version to 108.01 in my project for getting stuff from a Shopware API and now I get this error when loading the CSharpAmazonSpAPI
RestSharp Version >=107 contains some breaking changes

I tried to do some Assembly Rebinding
```
		<dependentAssembly>
			<assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
			<codeBase version="106.12.0.0" href="RestSharp10612.dll" />
		</dependentAssembly>
```
But it seams VS  does not consider this entry.

How can I fix this?

**Comment by J-W-Chan** [comment]
> Hi,
> 
> I needed to update the RestSharp Version to 108.01 in my project for getting stuff from a Shopware API and now I get this error when loading the CSharpAmazonSpAPI RestSharp Version >=107 contains some breaking changes
> 
> I tried to do some Assembly Rebinding
> 
> ```
> 		<dependentAssembly>
> 			<assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
> 			<codeBase version="106.12.0.0" href="RestSharp10612.dll" />
> 		</dependentAssembly>
> ```
> 
> But it seams VS does not consider this entry.
> 
> How can I fix this?

you can refer to my branch, I haven't merged into main branch yet.
[https://github.com/J-W-Chan/Amazon-SP-API-CSharp/tree/updateToRestsharp108](url)

**Comment by abuzuhri** [comment]
@J-W-Chan  do you test it , its work ? 
I try to do that but there problem when get token

**Comment by zinsmeik** [comment]
Hi,

I rebinding now works with this code
```

		<dependentAssembly>
			<assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
			<bindingRedirect oldVersion="0.0.0.0-106.99.0.0" newVersion="106.12.0.0" />
			<bindingRedirect oldVersion="108.02.0.0" newVersion="108.02.0.0" />
			<codeBase version="106.12.0.0" href="RestSharp10612.dll" />
			<codeBase version="108.02.0.0" href="RestSharp.dll" />
		</dependentAssembly>

```

So this is a workaround.
