### ISSUE TITLE
SearchCatalogItems202204Async sometimes not returning list price value

### ISSUE THREAD

**Issue by Timbot-42** [abuzuhri/Amazon-SP-API-CSharp#297]
Not sure if this is down to the package or the amazon api but many products returned by the method SearchCatalogItems202204Async do not have the actual price. For example I receive the following

```
"list_price": [{
                    "currency": "GBP",
                    "marketplace_id": "A1F83G8C2ARO7P"
                }
            ]
```

When I check the amazon.co.uk website there is indeed a list price (the product is not unavailable). Also the method GetCompetitivePricingAsync is returning price values for the same ASINs. I am using this method as a workaround for now to fill the missing prices. 

Is this a bug?

Thanks
Tim

**Comment by abuzuhri** [comment]
hi @Timbot-42 

If JSON came from AMAZON then you need to open case there

**Comment by Timbot-42** [comment]
Thanks @abuzuhri I will double check in postman if its the same in there and report back. My JSON was from this repo, which is really helpful btw, thank you!

**Comment by abuzuhri** [comment]
this repo also get JSON from amazon its not generated , please double check and let know if its different in postman

**Comment by Timbot-42** [comment]
Can confirm same behaviour in postman, have opened a ticket with Amazon support. Thanks.

**Comment by abuzuhri** [comment]
Please let us know the answer

**Comment by Timbot-42** [comment]
Ok so support got back to me and confirmed the reason the price is not available is because the creds I was calling with did not have that ASIN with an active listing on the seller account. So you need to actually have the listing in order to check the price. To be honest I have found this to be 50/50 correct as a lot are still returning the price anyway.
