### ISSUE TITLE
please create contruct feed code for POST_FBA_INBOUND_CARTON_CONTENTS

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#299]
its very needed for the fba inbound code

**Comment by abuzuhri** [comment]
@nafberger 

Do you have sample XML ?

**Comment by nafberger** [comment]
here is a reference. for a start, but I will get u a full example. thanks.

https://docs.developer.amazonservices.com/en_US/feeds/Feeds_FeedType.html#FeedType_Enumeration__ProductInventoryFeeds

**Comment by nafberger** [comment]
lets say I have already code on how to make the xml, how do i submit it using your library?

**Comment by nafberger** [comment]
xml example
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Header>
    <DocumentVersion>1.01</DocumentVersion>
    <MerchantIdentifier>AXQ2TEJF79KT5</MerchantIdentifier>
  </Header>
  <MessageType>CartonContentsRequest</MessageType>
  <Message>
    <MessageID>1</MessageID>
    <CartonContentsRequest>
      <ShipmentId>FBA16T0N7YC2</ShipmentId>
      <NumCartons>4</NumCartons>
      <Carton>
        <CartonId>1</CartonId>
        <Item>
          <SKU>7004</SKU>
          <QuantityShipped>5</QuantityShipped>
          <QuantityInCase>5</QuantityInCase>
        </Item>
        <Item>
          <SKU>4051</SKU>
          <QuantityShipped>10</QuantityShipped>
          <QuantityInCase>10</QuantityInCase>
        </Item>
        <Item>
          <SKU>6023</SKU>
          <QuantityShipped>10</QuantityShipped>
          <QuantityInCase>10</QuantityInCase>
        </Item>
      </Carton>
      <Carton>
        <CartonId>2</CartonId>
        <Item>
          <SKU>7004</SKU>
          <QuantityShipped>5</QuantityShipped>
          <QuantityInCase>5</QuantityInCase>
        </Item>
        <Item>
          <SKU>4051</SKU>
          <QuantityShipped>10</QuantityShipped>
          <QuantityInCase>10</QuantityInCase>
        </Item>
      </Carton>
      <Carton>
        <CartonId>3</CartonId>
        <Item>
          <SKU>4062</SKU>
          <QuantityShipped>40</QuantityShipped>
          <QuantityInCase>40</QuantityInCase>
        </Item>
      </Carton>
      <Carton>
        <CartonId>4</CartonId>
        <Item>
          <SKU>6023</SKU>
          <QuantityShipped>30</QuantityShipped>
          <QuantityInCase>30</QuantityInCase>
        </Item>
      </Carton>
    </CartonContentsRequest>
  </Message>
</AmazonEnvelope>

**Comment by nafberger** [comment]
xml example 
[xml example.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/9455278/xml.example.txt)

**Comment by nafberger** [comment]
[xml example.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/9455280/xml.example.txt)

**Comment by abuzuhri** [comment]
> lets say I have already code on how to make the xml, how do i submit it using your library?

You can do that using fork then submit pull request, read about that it's very easy
