### ISSUE TITLE
Class of ItemSummaryByMarketplace lock of the attribute of websiteDisplayGroupName

### ISSUE THREAD

**Issue by Kofslime** [abuzuhri/Amazon-SP-API-CSharp#300]
The location of the package is FikaAmazonAPI.AmazonSpApiSDK.Models.CatalogItems.V20220401,the name of class is ItemSummaryByMarketplace.The websiteDisplayGroupName attribute is available on the official documentation,but it's not in the package.

**Comment by abuzuhri** [comment]
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference

**Comment by Kofslime** [comment]
Yes,you are right.In this website,the class of ItemSummaryByMarketplace have arrtibute of websiteDisplayGroupName,but it doesn't exist in the code.Could you add it ?
