### ISSUE TITLE
ReportManager GetProducts missing data

### ISSUE THREAD

**Issue by 3aum** [abuzuhri/Amazon-SP-API-CSharp#304]
First of all thank you very much for the work you have done here.
I have problems with the following data fields when using GetProducts:
-ImageUrl (Missing for all my products)
- FulfillmentChannel (Missing for all my products)
- ItemName (Is not decoded correctly my string does not contain any german special characters only a lot of '?')
- Quantity and PendingQuantity (only contains correct data for FBM listings. For FBA listings i am getting "-2147483648" as values)

I should have all the premissions needed:
![image](https://user-images.githubusercontent.com/98931398/188018620-1afa597f-5c97-47ac-8f3d-72113e396b4c.png)

Can anyone help me out on this please?

**Comment by abuzuhri** [comment]
this not problem in ReportManager its amazon not return this data , you can call get report and check the report came from amzon
