### ISSUE TITLE
GetProducts "Amazon Api didn't respond with Okay, see exception for more details"

### ISSUE THREAD

**Issue by mjw2022** [abuzuhri/Amazon-SP-API-CSharp#309]
Hi, thanks for adding MerchantShippingGroup field to the GetProducts()
After upgrading to ver 1.4.25 I get an error with GetProducts

"Amazon Api didn't respond with Okay, see exception for more details"

"Enumeration yielded no results"

If I revert back to  1.4.23 it works OK.

Thanks

Mark

**Comment by gambit823** [comment]
I am having the same issue with Orders.GetOrderItems. I've tracked it down to the fix for issue #287. That fix added the following line to Source/FikaAmazonAPI/Services/RequestService.cs:
RequestClient.ThrowOnAnyError = true;

If you remove that line everything works again.

**Comment by gambit823** [comment]
FYI this is a duplicate of #308.

**Comment by abuzuhri** [comment]
Please check v1.4.26

**Comment by mjw2022** [comment]
v1.4.26 works well for me. Thanks
