### ISSUE TITLE
FulfilmentInbound.PutTransportDetails returning error

### ISSUE THREAD

**Issue by shashi-attri** [abuzuhri/Amazon-SP-API-CSharp#310]
Details: The payload being sent to API is returning error, though everything is being passed but seems like JSONConverter missing some values ShipmentType and Unit of Weight.

Error Details:

2 validation errors detected: Value '' at 'transportDetails.partneredSmallParcelData.packageList.1.member.weight.unit' failed to satisfy constraint: Member must satisfy enum value set: [pounds, kilograms]; Value '' at 'shipmentType' failed to satisfy constraint: Member must satisfy enum value set: [LTL, SP]

**Comment by shashi-attri** [comment]
@abuzuhri  do we have any updates on this one, from my side I will try out with the latest released version. I'II look forward to hear from you.

**Comment by MasterTyrr** [comment]
I am getting an error with my request on PutTransportDetails, though I am not sure this is the same as I am not using partnered shipments. 

Error: "AmazonInvalidInputException: 1 validation error detected: Value '{}' at 'transportDetails.nonPartneredLtlData.proNumber' failed to satisfy constraint: Member must have length greater than or equal to 7". 
My code:
`putTransportDetailsRequest.ShipmentType = ShipmentType.LTL;
                var ltlInputData = new NonPartneredLtlDataInput();
                ProNumber proNum = new ProNumber();
                proNum.Equals(coTrackNum);

                ltlInputData.CarrierName = coMethod;
                ltlInputData.ProNumber = proNum;
                transportDetails.NonPartneredLtlData = ltlInputData;

                putTransportDetailsRequest.TransportDetails = transportDetails;`

**Comment by abuzuhri** [comment]
> @abuzuhri do we have any updates on this one, from my side I will try out with the latest released version. I'II look forward to hear from you.

I can't see any PULL REQUEST from you

**Comment by shashi-attri** [comment]
> > @abuzuhri do we have any updates on this one, from my side I will try out with the latest released version. I'II look forward to hear from you.
> 
> I can't see any PULL REQUEST from you

I've downloaded and made a fix now it works for me. I will pull down changes and push to the branch.

**Comment by abuzuhri** [comment]
@shashi-attri thanks too much

**Comment by shashi-attri** [comment]
> o much

I just pulled down and made the changes, I can't push. I think I do not have permissions.

**Comment by shashi-attri** [comment]
@abuzuhri  - This is done and pushed, could you please release and let me know the latest package # . I'II look forward to hear from you soon.

**Comment by abuzuhri** [comment]
@shashi-attri do you found how to do this ?

**Comment by shashi-attri** [comment]
@abuzuhri  - Just created a pull request, please let me know if you need anything.

**Comment by abuzuhri** [comment]
check v1.4.30

**Comment by shashi-attri** [comment]
Awesome, Thank you!
