### ISSUE TITLE
Can I use AddProductMessage method to post amazon seller catalog feed on amazon using FikaAmazonAPi

### ISSUE THREAD

**Issue by asifiq2000** [abuzuhri/Amazon-SP-API-CSharp#317]
ConstructFeedService createDocument = new ConstructFeedService(SellerID, "1.02");
var list = new List<ProductMessage>();
createDocument.AddProductMessage(list);
var xml = createDocument.GetXML();
var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_PRODUCT_DATA);

Hi
I am using the FikaAmazonApi to post inventory and price on amazon successfully
now I also have to post the catalog feed on amazon, so my query is, can I post the catalog feed
using the above mentioned methods, if I construct the productfeed xml and post through the
above method as posted inventory or price successfully.
please confirm awaiting your reply.

**Comment by asifiq2000** [comment]
> var list = new List(); createDocument.AddProductMessage(list); var xml = createDocument.GetXML(); var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_PRODUCT_DATA);
> 
> Hi

I am using the FikaAmazonApi to post inventory and price on amazon successfully
now I also have to post the catalog feed on amazon, so my query is, can I post the catalog feed 
using the above mentioned methods, if I construct the productfeed xml and post through the 
above method as posted inventory or price successfully.
please confirm awaiting for your reply.

**Comment by abuzuhri** [comment]
Hello @asifiq2000 

AddProductMessage  right now only do mapping for existing ASIN

**Comment by abuzuhri** [comment]
Here sample 

```Csharp
            ConstructFeedService createDocument = new ConstructFeedService("A3J37AJU4O9RHK", "1.02");

            var list = new List<ProductMessage>();
            list.Add(new ProductMessage()
            {
                SKU = "8201031206122...",
                StandardProductID = new ConstructFeed.Messages.StandardProductID()
                {
                    Type = "ASIN",
                    Value = "B08CDYB2DC"
                }
            });
            createDocument.AddProductMessage(list, OperationType.Update);
            var xml = createDocument.GetXML();

            var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_PRODUCT_DATA);
```

**Comment by asifiq2000** [comment]
Yes I got it before your reply but thank you so much @abuzuhri for the help,

Actually I am looking for the catalog feed posting using UPC wherein I do not need to post all catalog fields
however I would post only 3 to 4 fields including UPC, means if that UPC matches with the listed amazon product
then it will use the same details and list the product with my SKU no.

Please help me and guide me to achieve this goal

**Comment by asifiq2000** [comment]
> Hello @asifiq2000
> 
> AddProductMessage right now only do mapping for existing ASIN

Hi @abuzuhri 
Thanks for your reply, I have some confusion with your answer, please clear it.

1. You mean the product I want to create on amazon in my seller account that product must be created 
    or available for any other seller's account before?

2. OR you want to say that I can only update my seller account's existing product using the AddProductMessage method and cannot add/create it?

3. If the point no 1. is correct then, what if I want to create a new product on amazon that was not created or listed  
    before on amazon by any seller.

4. If the point no 2. is correct then what is the other way to create or add any product in my amazon seller account.

Thanks for your helps
