### ISSUE TITLE
Country domain of Japan is error

### ISSUE THREAD

**Issue by skl-hyf** [abuzuhri/Amazon-SP-API-CSharp#32]
`        public static Country JP { get { return new Country("JP", "Japan", "jp", "https://sellercentral.amazon.co.jp", "https://vendorcentral.amazon.co.jp"); } }
`

domain of Japan is co.jp ，not jp.
Please modify it.
Thank you!

**Comment by skl-hyf** [comment]
Hi,I pushed a pull request to fix it. Please merge it.
Thanks!

**Comment by abuzuhri** [comment]
Thanks for fix
