### ISSUE TITLE
Notifications body wrong 

### ISSUE THREAD

**Issue by RenzoF** [abuzuhri/Amazon-SP-API-CSharp#324]
Is anyone using the notifications API? The documentation (and there for this library) has the json properties incorrect and it doesn't deserialize.
the notification body sent by amazon is using CamelCase but the documentation [here](https://github.com/amzn/selling-partner-api-models/blob/main/schemas/notifications/FBAOutboundShipmentStatusNotification.json) is using pascalCase
Docs
![image](https://user-images.githubusercontent.com/1706557/190925925-48f0b0c9-5caa-4e33-a965-d78b45a02588.png)

Actual
![image](https://user-images.githubusercontent.com/1706557/190925949-28759473-0aea-4c12-af0e-bf78caff2050.png)
Any ideas? I could submit a pull request if everyone sees the same and maybe open a case with Amazon to update the documentation. (unless I am missing something?)

**Comment by abuzuhri** [comment]
@RenzoF can you submit PULL REQUEST to fix this

**Comment by RenzoF** [comment]
@abuzuhri  sure no problem, I wasn't it was something wrong with my config, I'll submit a pull later
