### ISSUE TITLE
Questions about getListingOffers

### ISSUE THREAD

**Issue by shooter-13** [abuzuhri/Amazon-SP-API-CSharp#326]
Hello, I have two questions that I hope you can answer.Thank you.

1. The default value of the “ItemCondition” parameter of the GetLowestOfferListingsForSKU method in MWS is "Any", but the current SP-API does not have this default value. What should I do if I want to get the same data as the incoming "Any"?
2. There is no "ExcludeMe" parameter in SP-API. What should I do if I want to query the data that does not contain my own goods through SKU?

**Comment by RenzoF** [comment]
Hi,

1.  I don't think you can do it, might be worth asking on the amazon repo instead of here.
2. I am not sure if there is a way to do it, your only option might just to filter them out of the response using the seller id

**Comment by abuzuhri** [comment]
Hi @shooter-13 

I agree with @RenzoF this the best answer
