### ISSUE TITLE
Getting issue in creating report type "GET_FBA_MYI_ALL_INVENTORY_DATA"

### ISSUE THREAD

**Issue by asifiq2000** [abuzuhri/Amazon-SP-API-CSharp#328]
Hi @abuzuhri 

I need your help

I have to create GET_FBA_MYI_ALL_INVENTORY_DATA report then download it for our application
I have also checked in FikaApi, method for this report is not available there so I am trying to POST 
a create report request for the same then I will have to GET the report as well using rest request.

In SP-API doc I only found below detail whereas missing authorization details:

create report:
POST https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports
{
  "reportType": "GET_FBA_MYI_ALL_INVENTORY_DATA",
  "dataStartTime": "2022-09-08T20:11:24.000Z",
  "marketplaceIds": [
   "ATVPDKIKX0DER"
  ]
}

retrieve report:
GET https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/documents/DOC-b8b0-4226-b4b9-0ee058ea5760

I wrote the below mentioned code to create a report request:

restClient = new RestClient("https://sellingpartnerapi-na.amazon.com");
IRestRequest restRequest = new RestRequest("/reports/2022-06-30/reports", Method.POST);
restRequest.AddHeader("x-amz-access-token", str_token_from_your_secure_db);

string strInventoryList = "{\"reportType\":\"GET_FBA_MYI_ALL_INVENTORY_DATA\",\"dataStartTime\":\"2022-09-08T20:11:24.000Z\",\"marketplaceIds\":[\"ATVPDKIKX0DER\"]}";

restRequest.AddParameter("application/json", strInventoryList, ParameterType.RequestBody);
var request = signatureHelper.SignRequest(restRequest, restClient, content_form_urlencoded);
var result = restClient.Execute(request);

Please correct my mistakes, and guide me how to create and get this report.

**Comment by RenzoF** [comment]
Have a look at the examples here 
https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI.SampleCode/ReportsSample.cs
