### ISSUE TITLE
Is there any way I can get the X-AMZn-requestid for each request?

### ISSUE THREAD

**Issue by Kofslime** [abuzuhri/Amazon-SP-API-CSharp#338]
Every time I request an interface, I can get the content of the request. Now I want the request ID in the request header for each request. How should I do?

**Comment by tank104** [comment]
Did you manage to sort this?  or just found it wasn't supported?

**Comment by TechyChap** [comment]
I second this and additionally request "Date". The reason for asking is that when you submit a case to Amazon for support the request ID and the timestamp are required fields.
Currently we have to manually submit the request via Postman.

**Comment by TechyChap** [comment]
Been looking at the code again. Looks like we can grab these values from LastResponseHeader

**Comment by abuzuhri** [comment]
Yes all header value you can get from last request by call **(LastResponseHeader)**
