### ISSUE TITLE
Getting Access Error in PII information for orders ("buyerInfo", "shippingAddress")

### ISSUE THREAD

**Issue by asifiq2000** [abuzuhri/Amazon-SP-API-CSharp#340]
Hi @abuzuhri 

I am using below Fika api codes to get the orders from amazon which is running successfully 

Successful Get Order Code:
AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
        {
            AccessKey = "XXXXXXXXXXXXXXXXXXXX",
            SecretKey = "XXXXXXXXXXXXXXXXXXXX",
            RoleArn = "XXXXXXXXXXXXXXXXXXXX",
            ClientId = "XXXXXXXXXXXXXXXXXXXX",
            ClientSecret = "XXXXXXXXXXXXXXXXXXXX",
            RefreshToken = "XXXXXXXXXXXXXXXXXXXX",  
            MarketPlace = MarketPlace.GetMarketPlaceByID("ATVPDKIKX0DER"),
        });
        amzonOrders objOrders = new amzonOrders();
        ParameterOrderList serachOrderList = new ParameterOrderList();
        serachOrderList.CreatedAfter = DateTime.UtcNow.AddHours(mHours);
        serachOrderList.OrderStatuses = new List<OrderStatuses>();
        serachOrderList.OrderStatuses.Add(OrderStatuses.Unshipped);
        var orders = amazonConnection.Orders.GetOrders(serachOrderList);

However when I try to get the orders along with PII information with the below codes then getting Access error
Error: "Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]"

AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
{
    AccessKey = "XXXXXXXXXXXXXXXXXXXX",
    SecretKey = "XXXXXXXXXXXXXXXXXXXX",
    RoleArn = "XXXXXXXXXXXXXXXXXXXX",
    ClientId = "XXXXXXXXXXXXXXXXXXXX",
    ClientSecret = "XXXXXXXXXXXXXXXXXXXX",
    RefreshToken = "XXXXXXXXXXXXXXXXXXXX",  
    MarketPlace = MarketPlace.GetMarketPlaceByID("ATVPDKIKX0DER"),
});

var parameterOrderList = new ParameterOrderList
{
    CreatedAfter = DateTime.UtcNow.AddHours(-24),
    OrderStatuses = new List<OrderStatuses> { OrderStatuses.Unshipped },
    MarketplaceIds = new List<string> { MarketPlace.US.ID },
    IsNeedRestrictedDataToken = true,
    RestrictedDataTokenRequest = new CreateRestrictedDataTokenRequest
    {
        restrictedResources = new List<RestrictedResource>
        {
            new RestrictedResource
            {
                method = Method.GET.ToString(),
                path = ApiUrls.OrdersApiUrls.Orders,
                dataElements = new List<string> { "buyerInfo", "shippingAddress" }
            }
        }
    }
};
var orders = amazonConnection.Orders.GetOrders(parameterOrderList);

When I had created support ticket on amazon with the respective request detail as follows:

Rest Api Get Order Request Detail:
----------------------------------
{host=sellingpartnerapi-na.amazon.com}
{={"restrictedResources":[{"method":"GET","path":"/orders/v0/orders","dataElements":["buyerInfo","shippingAddress"]}],"targetApplication":null}}
{x-amz-access-token=Atza|IwEBILWdomQXXXXXXXXXXXX}
{x-amz-security token=FwoGZXIvYXdzXXXXXXXXXXXXXXX}
{X-Amz-Date=20220927T004535Z}
{Authorization=AWS4-HMAC-SHA256 Credential=ASIARCXXXXXXX/20220927/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=XXXXXXXXXXXXXXXXXXXXX}

then Amazon support are replied as follows:
![image](https://user-images.githubusercontent.com/40463094/192905057-27f5fe29-f29d-40d1-bd6b-c4af86f0227f.png)

Please suggest how can I answer them for this issue since I am using Fika api

**Comment by J-W-Chan** [comment]
> 

make sure you app has PII Role

**Comment by RenzoF** [comment]
The answer from Amazon is surprisingly clear, you either don't request PII data or add the role

**Comment by abuzuhri** [comment]
@RenzoF  and @J-W-Chan 

Thanks for true answer
