### ISSUE TITLE
GetMessagingActionsForOrder Error:An item with the same key has already been added. Key: marketplaceIds

### ISSUE THREAD

**Issue by valle-gp** [abuzuhri/Amazon-SP-API-CSharp#342]
I am trying to implement message handling, and I have tried using GetMessagingActionsForOrder  ( var red = amazonConnection.Messaging.GetMessagingActionsForOrder("XXX-7123008-XXXXXX"); ) but it always gives error "**An item with the same key has already been added. Key: marketplaceIds**'"

**Comment by abuzuhri** [comment]
@RenzoF thanks a lot for your fix
