### ISSUE TITLE
InternalFailure when calling GetShipmentAsync

### ISSUE THREAD

**Issue by ProNotion** [abuzuhri/Amazon-SP-API-CSharp#343]
I am having no success trying to request shipment details from the API. My request look as follows:

```
await _amazonConnection.Shipping.GetShipmentAsync(shipmentId, new ParameterBasedPII()
                {
                    IsNeedRestrictedDataToken = false
                });
```

I don't need or want any PII but my requests always result in the following response from the AP:

```
{
	"errors": [{
		"code": "InternalFailure",
		"message": "We encountered an internal error. Please try again.",
		"details": ""
	}]
}
```

I am using the UK marketplace in case that is of any relevance.

**Comment by RenzoF** [comment]
Hi @ProNotion ,
Are you trying to get an amazon Shipment or an FBA Inbound shipment?
is easy to get confused.

**Comment by ProNotion** [comment]
> Hi @ProNotion , Are you trying to get an amazon Shipment or an FBA Inbound shipment? is easy to get confused.

@RenzoF I am trying to get an FBA Inbound shipment.

**Comment by RenzoF** [comment]
Correct, you are looking for this 
`amazonConnection.FulFillmentInbound.GetShipments(new ParameterGetShipments() { ShipmentIdList = new List<string>() { { "FBA15XXXXX" } }, QueryType = QueryType.SHIPMENT, MarketplaceId = MarketPlace.UnitedKingdom.ID  });`

Been there done that 🤣

**Comment by ProNotion** [comment]
> Correct, you are looking for this `amazonConnection.FulFillmentInbound.GetShipments(new ParameterGetShipments() { ShipmentIdList = new List<string>() { { "FBA15XXXXX" } }, QueryType = QueryType.SHIPMENT, MarketplaceId = MarketPlace.UnitedKingdom.ID });`
> 
> Been there done that 🤣

Thank you - that's removed a significant roadblock in my application 👍
