### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

### ISSUE THREAD

**Issue by jmawebtech** [abuzuhri/Amazon-SP-API-CSharp#347]
Hi,

I am upgrading a site from ASP.NET MVC 5 to ASP.NET CORE 6. My code from ASP.NET MVC works fine, but the code fails with .NET Core 6. The code from both systems is identical. I am sending the same credentials (api keys, access and refresh tokens) and the access token appears correct. I can test my .NET Core app and my MVC 5 app side by side. The MVC app works fine. .NET Core does not.

POST
/tokens/2021-03-01/restrictedDataToken

Host:sellingpartnerapi-na.amazon.com
x-amz-access-token:OMITTED
x-amz-date:20221003T185625Z

host;x-amz-access-token;x-amz-date
601684d6a38784a5a01a758f01c100f21fe40f09121fa1ceaf4b7288b43be221

AWS4-HMAC-SHA256
20221003T185625Z
20221003/us-east-1/execute-api/aws4_request
f11af4b345258a525f84252dea8b310a46c4b8ffb5d59db5dd8e28fd639604f5

ERROR FROM AMAZON

The Canonical String for this request should have been
'POST
/tokens/2021-03-01/restrictedDataToken

host:sellingpartnerapi-na.amazon.com
x-amz-access-token:OMITTED
x-amz-date:20221003T185625Z

host;x-amz-access-token;x-amz-date
601684d6a38784a5a01a758f01c100f21fe40f09121fa1ceaf4b7288b43be221'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20221003T185625Z
20221003/us-east-1/execute-api/aws4_request
347bad17b25bf033be2ceab9daa28aa27a29f86aa64f77c268cebf22985c2d76'
",
     "code": "InvalidSignature"
    }
  ]
}

I think the issue is here:

        /// <summary>
        /// Builds the string for signing using signing date, hashed canonical request and region
        /// </summary>
        /// <param name="signingDate">Signing Date</param>
        /// <param name="hashedCanonicalRequest">Hashed Canonical Request</param>
        /// <param name="region">Region</param>
        /// <returns>String to be used for signing</returns>
        public virtual string BuildStringToSign(DateTime signingDate, string hashedCanonicalRequest, string region)
        {
            string scope = BuildScope(signingDate, region);
            string stringToSign = string.Format(CultureInfo.InvariantCulture, "{0}-{1}\n{2}\n{3}\n{4}",
                Scheme,
                Algorithm,
                signingDate.ToString(ISO8601BasicDateTimeFormat, CultureInfo.InvariantCulture),
                scope,
                hashedCanonicalRequest);

            return stringToSign;
        }

**Comment by RenzoF** [comment]
Hi @jmawebtech 
I am using the library with .Net Core 6 and don't have this issue. 
Is this all in the server maybe some issue with the date of the system? 
What version are you using?

**Comment by jmawebtech** [comment]
I use HTTPClient in mine. The header keys must be lower case:

Notice

Host:sellingpartnerapi-na.amazon.com

vs

host:sellingpartnerapi-na.amazon.com

Host should be lower case.

        public virtual string ExtractCanonicalHeaders(HttpClient client)
        {
            Dictionary<string, string> headers = new Dictionary<string, string>();
            foreach (var header in client.DefaultRequestHeaders)
            {
                headers.Add(header.Key.ToLower(), string.Join("", header.Value));
            }

**Comment by abuzuhri** [comment]
@jmawebtech please check if this change solve the problem ?

**Comment by abuzuhri** [comment]
@jmawebtech can we close this case ?

**Comment by jmawebtech** [comment]
Yes please close it.



________________________________
