### ISSUE TITLE
FulfillmentOutbound.ListAllFulfillmentOrders and FulfillmentOutbound.GetFulfillmentOrder

### ISSUE THREAD

**Issue by ccstest1** [abuzuhri/Amazon-SP-API-CSharp#357]
FulfillmentOutbound.ListAllFulfillmentOrders missing fields:DisplayableOrderDateTime,ReceivedDateTime,StatusUpdatedDateTime
looks like all fields type of Timestamp are missing.

FulfillmentOutbound.GetFulfillmentOrder has the same problem,and FulfillmentOrderItemList,FulfillmentShipmentList are missing too.

**Comment by RenzoF** [comment]
Hi 
Those fields are part of the StatusUpdatedDateTime [FulfillmentOrder.cs](https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI/AmazonSpApiSDK/Models/FulfillmentOutbound/FulfillmentOrder.cs) not the reponses or results.

This FulfillmentOutbound.ListAllFulfillmentOrders  Returns a list which has all the orders with the fields you are looking for under FulfillmentOrderList

**Comment by RenzoF** [comment]
Got it, I got confused with the missing part so I went to check the models :-), what version are you using?
They seem to be working for me
I only have a couple of old orders on this account
![image](https://user-images.githubusercontent.com/1706557/194883946-e811525b-cc7e-428e-9d4e-8fefd8455327.png)
Maybe you are setting a different serializer for newtonsoft somewhere else in your code that might be interfering?

**Comment by ccstest1** [comment]
It's solved by get latest version.
