### ISSUE TITLE
Throtteling in Pricing Call

### ISSUE THREAD

**Issue by OliverZemke2021** [abuzuhri/Amazon-SP-API-CSharp#362]
Hello,

We use version 1.4.22, because we can still use the old call "ListCatalogItems" to get the author information when we search for a book. With the new call, unfortunately, we do not get this information. Is this information no longer sent by Amazon?
Now to the real question, we are optimizing our prices using the "GetItemOffers" call, unfortunately we are getting into throtteling very quickly. If I have seen it correctly, then in the version 1.4.22 but the function "SleepForRateLimit" is included, which should ensure not to come into throtteling, right?

Best Regards
Olli

**Comment by abuzuhri** [comment]
Is this endpoint still working “ ListCatalogItems” ? If yes I can reactivate it with warning only 

for GetItemOffers yes Amazon change the number of request abd we update our library with new number they have new endpoint to get offer as batch try that .

**Comment by OliverZemke2021** [comment]
Yes in the Version 1.4.22 the "ListCatalogItems" is still working. It will be perfect if you will reactivate it with warning.

**Comment by abuzuhri** [comment]
check v1.5.3
