### ISSUE TITLE
how to handle UnsignedIntType in box count of PartneredLtlDataInput

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#369]
hi @abuzuhri 
in your library the box count for PartneredLtlDataInput is a UnsignedIntType 
how do i convert an int to that value and besides, what's the reason, can it be made as a plain int

**Comment by abuzuhri** [comment]
can you give more details here ?

**Comment by nafberger** [comment]
![image](https://user-images.githubusercontent.com/26122027/198908625-b966fd9a-7fa1-49a2-8891-acbb5cda6bd3.png)

**Comment by nafberger** [comment]
I mean how do u assign a value to it, never encountered this int type in c#

**Comment by nafberger** [comment]
@abuzuhri 
waiting for answer on that.

**Comment by nafberger** [comment]
@abuzuhri 
why is this issue closed, its a genuine problem, can u please paste a code snippet on how to provide transport details with LTL partnered and provide a box count

**Comment by nafberger** [comment]
@abuzuhri I think its a bad class generated by some generation code but look it up, its an empty useless class its a bug that needs to be fixed please

**Comment by RenzoF** [comment]
@nafberger I think he closed it because it merged the pull request you sent to fix it, pull  #377
