### ISSUE TITLE
carton item class in construct feed needs ExpirationDate property

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#371]
carton item class in construct feed needs ExpirationDate property

I can add it

how do i make sure it doesn't get serialized when null, this can create trouble

**Comment by nafberger** [comment]
@abuzuhri  please comment

**Comment by nafberger** [comment]
CartonContentsRequest.NumCartons is missing from xml

<?xml version="1.0" encoding="utf-16"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Header>
        <DocumentVersion>1.02</DocumentVersion>
        <MerchantIdentifier>ccccccccccc</MerchantIdentifier>
    </Header>
    <MessageType>CartonContentsRequest</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <OperationType>Update</OperationType>
        <CartonContentsRequest>
            <ShipmentId>FBA16XVBHNNT</ShipmentId>
            <Carton>
                <CartonId>1</CartonId>
                <Item>
                    <SKU>cccccc</SKU>
                    <QuantityShipped>1</QuantityShipped>
                    <QuantityInCase>1</QuantityInCase>
                </Item>
            </Carton>
        </CartonContentsRequest>
    </Message>
</AmazonEnvelope>

**Comment by abuzuhri** [comment]
for **'NumCartons'** please read this 
https://stackoverflow.com/questions/5585364/force-xml-serialization-to-serialize-readonly-property

**Comment by abuzuhri** [comment]
for **'ExpirationDate'** here the solution

```CSHARP

        [XmlElement(ElementName = "ExpirationDate")]
        public Nullable<DateTime> ExpirationDate { get; set; }

        [XmlIgnore]
        public bool ExpirationDateSpecified { get { return ExpirationDate != null; } }

```

**Comment by abuzuhri** [comment]
but i think the format for **ExpirationDate** please double check thar

**Comment by nafberger** [comment]
@abuzuhri  please tell me when latest fixes r on nuget so I can test and close issue. big thanks

**Comment by abuzuhri** [comment]
all in v1.5.8
