### ISSUE TITLE
PrepInstructions Enum

### ISSUE THREAD

**Issue by Paul-J-Barrett** [abuzuhri/Amazon-SP-API-CSharp#381]
We are having to add our custom PrepInstruction.cs Enums to the file. Any one have a better idea on how to handle this issue.

,

        /// <summary>
        /// Enum SuffocationStickering for value: SuffocationStickering
        /// </summary>
        [EnumMember(Value= "SuffocationStickering")]
        SuffocationStickering = 7,

        /// <summary>
        /// Enum SetCreation for value: SetCreation
        /// </summary>
        [EnumMember(Value = "SetCreation")]
        SetCreation = 8

**Comment by abuzuhri** [comment]
Please describe what the issue you face ?

**Comment by RenzoF** [comment]
@Paul-J-Barrett can you point us to the documentation of those values? 
The official model only shows this
![image](https://user-images.githubusercontent.com/1706557/199693241-86c197d1-9afa-4af4-a3fb-09ed4d65f3bd.png)
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-model

**Comment by nafberger** [comment]
Hi all I added these enums because the code that was getting fba shipments was crashing because on fba shipments items amazon return s the prep instructions requires and the response wasn't serializing those properties correctly

**Comment by nafberger** [comment]
so yes its possible that the model is not updated, which is very common. so whats the probelm

**Comment by abuzuhri** [comment]
@Paul-J-Barrett 

The code in last version right now has those enum 

![image](https://user-images.githubusercontent.com/3703300/199829602-862d24fd-5ea7-487e-8551-14357716e73c.png)


Please update to last version and you get it work

**Comment by RenzoF** [comment]
> so yes its possible that the model is not updated, which is very common. so whats the probelm

No one said that there was a problem, the question was to try to find out where the full list was or how did you find which one was missing so that we can update them.

**Comment by nafberger** [comment]
I found out by running the fba shipment items call it returns all the prep
instructions for an item

**Comment by Paul-J-Barrett** [comment]
When we encounter an error on the prep enumerated we just add the animals
ourselves. The comments above were eluminating.

Thanks for the feed back.

I don't work on the FBA fulfilment team so I actually thought the values
might be custom rather than assigned by Amazon.
