### ISSUE TITLE
ShipmentStatusList need new status "READY_TO_SHIP"

### ISSUE THREAD

**Issue by Wildfire2022** [abuzuhri/Amazon-SP-API-CSharp#387]
Hi,
Recently,  I found that the newly created Shipment cannot be requested by FulFillmentInbound.GetShipments method. 
After checking, I found that this ShipmentStatus is missing: READY_TO_SHIP

**Comment by RenzoF** [comment]
It looks like this is a known issue since august in the models provided by amazon, 
https://github.com/amzn/selling-partner-api-models/issues/270#issue-1349823089
I'll update the model now to add the READY_TO_SHIP status
