### ISSUE TITLE
Update Tracking posting throwing error sometimes

### ISSUE THREAD

**Issue by asifiq2000** [abuzuhri/Amazon-SP-API-CSharp#397]
Hi @abuzuhri 

I have implemented the Fika API, using it I am posting the Tracking of the amazon orders 
which is running fine but sometimes its throwing error as well and everytime the same error 
**"We are unable to process the XML feed because one or more items are invalid. Please re-submit the feed."**
getting occurred while there is no issue in the data or the xml feed, 
please find below my used codes and error detail for reference:

Kindly help me if you know the reason, coz this issue put me in trouble our client is on fire for this 
they have loads of orders and their tracking to be updated on daily hourly basis however sometime 
they met with this issue with few order but it is very difficult to manage it got missed and amazon will 
make the account suspended due to delay in update.

Code:
------
list.Add(new OrderFulfillmentMessage()
        {
            AmazonOrderID = mAmazonOrderID,
            FulfillmentDate = DateTime.UtcNow.ToString(),
            FulfillmentData = new FulfillmentData()
            {
                CarrierName = mCarrierName,
                ShippingMethod = mShippingMethod,
                ShipperTrackingNumber = mShipperTrackingNumber
            }
        });
        createDocument.AddOrderFulfillmentMessage(list);
        var xml = createDocument.GetXML();
        string feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_ORDER_FULFILLMENT_DATA);
        var feedOutput = amazonConnection.Feed.GetFeed(feedID);

Error:
------

![image](https://user-images.githubusercontent.com/40463094/200969856-16dc70ef-b767-4c38-b485-cc5652fb5970.png)

**Comment by J-W-Chan** [comment]
> Hi @abuzuhri
> 
> I have implemented the Fika API, using it I am posting the Tracking of the amazon orders which is running fine but sometimes its throwing error as well and everytime the same error "We are unable to process the XML feed because one or more items are invalid. Please re-submit the feed." getting occurred while there is no issue in the data or the xml feed, please find below my used codes and error detail for reference:
> 
> Kindly help me if you know the reason, coz this issue put me in trouble our client is on fire for this they have loads of orders and their tracking to be updated on daily hourly basis however sometime they met with this issue with few order but it is very difficult to manage it got missed and amazon will make the account suspended due to delay in update.
> 
> ## Code:
> list.Add(new OrderFulfillmentMessage() { AmazonOrderID = mAmazonOrderID, FulfillmentDate = DateTime.UtcNow.ToString(), FulfillmentData = new FulfillmentData() { CarrierName = mCarrierName, ShippingMethod = mShippingMethod, ShipperTrackingNumber = mShipperTrackingNumber } }); createDocument.AddOrderFulfillmentMessage(list); var xml = createDocument.GetXML(); string feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_ORDER_FULFILLMENT_DATA); var feedOutput = amazonConnection.Feed.GetFeed(feedID);
> 
> ## Error:
> ![image](https://user-images.githubusercontent.com/40463094/200969856-16dc70ef-b767-4c38-b485-cc5652fb5970.png)

You should provide us the uploaded xml content

**Comment by J-W-Chan** [comment]
You should provide us the uploaded xml content

**Comment by asifiq2000** [comment]
> You should provide us the uploaded xml content

![image](https://user-images.githubusercontent.com/40463094/201433575-759f4a8e-8db5-4a02-94b2-90654c039cbe.png)

**Comment by J-W-Chan** [comment]
you should use datetime toISO-8601 format.
like this:
https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/93755646632ff838f3340dedd5a05916153836b0/Source/FikaAmazonAPI.SampleCode/FeedsSample.cs#L217
