### ISSUE TITLE
There are some problems with CreateReportAndDownloadFileAsync

### ISSUE THREAD

**Issue by Wildfire2022** [abuzuhri/Amazon-SP-API-CSharp#403]
I found two problems using this method CreateReportAndDownloadFileAsync.

1. This method sometimes throw a exception: Collection was modified; enumeration operation may not execute.
2. Sometimes the types of reports requested and downloaded are different.  For example, request “GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA” report. After the download is complete, check that the file is a type “GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA” report.

**Comment by abuzuhri** [comment]
I check this and I confirm that true but this as its come from amazon its not problem from our library

**Comment by abuzuhri** [comment]
@Wildfire2022 please open case in amazon
