### ISSUE TITLE
typo in my latest commit

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#406]
![image](https://user-images.githubusercontent.com/26122027/202295063-ea111dd7-644c-4643-a783-1dd3b947a192.png)

sorry sorry

sorry

can u please fix and push because now its broken.

@abuzuhri

**Comment by nafberger** [comment]
@abuzuhri 
if u push now i can test and make sure it works

**Comment by abuzuhri** [comment]
I SEE THAT AND I FIX IT already in last version

**Comment by abuzuhri** [comment]
Install-Package CSharpAmazonSpAPI -Version 1.5.14

**Comment by nafberger** [comment]
@abuzuhri 
https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/e94996831995ad0fd9b9dba107a73c690787bdf4/Source/FikaAmazonAPI/AmazonSpApiSDK/Models/FulfillmentInbound/CurrencyCode.cs#L45
just looked online on the code, is this ok?

**Comment by nafberger** [comment]
"CAD" is there 2 times

**Comment by nafberger** [comment]
i needs to b fixed, i doubt that the code will work

**Comment by abuzuhri** [comment]
Yes it's fixed in last version

**Comment by nafberger** [comment]
no it's a new problem, as u can see in your latest commit. the 
 [EnumMember(Value = "CAD")] is repeated twice, one for cad and one for JPY, and when the code finds duplicate  [EnumMember(Value = "CAD")] it crashes.
@abuzuhri please look in the code online on github

**Comment by nafberger** [comment]
@abuzuhri  can u please push to NuGet? would be a great great help. big thanks. looks like some tests didn't go trough

**Comment by abuzuhri** [comment]
Yes already do that
