### ISSUE TITLE
ListingPrice is NULL in QuantityDiscountPrice of GetOffersResponse

### ISSUE THREAD

**Issue by ddelucie** [abuzuhri/Amazon-SP-API-CSharp#409]
ListingPrice is not deserializing correctly in QuantityDiscountPrice when calling ProductPricing.GetListingOffers

The json returned to amazon SP API is not adhering to their spec.  The json sample from SP API below shows field named "price" and the SP API spec shows listingPrice.

https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#quantitydiscountpricetype

                "quantityDiscountPrices": [
                    {
                        "quantityTier": 3,
                        "quantityDiscountType": "QUANTITY_DISCOUNT",
                        "price": {
                            "CurrencyCode": "USD",
                            "Amount": 14.89
                        }
                    }
                ],

Sample call:

			ParameterGetListingOffers GetListingOffer = new ParameterGetListingOffers()
			{
				ItemCondition = ItemCondition.New,
				MarketplaceId = "ATVPDKIKX0DER",//MarketPlace.US.ID,
				SellerSKU = "TRPN002050GY",
                 CustomerType = CustomerType.Business
			};

			var myResult =  amazonConnection.ProductPricing.GetListingOffers(GetListingOffer);

**Comment by abuzuhri** [comment]
please share asin to test it from my side

**Comment by ddelucie** [comment]
ASIN - B0000512CU

**Comment by abuzuhri** [comment]
i don't find any **quantityDiscountPrices**  in this ASIN offer
