### ISSUE TITLE
Remove IList<T> from parameters where not needed

### ISSUE THREAD

**Issue by Xriuk** [abuzuhri/Amazon-SP-API-CSharp#412]
Hi, I noticed that most of the parameters for requests use `IList<T>` as type, is there any reason for that? Do they need to be edited by the methods before sending the requests? Or does the order inside the collection matter?

If not I would consider "downgrading" them to `IEnumerable<T>` (or `ICollection<T>`), where needed, to allow using arrays too, since `IList<T>` allows insertion and this might result in exceptions for arrays. Also lists are a bit heavier than arrays.

**Comment by J-W-Chan** [comment]
As an sdk project, I think these optimizations are not certain

**Comment by Xriuk** [comment]
It's not that much for optimization, if there is not a real reason, why use IList? You could use IEnumerable so that one could pass in whatever collection, not just the ones implementing IList.

**Comment by ProNotion** [comment]
I have to agree with @Xriuk and the reasons he has given on this so the change has my vote 👍

**Comment by abuzuhri** [comment]
for now I will downgrade to ICollection I know this still not solve the problem but many developer still add to list direct so this change will affect many developer code that use the library if they upgrade

**Comment by Xriuk** [comment]
I think the problem does not come from outside, if a developer pass a list as a parameter to the funcion they have to create and populate it anyways.
This has nothing to do with the library, so you could safely go down to IEnumerable in my opinion.
The only thing is that you should replace all the Add() you have in your code by recreating the list or by Appending values directly to the IEnumerable
