### ISSUE TITLE
AmazonQuotaExceededException thrown

### ISSUE THREAD

**Issue by Xriuk** [abuzuhri/Amazon-SP-API-CSharp#417]
Hi, I'm trying to retrieve info about many products with the API, I split them in chunks of 20 and I'm submitting them all inside a loop:
```csharp
var ChunkSize = 20;
foreach (var batch in products.Chunk(ChunkSize)) {
  var results = connection.CatalogItem.SearchCatalogItems202204(new ParameterSearchCatalogItems202204 {
    identifiers = batch.Select(p => p.Code).ToArray(),
    identifiersType = IdentifiersType.SKU,
    sellerId = VendorCode,
    pageSize = ChunkSize,
    includedData = new List<IncludedData> {
      IncludedData.identifiers
    }
  });
}
```
In the console I see that it sends out 3 requests succesfully and then it fails on the 4th.

I noticed that the 3rd request (still successful) logs:
```
... [RateLimits ,CatalogItems20220401_SearchCatalogItems]: 24/11/2022 10:02:53	 Request/Burst: FULL/2	 Rate: 2,0/500ms
```

While the first two log:
```
... [RateLimits ,CatalogItems20220401_SearchCatalogItems]: 24/11/2022 10:02:53	 Request/Burst: 2/2	 Rate: 2,0/500ms
```

Tried both Async and sync method, no difference

**Comment by abuzuhri** [comment]
@RenzoF and @J-W-Chan , Can you help here i try from my side its look ok but i want you test also

**Comment by RenzoF** [comment]
@Xriuk can you share the extension method for the chunk, pleas, so that I can test the same code

**Comment by Xriuk** [comment]
@RenzoF it's from LINQ: https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.chunk?view=net-7.0

**Comment by RenzoF** [comment]
I can't recreate this either
![image](https://user-images.githubusercontent.com/1706557/203849758-3fd3f4ab-c78b-49d3-854f-70a4136748f9.png)
the first ok the second 2 (in my case) throttled but no exception thrown.

The only case I can think of is that you are restarting your process too often or running the same code on a different thread or unit test?.
In that case, the request you can expect this exception as the request throttle by default is a single-threaded and single instance.

**Comment by Xriuk** [comment]
No threads (I guess), just that loop, running asynchronously.
If you keep calling the function, like with 200 products / 20 = 10 times do you get any exception after throttling?
Can you try also other marketplaces? Do you think it could be a marketplace issue?

**Comment by RenzoF** [comment]
I have increased the call to make it call 31 times and indeed it file in one of them,
@abuzuhri if you try testing with multiple calls you might see the same, to make it easier I tested one asin multiple times and got this result. Migth be worth buffering a bit the delay maybe? Might experiment tomorro
![image](https://user-images.githubusercontent.com/1706557/203856699-dc182936-469d-428f-8de3-da19b11dfc6a.png)

**Comment by abuzuhri** [comment]
From the time it's look ok , maybe we need to open case in Amazon to see why that happen

**Comment by RenzoF** [comment]
Should we add a couple of retries for now since the exception is not thrown (only logged) and also not retried.
Might test more but from the 31 calls I made I only had 30 results.

**Comment by abuzuhri** [comment]
But even this one shouldn't happen because we follow the documentation in Amazon.

I will do another test from my side again

**Comment by J-W-Chan** [comment]
Is it just this api that has the problem, or is it something else?

**Comment by Xriuk** [comment]
My two cents: maybe the rate/burst calculations on Amazon side are not precise? Maybe this API need a bit (more) of tolerance (daley)?
Or is it already accounted for?

**Comment by abuzuhri** [comment]
I Use the following code and arrived to 600+ request without any error <**I use new fresh application**> 

```csharp
int i = 0;
            while (true)
            {
                Console.Write(i++ + " ");
                var results = amazonConnection.CatalogItem.SearchCatalogItems202204(new ParameterSearchCatalogItems202204
                {
                    identifiers = new List<string> { "B07X4DWF8C" },
                    identifiersType = IdentifiersType.ASIN,
                    includedData = new List<IncludedData> {
                      IncludedData.identifiers
                    }
                });

            }
```
I think the problem came from amazon not from our library  

![image](https://user-images.githubusercontent.com/3703300/204031108-c2b62484-7a16-4479-9c14-197a02f37a1c.png)

**Comment by abuzuhri** [comment]
I'm going to close this as i cant see any error from our side trigger this problem , you can increase  MaxThrottledRetryCount to 10

```Csharp

AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
            {
                MaxThrottledRetryCount=10
            });

```

**Comment by RenzoF** [comment]
I am not sure what it could be but for me is consistent, I ran one test with MaxThrottledRetryCount =3  (which I have forgotten by the way) 

![image](https://user-images.githubusercontent.com/1706557/204037412-6887406d-ad53-434b-8de4-62aa1f36fe50.png)

and the second test with MaxThrottledRetryCount= 10

![image](https://user-images.githubusercontent.com/1706557/204037431-6835437d-75d5-470a-b310-55435166c348.png)

I am using production and marketplace = france

**Comment by abuzuhri** [comment]
are the application running now and call others methods ?

**Comment by RenzoF** [comment]
This is just a console app, the Amazon app is running but I don't really use the Catalog API.
They share the quota with other services/calls right? 
Might try a new app another day, though though as I mentioned I don't really use the catalog device though is always intriguing as of why is this sometimes failing 🙂 (slight OCD😂)

**Comment by abuzuhri** [comment]
I think amazon share rate limit some how , i try with another developer the application heavy use amazon service and but never use  SearchCatalogItems202204 and i get error message 

its look more Amaozn not manage rate limit exactly as the documentation

**Comment by RenzoF** [comment]
Thanks @abuzuhri  It would be nice if they shared how is supposed to work.
By the way, I just tested the MaxThrottledRetryCount and works as it should so even tho it logs QuotaExeeded is actually retrying and succeeding once again, so it's all good
