### ISSUE TITLE
Null values in response on CreateUploadDestinationForResource method

### ISSUE THREAD

**Issue by matt748** [abuzuhri/Amazon-SP-API-CSharp#418]
I have enabled the debug option and I can see the details in the raw response from amazon in the console output, however the object that the function returns has null values, any ideas what could be going wrong?

Thanks

**Comment by matt748** [comment]
Further to this, are there any examples of how to use the response to upload a document? I can't see anything in the package so I'm looking at using a raw RestSharp request. It would be great if there was a method on the API client for this.

**Comment by matt748** [comment]
I think I have figured it out. It is returning a 201 (created) response, but the code only deserialises the response for a 200 (ok) response. Any chance you could take a look at this?

**Comment by abuzuhri** [comment]
Ok share sample code and I will fix today

**Comment by matt748** [comment]
See pull request https://github.com/abuzuhri/Amazon-SP-API-CSharp/pull/419

**Comment by matt748** [comment]
Thanks for merging :) looking forward to the next release.
