### ISSUE TITLE
ReportDataTable headers and fields end up with quoted values

### ISSUE THREAD

**Issue by ProNotion** [abuzuhri/Amazon-SP-API-CSharp#429]
I'm not sure if I am trying to use this incorrectly but I am working on implementing an instance of the Inventory Ledger report, specifically for the report type `GET_LEDGER_DETAIL_VIEW_DATA` and the  `Receipts` event type. I can get the report and download it fine. I'm following other examples in the project so have a class for the report and constuctor takes a path to the report and tries to parse the values into a `ReportDataTable` as follows:

```
public class InventoryLedgerReceiptsReport
{
    public List<InventoryLedgerReceiptRow> Data { get; } = new List<InventoryLedgerReceiptRow>();
    public InventoryLedgerReceiptsReport(string path)
    {
        if (string.IsNullOrEmpty(path))
            return;

        var table = Table.ConvertFromCSV(path);

        List<InventoryLedgerReceiptRow> values = new List<InventoryLedgerReceiptRow>();
        foreach (var row in table.Rows)
        {
            values.Add(InventoryLedgerReceiptRow.FromRow(row));
        }
        Data = values;
    }
}
```

First off all, not sure if you agree but the method name `ConvertFromCSV` is a bit misleading since the default separator is actually a tab not a comma, not a big issue but might want to think about renaming it potentially?

Going back to the issue at hand, the report when downloaded has quoted fields and the quotes end up in the headers and property data and wondered if I am not using it correctly because I would have expected more reports of the issue before now?

Example:

![image](https://user-images.githubusercontent.com/1590398/205258320-b1a514a0-618c-4d52-871e-012e5d498763.png)

Do I need to update the `Table` class to strip leading and trailing quotes on each and every row?

**Comment by ProNotion** [comment]
Not sure if you are wanting to restrict third party dependencies but I've used the [CSV Helper](https://github.com/JoshClose/CsvHelper) library in the past for handling CSV's and it does the job well. I think it can also handle tab separated files too.

**Comment by abuzuhri** [comment]
> tab not a comma
why we need to have comma if the the default for most report are tab
![image](https://user-images.githubusercontent.com/3703300/205432808-cf022d91-76aa-4530-8b20-d28629fe6363.png)

**Comment by abuzuhri** [comment]
Is the content for the report also has double quote **""** ?

**Comment by ProNotion** [comment]
No double quotes in the report:

```
"Date"	"FNSKU"	"ASIN"	"MSKU"	"Title"	"Event Type"	"Reference ID"	"Quantity"	"Fulfillment Center"	"Disposition"	"Reason"	"Country"	"Reconciled Quantity"	"Unreconciled Quantity"
```

**Comment by abuzuhri** [comment]
Now its ready 

```Csharp
ReportManager reportManager1 = new ReportManager(amazonConnection);
var list=await reportManager1.GetLedgerDetailAsync(10);
```

**Comment by ProNotion** [comment]
@abuzuhri  Thanks for that - sorry for the delayed reply, I will check it out.
