### ISSUE TITLE
ReportManager.GetFeedbackFromDays results in reports in getting cancelled

### ISSUE THREAD

**Issue by ProNotion** [abuzuhri/Amazon-SP-API-CSharp#431]
Any ideas how I can find out why my report requests are getting cancelled? 

Here is the raw response back from the API and there is no detail as to why it was cancelled but it happens every time:

```
{
	"reportType": "GET_SELLER_FEEDBACK_DATA",
	"processingEndTime": "2022-12-02T16:28:16+00:00",
	"processingStatus": "CANCELLED",
	"marketplaceIds": ["A1F83G8C2ARO7P"],
	"reportId": "***",
	"dataEndTime": "2022-12-02T16:28:04+00:00",
	"createdTime": "2022-12-02T16:28:04+00:00",
	"processingStartTime": "2022-12-02T16:28:10+00:00",
	"dataStartTime": "2022-06-05T16:28:02+00:00"
}
```

**Comment by abuzuhri** [comment]
Most probably no data in the report to show

**Comment by ProNotion** [comment]
Oh, I see, so items that are struck through are not included. Is there a report where all feedback can be requested?

**Comment by abuzuhri** [comment]
No Amazon allow only 1,2,3 star feedback report not others feedback

**Comment by ProNotion** [comment]
OK, thanks for clarifying.
