### ISSUE TITLE
Reports.CreateReport(parameters) seems not working

### ISSUE THREAD

**Issue by farshadshah** [abuzuhri/Amazon-SP-API-CSharp#442]
it seems that amazonConnection.Reports.CreateReport(parameters) not working and maybe amazon server are busy or something wrong at our side.
after sending request and going through the loop till file is ready it never ends and seems the amazon server is not serving this API maybe putting some measures in place.
this API call was working perfect till 5th Dec 2022.

**Comment by smithburger** [comment]
Every store has a different opinion of how long is too long. My personal opinion is this should be handled in your application and not the library. Amazon taking a long time to return a report is not a library issue. I'm not the library author just my opinion.

**Comment by farshadshah** [comment]
normally it was responding after 60 seconds but this morning was more than 4 minutes. it seems that servers were busy.
now it is working. any way thanks for your response.
