### ISSUE TITLE
Fixing FulFillmentInbound.GetLabels when Labels generated on the web

### ISSUE THREAD

**Issue by youst03** [abuzuhri/Amazon-SP-API-CSharp#444]
If you manually create carton labels on the web there is currently no way to retrieve those labels via FulFillmentInbound.GetLabels.

You will get errors of {'errors': [{'code': 'InvalidInput',
   'message': "1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null",
   'details': ''}]}

You get similar errors even if you supply the amazon generated carton ids. 

There is a workaround by setting LabelType = SELLER_LABEL (this is an undocumented enum).  I confirmed through testing that setting this LableType (undocumented) and setting the PageSize will allow you to return GetLabels when the labels where generated from the web.

Additional details can be found here:
https://github.com/amzn/selling-partner-api-docs/issues/329

If we can add the enum LabelType.SELLER_LABEL it would allow you to get around the issue.

**Comment by abuzuhri** [comment]
@youst03 can you share sample code , we can add it to sample

**Comment by youst03** [comment]
In order to call FulFillmentInbound.GetLabels when you created the shipping plan from the web you must call the method as follows:

`

public void GetFulFillmentInboundLabelsFromWebCreationSample()
        {
            var labelParams = new ParameterGetLabels()
                {
                    MarketplaceId = marketplaceId,
                    PageType = PageType.PackageLabel_Letter_6,
                    shipmentId = shipmentId,
                    LabelType = LabelType.SELLER_LABEL,
                    PageSize =boxCount
                };
                
                 var labels = amazonConnection.FulFillmentInbound.GetLabels(labelParams);
                 
        }    
`

The key is to set LabelType = LabelType.SELLER_LABEL
