### ISSUE TITLE
Error on Feed Submit for change price :" Access to requested resource is denied."

### ISSUE THREAD

**Issue by busedemirci** [abuzuhri/Amazon-SP-API-CSharp#455]
Hi,
I am getting  "Access to requested resource is denied." while trying to change product price. I am using the below code:
           var auth =request.Authentication;

            ConstructFeedService createDocument = new ConstructFeedService("", "1.02");
            var amazonConnection = GetAmazonConnection(auth);

            var list = new List<PriceMessage>();
            list.Add(new PriceMessage()
            {
                SKU = "1",
                StandardPrice = new StandardPrice()
                {
                    currency = amazonConnection.GetCurrentMarketplace.CurrencyCode.ToString(),
                    Value = (61.7).ToString("0.00")
                }
            });
            createDocument.AddPriceMessage(list);

            var xml = createDocument.GetXML();

            var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_PRODUCT_PRICING_DATA);

            Thread.Sleep(1000 * 30);

            var feedOutput = amazonConnection.Feed.GetFeed(feedID);

            var outPut = amazonConnection.Feed.GetFeedDocument(feedOutput.ResultFeedDocumentId);

            var reportOutpit = outPut.Url;

            var processingReport = amazonConnection.Feed.GetFeedDocumentProcessingReport(outPut.Url);
If anyone can help me I would be really happy.

**Comment by abuzuhri** [comment]
Are you able to get order or access any other endpoint ?

**Comment by busedemirci** [comment]
Yes I am. I think the problem was about Amazon's pricing rule. I was able to see new price in products detail but I could not see in the inventory. Is there any rule that I need to consider about it?

**Comment by abuzuhri** [comment]
This feed rolls and after change you need to get new refresh token

**Comment by busedemirci** [comment]
Okay I will try with new refresh token thank you so much!
