### ISSUE TITLE
Fields are missing in LowestPriceType

### ISSUE THREAD

**Issue by qaisarikram** [abuzuhri/Amazon-SP-API-CSharp#456]
Few fields are missing in LowestPriceType Class (just like BuyBoxPriceType)
![image](https://user-images.githubusercontent.com/55479280/208505666-ed65fec5-1593-467d-8bbe-38b16a6541e8.png)

**Comment by RenzoF** [comment]
Hi, it would help if you specify exactly what are you missing and even better if you submit a pull request with the missing ones :-)

**Comment by qaisarikram** [comment]
Hi Renzo,
**_offerType, quantityTier and quantityDiscountType_** are missing.

![image](https://user-images.githubusercontent.com/55479280/209181493-0542222c-2313-482f-8b3a-8863673707ba.png)

(I have installed the NuGet, that's why did not submit the pull request).

**Comment by qaisarikram** [comment]
I pulled your code and I have added the code for missing fields.
I now want to check in the code.
I created a new branch for my changes and tried pushing (to create a pull request) but having 403 error. maybe it is because of Read/Write issue.
What do you suggest I should do?

**Comment by RenzoF** [comment]
Sorry I haven't had time to look at this.
To submit a pull request you need to:
- Fork this repo
- checkout/pull your code
- Create a branch
- Add your changes 
- Check in / push your changes
- Create pull request from that branch

**Comment by qaisarikram** [comment]
> 

Forked your repo, made changes and created a [pull request](https://github.com/abuzuhri/Amazon-SP-API-CSharp/pull/468)
