### ISSUE TITLE
In BR domain Issue in  Orders.GetOrderAddress("OrderId")

### ISSUE THREAD

**Issue by kapildel** [abuzuhri/Amazon-SP-API-CSharp#459]
The Response of  amzcon.Orders.GetOrderAddress(AzOrderId) not returning Address1 and Address2 other property is coming fine,
What i should check to get the missing data in response.

Thanks

**Comment by abuzuhri** [comment]
Read more about PII and how to get and see sample how to get PII order

**Comment by abuzuhri** [comment]
[github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI.SampleCode/OrdersSample.cs#L72](https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI.SampleCode/OrdersSample.cs#L72)
