### ISSUE TITLE
Error getting LWA Token

### ISSUE THREAD

**Issue by gcuadrado** [abuzuhri/Amazon-SP-API-CSharp#46]
Hi, first of all congratulate you for this awesome library. 

I am trying to start to use it but I am having a problem with the very first authetication. I have the following example code:

`AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
            {              
                AccessKey = "",
                SecretKey = "",
                RoleArn = "",
                ClientId = "",
                ClientSecret = "",
                RefreshToken = "",
                MarketPlace = MarketPlace.Spain
            });`

           `ParameterOrderList serachOrderList = new ParameterOrderList();
            //serachOrderList.CreatedAfter = DateTime.UtcNow.AddMinutes(-600000);
            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Canceled);
            var orders = amazonConnection.Orders.GetOrders(serachOrderList);`

When I execute this, I get an exception on the last line that says "Error getting LWA Token", with the following stacktrace: 

` at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.GetAccessToken()
   at FikaAmazonAPI.Services.TokenGeneration.RefreshAccessToken(AmazonCredential credentials, TokenDataType tokenDataType)
   at FikaAmazonAPI.Services.RequestService.RefreshToken(TokenDataType tokenDataType, CreateRestrictedDataTokenRequest requestPII)
   at FikaAmazonAPI.Services.RequestService.CreateAuthorizedRequest(String url, Method method, List1 queryParameters, Object postJsonObj, TokenDataType tokenDataType, Object parameter)
   at FikaAmazonAPI.Services.OrderService.GetOrders(ParameterOrderList searchOrderList)`

I think all my Amazon credentials are ok, because I am able to send request with another project using raw Restsharp requests and AWSSDK.

Thank you.

**Comment by abuzuhri** [comment]
> Hi, first of all congratulate you for this awesome library.
> 
> I am trying to start to use it but I am having a problem with the very first authetication. I have the following example code:
> 
> `AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential() { AccessKey = "", SecretKey = "", RoleArn = "", ClientId = "", ClientSecret = "", RefreshToken = "", MarketPlace = MarketPlace.Spain });`
> 
> ```
>        `ParameterOrderList serachOrderList = new ParameterOrderList();
>         //serachOrderList.CreatedAfter = DateTime.UtcNow.AddMinutes(-600000);
>         serachOrderList.OrderStatuses = new List<OrderStatuses>();
>         serachOrderList.OrderStatuses.Add(OrderStatuses.Canceled);
>         var orders = amazonConnection.Orders.GetOrders(serachOrderList);`
> ```
> 
> When I execute this, I get an exception on the last line that says "Error getting LWA Token", with the following stacktrace:
> 
> ` at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.GetAccessToken() at FikaAmazonAPI.Services.TokenGeneration.RefreshAccessToken(AmazonCredential credentials, TokenDataType tokenDataType) at FikaAmazonAPI.Services.RequestService.RefreshToken(TokenDataType tokenDataType, CreateRestrictedDataTokenRequest requestPII) at FikaAmazonAPI.Services.RequestService.CreateAuthorizedRequest(String url, Method method, List1 queryParameters, Object postJsonObj, TokenDataType tokenDataType, Object parameter) at FikaAmazonAPI.Services.OrderService.GetOrders(ParameterOrderList searchOrderList)`
> 
> I think all my Amazon credentials are ok, because I am able to send request with another project using raw Restsharp requests and AWSSDK.
> 
> Thank you.



Hello @gcuadrado 

Are you sour you follow all steps here 

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by gcuadrado** [comment]
Yes, I am using the official Amazon library for C# and I am able to retrieve orders information.

**Comment by abuzuhri** [comment]
Same code are used internal our API , please contact me in private email tareq.abuzuhri@gmail.com
I want to see the code working and the code not working please send all details

**Comment by abuzuhri** [comment]
After checking i found MarketplaceIds missing , here full working sample for both using libary and without libary

```Csharp
using Amazon.Runtime;
using Amazon.SecurityToken;
using Amazon.SecurityToken.Model;
using Amazon.SellingPartnerAPIAA;
using FikaAmazonAPI;
using FikaAmazonAPI.Parameter.Order;
using FikaAmazonAPI.Utils;
using RestSharp;
using static FikaAmazonAPI.Utils.Constants;

namespace PruebaAmazon
{
    class Program
    {
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("AccessKey", "....");
            Environment.SetEnvironmentVariable("SecretKey", "....");
            Environment.SetEnvironmentVariable("RoleArn", "arn:aws:iam::00000000:role/00000");
            Environment.SetEnvironmentVariable("ClientId", "amzn1.application-oa2-client.0000000000");
            Environment.SetEnvironmentVariable("ClientSecret", "000000000000000000000000000000");
            Environment.SetEnvironmentVariable("RefreshToken", "Atzr|000000000000000000000000000000000000000");


            //string response = getResponse("/orders/v0/orders", Method.GET, false, null);


            var amazonConnection = new AmazonConnection(new AmazonCredential()
            {
                AccessKey = Environment.GetEnvironmentVariable("AccessKey"),
                SecretKey = Environment.GetEnvironmentVariable("SecretKey"),
                RoleArn = Environment.GetEnvironmentVariable("RoleArn"),
                ClientId = Environment.GetEnvironmentVariable("ClientId"),
                ClientSecret = Environment.GetEnvironmentVariable("ClientSecret"),
                RefreshToken = Environment.GetEnvironmentVariable("RefreshToken"),
                MarketPlace = MarketPlace.Spain

            });

            ParameterOrderList serachOrderList = new ParameterOrderList();
            serachOrderList.CreatedAfter = DateTime.UtcNow.AddDays(-5);
            serachOrderList.MarketplaceIds=new List<string>();
            serachOrderList.MarketplaceIds.Add(MarketPlace.Spain.ID);
            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Canceled);
            var orders = amazonConnection.Orders.GetOrders(serachOrderList);

            
        }

        private static string getResponse(string endpoint, RestSharp.Method httpMethod, bool pruebas, Object body = null)
        {
            AssumeRoleResponse assumeRoleResponse = null;
            DateTime checkDate = DateTime.UtcNow.AddDays(-5);

            Task.Run(async () =>
            {
                assumeRoleResponse = await GetAssumeRoleTokenDetail();
            }).GetAwaiter().GetResult();

            string urlProduccion = "https://sellingpartnerapi-eu.amazon.com";
            string urlPruebas = "https://sandbox.sellingpartnerapi-eu.amazon.com/";
            RestClient restClient = new RestClient(!pruebas ? urlProduccion : urlPruebas);
            // IRestRequest restRequest = new RestRequest("orders/v0/orders/TEST_CASE_200/orderItems/buyerInfo", Method.GET);
            IRestRequest restRequest = new RestRequest(endpoint, httpMethod);

            restRequest.AddQueryParameter("MarketplaceIds", "A1RKKUPIHCS9HS");
            restRequest.AddQueryParameter("CreatedAfter", checkDate.ToString("yyyy-MM-ddTHH:mm:ssZ"));



            AWSAuthenticationCredentials AWSCredentials = new AWSAuthenticationCredentials();
            AWSCredentials.AccessKeyId = assumeRoleResponse.Credentials.AccessKeyId;
            AWSCredentials.SecretKey = assumeRoleResponse.Credentials.SecretAccessKey;
            AWSCredentials.Region = "eu-west-1";


            LWAAuthorizationCredentials LWACredentials = new LWAAuthorizationCredentials();
            LWACredentials.ClientId = Environment.GetEnvironmentVariable("ClientId");
            LWACredentials.ClientSecret = Environment.GetEnvironmentVariable("ClientSecret");
            LWACredentials.Endpoint = new Uri("https://api.amazon.com/auth/o2/token");
            LWACredentials.RefreshToken = Environment.GetEnvironmentVariable("RefreshToken");
            restRequest = new LWAAuthorizationSigner(LWACredentials).Sign(restRequest);

            restRequest.AddHeader("X-Amz-Security-Token", assumeRoleResponse.Credentials.SessionToken);

            if (httpMethod == Method.POST && body != null)
            {
                restRequest.AddJsonBody(body);
            }

            restRequest = new AWSSigV4Signer(AWSCredentials).Sign(restRequest, restClient.BaseUrl.Host);



            IRestResponse response = restClient.Execute(restRequest);

            return response.Content;
        }

        private static async Task<AssumeRoleResponse> GetAssumeRoleTokenDetail()
        {
            // AWS IAM user data, NOT seller central dev data
            var accessKey = Environment.GetEnvironmentVariable("AccessKey"); // get from users access key id from first step
            var secretKey = Environment.GetEnvironmentVariable("SecretKey"); // get from users secret key from first step

            var credentials = new BasicAWSCredentials(accessKey, secretKey);

            var client = new AmazonSecurityTokenServiceClient(credentials);

            var assumeRoleRequest = new AssumeRoleRequest()
            {
                DurationSeconds = 3600,
                // role ARN you create here: 
                // https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-an-iam-role
                RoleArn = Environment.GetEnvironmentVariable("RoleArn"),
                RoleSessionName = DateTime.Now.Ticks.ToString()
            };

            var assumeRoleResponse = await client.AssumeRoleAsync(assumeRoleRequest);

            Console.WriteLine(assumeRoleResponse.HttpStatusCode);

            return assumeRoleResponse;
        }
    }
}


```
