### ISSUE TITLE
Getting Products

### ISSUE THREAD

**Issue by busedemirci** [abuzuhri/Amazon-SP-API-CSharp#461]
I hope I'm not asking too many questions but I need to ask this. Is there a way to get the items in my inventory without using reports? As a result of all my searches, I could not find any results other than the report.

**Comment by ProNotion** [comment]
Out of curiosity - why do you not want to use reports? 

You should be able to use the Inventory API to get details of your listings.  

E.g.

```
var inventorySearchOptions = new ParameterGetInventorySummaries()
{
    granularityId = MarketPlace.UnitedKingdom.ID,
    granularityType = Granularity.GranularityTypeEnum.Marketplace
};

return await _amazonConnection.FbaInventory.GetInventorySummariesAsync(inventorySearchOptions);
```

**Comment by busedemirci** [comment]
When I use a report, the summary of my lists comes in text format and I don't want that. If my listings come in the list, I won't have to parse .txt format.

By the way, thank you for your help, but I couldn't get my products using the code above. I am sharing my code below. I couldn't find where I went wrong. Please let me know if you see the wrong part of my code.

var inventorySearchOptions = new ParameterGetInventorySummaries()
            { 
                sellerSkus= new List<string>() { "1", "2", "3" },
                granularityId = MarketPlace.Turkey.ID,
                granularityType = Granularity.GranularityTypeEnum.Marketplace
            };

            var invData=  await amazonConnection.FbaInventory.GetInventorySummariesAsync(inventorySearchOptions);

**Comment by ProNotion** [comment]
Using the ReportManager you shouldn't need to parse the files yourself if you want to use the reports. 

```
ReportManager reportManager = new ReportManager(_amazonConnection);
return await reportManager.GetProductsAsync();
```
Also, if you've not already checked it out I suggest spending some time going through [the samples](https://github.com/abuzuhri/Amazon-SP-API-CSharp/tree/main/Source/FikaAmazonAPI.SampleCode).

You didn't specify what exception you were getting using your code. I've not used the sellerSkus parameter before so not sure what sort of error you might be seeing.

**Comment by busedemirci** [comment]
Oh thank you so much I was able to get my listings using report manager. I was struggling thank you!! Also I wasn't seeing any error when I use above code part but just empty list.

**Comment by ProNotion** [comment]
At a guess then the SKU's you were providing were not found in the marketplace perhaps?

**Comment by busedemirci** [comment]
I don't know. They are active listings in my inventory and I can update their stock value using SKU's. Maybe it was about startDateTime.

**Comment by ProNotion** [comment]
`startDateTime` was not in the query you provided so if you were actually using that then yes that is the likely reason.

**Comment by busedemirci** [comment]
Maybe but report manager solved my problem. Thank you again!
