### ISSUE TITLE
SubmitFeed

### ISSUE THREAD

**Issue by ramonmayedo** [abuzuhri/Amazon-SP-API-CSharp#466]
When I send a call to create the fullfilment details, it happens that the call fails, I have followed the code and it is given in line 247 of the FeedService.cs file
** if (System.IO.Path.IsPathRooted(contentOrFilePath))  **

I establish the order of the calls in the debug
```
 1 - amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_ORDER_FULFILLMENT_DATA);
      -   Task.Run(() => SubmitFeedAsync(XmlContentOrFilePath, feedType, marketPlaceIds, feedOptions, contentType)).ConfigureAwait(false).GetAwaiter().GetResult();
            -  _ = await PostFileDataAsync(feedCreate.Url, feedContentOrFilePath, contentType);
                  -             if (System.IO.Path.IsPathRooted(contentOrFilePath))
```

The error is that the System.IO.Path.IsPathRooted method finds an invalid character and completely crashes the web application. I have tried removing this code and directly writing the call with
`System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);`

and it has worked perfectly. I have only tested the call described above for the  fullfilment details.

Installed version of System.IO 4.3.0

**Comment by ramonmayedo** [comment]
Yes, I have changed certain parameters such as the order number, seller id and the order number and put another value and the same continues with the same problem, I leave the xml below. Thank you very much for your reply

`<?xml version="1.0" encoding="UTF-16"?>
-<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
-<Header>
<DocumentVersion>1.02</DocumentVersion>
<MerchantIdentifier>XXXXXXXXXXX</MerchantIdentifier>
</Header>
<MessageType>OrderFulfillment</MessageType>
-<Message>
<MessageID>1</MessageID>
<OperationType>Update</OperationType>
-<OrderFulfillment>
<AmazonOrderID>1212</AmazonOrderID>
<FulfillmentDate>2022-12-23T14:49:31.332+01:00</FulfillmentDate>
-<FulfillmentData>
<CarrierName>GLS</CarrierName>
<ShippingMethod>ePaq</ShippingMethod>
<ShipperTrackingNumber>CS6456456456</ShipperTrackingNumber>
</FulfillmentData>
</OrderFulfillment>
</Message>
</AmazonEnvelope>`

**Comment by RenzoF** [comment]
Thanks for providing this, I'll test it in a bit to see if I can recreate it
from the image, is that first character part of the data or is it the way you copied it?
![image](https://user-images.githubusercontent.com/1706557/209350045-d090c78d-1b7e-47d9-b8e5-58eaf6bf3772.png)

**Comment by ramonmayedo** [comment]
This character does not go, it was an error when copying from the visual studio debug, again when I updated the order in amazon marketplace it worked perfectly, what I explained in the first comment, the problem is in the System.IO.Path.IsPathRooted method, I can test it independently, passing the test xml that I put and it doesn't work

**Comment by ramonmayedo** [comment]
For example, I know that it is an io problem because when I try the following code it generates the exception
```
            try
            {
                var XMLTest = "<?xml version=\"1.0\" encoding=\"UTF-16\"?>\r\n<AmazonEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n<Header>\r\n<DocumentVersion>1.02</DocumentVersion>\r\n<MerchantIdentifier>XXXXXXXXXXX</MerchantIdentifier>\r\n</Header>\r\n<MessageType>OrderFulfillment</MessageType>\r\n<Message>\r\n<MessageID>1</MessageID>\r\n<OperationType>Update</OperationType>\r\n<OrderFulfillment>\r\n<AmazonOrderID>1212</AmazonOrderID>\r\n<FulfillmentDate>2022-12-23T14:49:31.332+01:00</FulfillmentDate>\r\n<FulfillmentData>\r\n<CarrierName>GLS</CarrierName>\r\n<ShippingMethod>ePaq</ShippingMethod>\r\n<ShipperTrackingNumber>CS6456456456</ShipperTrackingNumber>\r\n</FulfillmentData>\r\n</OrderFulfillment>\r\n</Message>\r\n</AmazonEnvelope>";
                if (System.IO.Path.IsPathRooted(XMLTest))
                {
                    throw new Exception("Ok");
                }

            }
            catch (Exception exep)
            {
                throw new Exception(exep.Message);
            }
```

**Comment by RenzoF** [comment]
I have just tried this and the result is isPathRooted is false (which is expected) trying to work out the invalid character, maybe is in one of the data you have removed?.
Can you try this and see what results do you get?

![image](https://user-images.githubusercontent.com/1706557/209352160-fe7680aa-3b95-4c74-b5e6-beb5437ee7be.png)

**Comment by RenzoF** [comment]
> try
>             {
>                 var XMLTest = "<?xml version=\"1.0\" encoding=\"UTF-16\"?>\r\n<AmazonEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n<Header>\r\n<DocumentVersion>1.02</DocumentVersion>\r\n<MerchantIdentifier>XXXXXXXXXXX</MerchantIdentifier>\r\n</Header>\r\n<MessageType>OrderFulfillment</MessageType>\r\n<Message>\r\n<MessageID>1</MessageID>\r\n<OperationType>Update</OperationType>\r\n<OrderFulfillment>\r\n<AmazonOrderID>1212</AmazonOrderID>\r\n<FulfillmentDate>2022-12-23T14:49:31.332+01:00</FulfillmentDate>\r\n<FulfillmentData>\r\n<CarrierName>GLS</CarrierName>\r\n<ShippingMethod>ePaq</ShippingMethod>\r\n<ShipperTrackingNumber>CS6456456456</ShipperTrackingNumber>\r\n</FulfillmentData>\r\n</OrderFulfillment>\r\n</Message>\r\n</AmazonEnvelope>";
>                 if (System.IO.Path.IsPathRooted(XMLTest))
>                 {
>                     throw new Exception("Ok");
>                 }
> 
>             }
>             catch (Exception exep)
>             {
>                 throw new Exception(exep.Message);
>             }

I copy and paste this and it doesn't throw an exception for me, I take it you have pulled the latest version right?
Not sure what it could be

**Comment by ramonmayedo** [comment]
You can put the XML text, it is an image

**Comment by ramonmayedo** [comment]
The version I have is
![image](https://user-images.githubusercontent.com/55454008/209353188-fa541494-f26f-437e-b9e9-869db2454cad.png)

**Comment by RenzoF** [comment]
the xml it the one you provided, 
![Screencast at December 23rd 2022 - 2 38 04 pm](https://user-images.githubusercontent.com/1706557/209353159-77b80b67-0b95-4ee2-9984-3555fb024df5.gif)



> What version of System.IO do you have installed?

None, my project is .Net 6.0

**Comment by ramonmayedo** [comment]
My project is in
![image](https://user-images.githubusercontent.com/55454008/209354246-d5636c47-f13b-4040-aa88-adc2f23f44cc.png)
You can try this version

**Comment by RenzoF** [comment]
Sorry it has been years since I stopped using other than dotnet core and above and I don't really have them installed, maybe someone else can help with testing? @abuzuhri 
![image](https://user-images.githubusercontent.com/1706557/209354960-03654e42-1c04-4d80-a3ec-f5d24575af35.png)

**Comment by ramonmayedo** [comment]
I think that as a suggestion to avoid this type of problems between versions, use an enum variable to determine what is going to be written to the buffer, so as not to check the content of the file to know what is going to be written. I appreciate your help and the code is very readable

```
       private async Task<string> PostFileDataAsync(string destinationUrl, string contentOrFilePath, ContentType contentType = ContentType.XML)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(destinationUrl);

            byte[] bytes;

            if (System.IO.Path.IsPathRooted(contentOrFilePath))
            {
                // The string looks like a file path, so try to read the file
                if (System.IO.File.Exists(contentOrFilePath))
                {
                    bytes = System.IO.File.ReadAllBytes(contentOrFilePath);
                }
                else
                {
                    // The file does not exist, so treat the string as content
                    bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                }
            }
            else if (Uri.IsWellFormedUriString(contentOrFilePath, UriKind.RelativeOrAbsolute))
            {
                // The string looks like a URI, so try to parse it as a file URI
                var uri = new Uri(contentOrFilePath);
                if (uri.IsFile)
                {
                    if (System.IO.File.Exists(uri.LocalPath))
                    {
                        bytes = System.IO.File.ReadAllBytes(uri.LocalPath);
                    }
                    else
                    {
                        // The file does not exist, so treat the string as content
                        bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                    }
                }
                else
                {
                    // The URI is not a file URI, so treat the string as content
                    bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                }
            }
            else
            {
                // The string is not a file path or a URI, so treat it as content
                bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
            }

            request.ContentType = LinqHelper.GetEnumMemberValue(contentType);
            request.ContentLength = bytes.Length;
            request.Method = "PUT";
            using (Stream requestStream = request.GetRequestStream())
            {
                requestStream.Write(bytes, 0, bytes.Length);
                requestStream.Close();
                HttpWebResponse response = (HttpWebResponse)await request.GetResponseAsync();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    Stream responseStream = response.GetResponseStream();
                    string responseStr = await new StreamReader(responseStream).ReadToEndAsync();
                    return responseStr;
                }
            }
            return null;
        }
```

**Comment by RenzoF** [comment]
The only problem is that if we add a new enum is introducing breaking changes as everyone who is already using the library will have to modify their code.
I am not the Author of the library so not sure how far is the plan to support older frameworks.

As for your issue, this might be related, maybe it helps
https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.6-4.7

**Comment by abuzuhri** [comment]
i try in many version , in new version its work in old version its not , 

problem solved in other way
