### ISSUE TITLE
Remove RestSharp

### ISSUE THREAD

**Issue by jmawebtech** [abuzuhri/Amazon-SP-API-CSharp#47]
Hi,

I notice that you use RestSharp in your code:

https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI/Services/TokenGeneration.cs

I was able to remove RestSharp and use HttpClient. If I fork and add the code, will you merge into a new build? I would prefer not to use RestSharp.

**Comment by abuzuhri** [comment]
> I was able to remove RestSharp and use HttpClient. If I fork and add the code, will you merge into a new build? I would prefer not to use RestSharp.

Can you explain why (you don't prefer to use RestSharp) ?

**Comment by jmawebtech** [comment]
Our tool maps sales from eBay and we use their SDK. We already have a reference to RestSharp and I'd prefer not to do assembly binding.

**Comment by abuzuhri** [comment]
If you upgrade to RestSharp last version in your tools and the same I can do here , is that solve the problem ?

**Comment by abuzuhri** [comment]
If that not solve the problem you can go ahead fork and add the code.
