### ISSUE TITLE
Authentication problems - not authorized to perform sts:AssumeRole 

### ISSUE THREAD

**Issue by KevinPoorDeveloper** [abuzuhri/Amazon-SP-API-CSharp#471]
Hi,

This SDK looks amazing but I'm having some problems with this. Here's the error I get from the compiled code:

`Amazon.SecurityToken.AmazonSecurityTokenServiceException: 'User: arn:aws:iam::123456789:user/UserAccount is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789:user/UserAccount '`

But if I make a post directly to:
https://api.amazon.com/auth/o2/token

With these parameters:
grant_type
refresh_token
client_id
client_secret

I get back data that includes an access_token directly from Amazon. 
This implies this isn't an IAM issue, correct?

Also note I'm not trying to build a 3rd party application, we're a seller and are looking to build our own.

Thanks for any help.

**Comment by sat-it** [comment]
Hi,

try role arn and not the user arn.

https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities
in AWS account.
Identity and Access Management (IAM)
Role
arn:aws:iam::12345789:role/"Name"
copy this value

and use it in your sellercentral account
Developer Central
IAM ARN

Best regards

**Comment by KevinPoorDeveloper** [comment]
Thank you - that worked. I appreciate it, this is not a bug you can close this, sorry for the inconvenience.
