### ISSUE TITLE
Something went wrong on deserialize report stream - error in GetFeedDocumentProcessingReportAsync

### ISSUE THREAD

**Issue by Tajanos** [abuzuhri/Amazon-SP-API-CSharp#473]
However the actual report seems fine and it can be retrieved from the FeedDocument.Url, although it seems to be txt, not xml. See attached.

I am guessing that this happens when the original feed is txt and the resulting report is probably then also txt.
[amzn1.tortuga.4.na.629d0eff-90c6-4932-83ac-597b0fb1bf62.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/10340735/amzn1.tortuga.4.na.629d0eff-90c6-4932-83ac-597b0fb1bf62.txt)

**Comment by abuzuhri** [comment]
are you still facing this error ?
