### ISSUE TITLE
Outbound Order Posting on FBA throwing UnAuthorised Error

### ISSUE THREAD

**Issue by asifiq2000** [abuzuhri/Amazon-SP-API-CSharp#475]
Hi @abuzuhri  I have created a Post method wherein I am trying to post a test order on FBA but getting UnAuthorized error,
sharing below the reference code, please correct me if I am wrong doing this task,
However I am able to create token, import orders, post tracking, post inventory on amazon successfully, there is no authorization or access error.

CODE
------
[HttpPost("PostFbaOrderOnAmazon")]
    public IActionResult PostFbaOrderOnAmazon(string mRefreshToken, string mOrderID)
    {
        AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
        {
            AccessKey = "AKIXXX",
            SecretKey = "0q7XXX",
            RoleArn = "arn:aws:iam::07XXX",
            ClientId = "amzn1.applXXX",
            ClientSecret = "26fbXXX",
            RefreshToken = mRefreshToken,
            MarketPlace = MarketPlace.GetMarketPlaceByID("ATVPDKIKX0DER"),
        });

        var restrictedResource = new RestrictedResource();
        restrictedResource.method = Method.GET.ToString();
        restrictedResource.path = ApiUrls.OrdersApiUrls.OrderItems(mOrderID);
        //restrictedResource.dataElements = new List<string> { "buyerInfo", "shippingAddress" };
        var createRDT = new CreateRestrictedDataTokenRequest()
        {
            restrictedResources = new List<RestrictedResource> { restrictedResource }
        };

        var parameterBasedPII = new ParameterBasedPII();
        parameterBasedPII.IsNeedRestrictedDataToken = true;
        parameterBasedPII.RestrictedDataTokenRequest = createRDT;

        CreateFulfillmentOrderRequest createorderrequest = new CreateFulfillmentOrderRequest();
        createorderrequest.MarketplaceId = "US";
        createorderrequest.FulfillmentAction = FulfillmentAction.Ship;
        CreateFulfillmentOrderItem item = new CreateFulfillmentOrderItem();
        createorderrequest.Items = new CreateFulfillmentOrderItemList();
        item.SellerFulfillmentOrderItemId = "TestItem1";
        item.Quantity = 1;
        item.SellerSKU = "TestSKU";
        item.SellerFulfillmentOrderItemId = "111";
        createorderrequest.Items.Add(item);
        createorderrequest.DestinationAddress = new Address();
        createorderrequest.DestinationAddress.City="";
        createorderrequest.DestinationAddress.StateOrProvinceCode = "";
        createorderrequest.DestinationAddress.CountryCode = "";
        createorderrequest.DestinationAddress.PhoneNumber = "";
        createorderrequest.DestinationAddress.PostalCode = "";
        createorderrequest.DestinationAddress.Name = "";
        createorderrequest.DestinationAddress.Line1 = "";
        createorderrequest.DestinationAddress.Line2 = "";
        var orderDet = amazonConnection.FulFillmentOutbound.CreateFulfillmentOrder(createorderrequest);
    

ERROR
--------
![image](https://user-images.githubusercontent.com/40463094/211000672-95e379dd-993b-48c3-9ea2-cbc7cfa4b3c2.png)

![image](https://user-images.githubusercontent.com/40463094/211001229-3f1dd30f-0182-4f16-a856-1621a292b34d.png)

**Comment by abuzuhri** [comment]
I don't think you have access to PII data
