### ISSUE TITLE
GetShipmentItemsByShipmentIdAsync doesn't return NextToken

### ISSUE THREAD

**Issue by HakanL** [abuzuhri/Amazon-SP-API-CSharp#476]
GetShipmentItemsByShipmentIdAsync doesn't return a NextToken. And GetShipmentItemsAsync iterates using the NextToken instead of returning it, making the GetShipmentItemsByNextTokenAsync useless.

**Comment by RenzoF** [comment]
GetShipmentItemsByShipmentIdAsync returns a GetShipmentItemsResponse with a payload of GetShipmentItemsResult and each has a next token as per the documentation, am I missing something? can you explain a bit more about the issue or what you are trying to achieve?

**Comment by HakanL** [comment]
Sorry, I must've overlooked the response from GetShipmentItemsByShipmentIdAsync, you're correct that it returns the NextToken, _but GetShipmentItemsAsync does not_. So if I want to get more items from GetShipmentItemsByShipmentIdAsync's NextToken then I need to call GetShipmentItemsByNextTokenAsync, but it requires a ParameterGetShipmentItems which GetShipmentItemsByShipmentIdAsync doesn't use (and GetShipmentItemsAsync returns all items).

**Comment by RenzoF** [comment]
'but GetShipmentItemsAsync does not.'

This is the same the response payload is has a result with the netxtoken 

You might want to have a look at the docs https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitems

If you have a nexttoken (which you should have form the result) all you required to pass is the nexttoken with a query type of next_token

**Comment by HakanL** [comment]
But GetShipmentItemsAsync will go through all the NextToken, so if you have 10000 items then they will all be loaded into memory. The issue is that it's inconsistent, some methods go through all items (using NextToken in your code) and some return the NextToken. It would be more advantageous if the library was consistent in the API, so it always returns a NextToken (and never iterate through the full list), or add additional methods to process the NextToken paging, so a developer can choose to use either or. The issue is that GetShipmentItemsAsync does it differently than GetShipmentItemsByShipmentIdAsync.

**Comment by HakanL** [comment]
MaxNumberOfPages would limit the total output, I still need the full output (by iterating through with NextToken), but don't want to potentially run out of memory. That's why I'd like a GetShipmentItems that doesn't iterate the NextToken, instead of returning it. And/or a GetShipmentItemsByShipmentIdNextTokenAsync method.
Ok, no worries, I meant the code in this library, whoever owns it :)

**Comment by RenzoF** [comment]
You are right, I think that at least it should be returning the GetShipmentItemsResponse (as per the docs) not the list of items.

**Comment by abuzuhri** [comment]
I agree we sold solve with same way we did in order @RenzoF , he can pass number of pages he want if its only 1 then we return NextToken

**Comment by abuzuhri** [comment]
We solve this by add **NextToken** to response , in case you want only one page you can set **MaxNumberOfPages** to one and then you will get one page and **NextToken**

**Comment by HakanL** [comment]
This isn't completely solved. So we have a `NextToken` on the response from `GetShipmentItemsByShipmentIdAsync`, which is good. But there's no method for `GetShipmentItemsByShipmentIdNextTokenAsync`, so I can't get more items. There is `GetShipmentItemsByNextTokenAsync`, but it requies a `ParameterGetShipmentItems`, which I don't have since I called `GetShipmentItemsByShipmentIdAsync`.

**Comment by HakanL** [comment]
@ProNotion Thanks, I know how to work around it, but I was primarily pointing out the inconsistency in the methods and suggest that it should be changed to improve the library.
