### ISSUE TITLE
Upload the Flat-File-AutomatePricing

### ISSUE THREAD

**Issue by OliverZemke2021** [abuzuhri/Amazon-SP-API-CSharp#477]
Hello,

is there a FeedType to upload the flate file for the automate pricing?
At the attachment is flate file that I want to upload.
[Flat.File.AutomatePricing.xlsx](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/10373236/Flat.File.AutomatePricing.xlsx)

Best regards
Olli

**Comment by abuzuhri** [comment]
@RenzoF do you work with file has same format before ?

**Comment by RenzoF** [comment]
My guess is there is one but undocumented.
What I have done before is to update the min and max price using the POST_PRODUCT_PRICING_DATA feed then generate one file do the rules association.
The problem with trying to automate this is that the repricer would pause for a while on every price update.

**Comment by abuzuhri** [comment]
@OliverZemke2021  Do you solve the problem ?

**Comment by OliverZemke2021** [comment]
@RenzoF I do not understand the part with "generate one file do the rules association."?

**Comment by RenzoF** [comment]
I generate a file like the one you posted but only use it to associate/assign the sku to a specific rule. Which in my case doesn't change that often, but the pricing does.

**Comment by abuzuhri** [comment]
@OliverZemke2021 For me I see repricing is very complicate and amazon made it simple as much as they can , I think the best way to do repricing is to do your own software after you look to repricing software now in market at least do you own code no need for UI

**Comment by OliverZemke2021** [comment]
@abuzuhri and @RenzoF Thank you for the information. I will give it a try.
