### ISSUE TITLE
possible to improve response times?

### ISSUE THREAD

**Issue by wheelersf** [abuzuhri/Amazon-SP-API-CSharp#48]
Hi Tareq,

I'm doing some testing and am consistently seeing these response times for the following operations:

Retrieve Orders: 00:01:01.48
Retrieve Order Items: 00:00:02.15
Retrieve Address: 00:01:00.02
Retrieve Order: 00:01:00.04

While retrieving ordered items is very quick, retrieval of orders, order, and address always seem to take about 1 minute.  Is there any room to better optimize these times?  

Thanks,
Scott

**Comment by abuzuhri** [comment]
Hi @wheelersf ,

Do you read about amazon rate limit ('x-amzn-RateLimit-Limit')
Can you change the setting setting and add (IsActiveLimitRate=false) in AmazonConnection
```CSharp            
var amazonConnection = new AmazonConnection(new AmazonCredential()
            {
                .
                .
                IsActiveLimitRate=false

            });
```

**Comment by wheelersf** [comment]
What a difference that parameter makes!  Thanks a bunch!

Retrieve Orders: 00:00:02.27
Retrieve Order Items: 00:00:00.18
Retrieve Address: 00:00:00.13
Retrieve Order: 00:00:00.14

**Comment by abuzuhri** [comment]
Hello @wheelersf 

If you don't use this parameter set as true you will get error when you do heavy use to Amazon API 
Read here
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md

**Comment by abuzuhri** [comment]
we start this if you want to share with test https://github.com/abuzuhri/Amazon-SP-API-CSharp/discussions/109
