### ISSUE TITLE
LWAClient GetAccessTokenAsync occasionally throws WebException "The underlying connection was closed: "

### ISSUE THREAD

**Issue by tank104** [abuzuhri/Amazon-SP-API-CSharp#484]
We have switched over to this for 100s merchants and get the occasional nested nested exception of "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."

Error details below.  Does anyone else get this?  I don't think we are hitting the 1 request per second to get token.

....
Type:
System.SystemException
Message:
Error getting LWA Access Token
Source:
FikaAmazonAPI
Target Site:
Void MoveNext()
Data:
System.Collections.ListDictionaryInternal
Stack Trace:
at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.<GetAccessTokenAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
...

-- Nested Exception --

Type:
System.IO.IOException
Message:
Unsuccessful LWA token exchange
Source:
FikaAmazonAPI
Target Site:
Void MoveNext()
Data:
System.Collections.ListDictionaryInternal
Stack Trace:
at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.<GetAccessTokenAsync>d__15.MoveNext()

-- Nested Exception --

Type:
System.Net.WebException
Message:
The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
Source:
System
Target Site:
System.Net.WebResponse EndGetResponse(System.IAsyncResult)
Data:
System.Collections.ListDictionaryInternal
Stack Trace:
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback

**Comment by abuzuhri** [comment]
its look like rejection came from amazon server
