### ISSUE TITLE
How to Sign the request using LWA Client

### ISSUE THREAD

**Issue by affan848** [abuzuhri/Amazon-SP-API-CSharp#487]
Hello Dear,
Thank you for the great template project. I have all the keys to make a request to Amazon API, and everything between the seller central and aws, policy, role, and sts are configured.

However, I am unable to call the below request and it's showing me that I need to sign the request. How can I do it?

 ParameterOrderList serachOrderList = new ParameterOrderList();
            serachOrderList.CreatedBefore = DateTime.Now;
            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Shipped);
            var orders = amazonConnection.Orders.GetOrders(serachOrderList);

Upon making the above call with all the credentials, it's giving me the following exception:

AmazonAPIClassLibrary.AmazonSpApiSDK.Models.Exceptions.AmazonUnauthorizedException: 'Access to requested resource is denied.'

and debugging is taking me to this piece of code, which means I need to sign the request first (see attachment)

Also, in your project the LWAAuthorizationSigner is excluded in the csproj file:

<ItemGroup>
    <Compile Remove="AmazonSpApiSDK\Runtime\LWAAuthorizationSigner.cs" />
  </ItemGroup>

When I tried to include that, it's giving me errors.

Can you please help?
![AmazonInvalidSignatureException](https://user-images.githubusercontent.com/10120009/213260719-bd70fc58-376b-40c0-83ff-477fc648327f.png)

**Comment by abuzuhri** [comment]
The API working without problem for many developers , you need recheck your setting added step by step to solve your problem

**Comment by affan848** [comment]
Dear,
Thank you for the response, I figured that out. It is working great. Thanks for the project.
