### ISSUE TITLE
SellerDeclaredValue not being serialized correctly

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#488]
hi i am trying to run this code snippet:

`            var transportDetailInput = new FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.TransportDetailInput();
            transportDetailInput.PartneredLtlData = new PartneredLtlDataInput();
            transportDetailInput.PartneredLtlData.SellerDeclaredValue = new FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.Amount(BaseXML.BaseCurrencyCode.USD, 500);
            transportDetailInput.PartneredLtlData.TotalWeight = new FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.Weight();
            transportDetailInput.PartneredLtlData.TotalWeight.Unit = UnitOfWeight.Pounds;
            transportDetailInput.PartneredLtlData.TotalWeight.Value = 500;`

but the resulting json does not include the currency code, cant understand why

**Comment by nafberger** [comment]
thats the json generated:

{
  "PartneredLtlData": {
    "TotalWeight": {
      "Unit": "pounds",
      "Value": 500.0
    },
    "SellerDeclaredValue": {
      "Value": 500.0
    }
  }
}

**Comment by nafberger** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/26122027/213952871-2618745e-f56c-4b56-8c8c-89b9a7c2c535.png)

**Comment by RenzoF** [comment]
Have a look at #284
I think is the issue issue with newtons or not serialising properly unless it has an USD=1 in the enum

**Comment by abuzuhri** [comment]
@nafberger do you still facing issue here ?
