### ISSUE TITLE
SubmitFeed Issues

### ISSUE THREAD

**Issue by RHarrison1** [abuzuhri/Amazon-SP-API-CSharp#490]
Hi, 

I have been testing out calls to SP-API via Amazon-SP-API-CSHarp.

My test application was using version 1.15.23

So I decided to upgrade to 1.15.31.  However since this the call to SubmitFeed seems to fails.  I get 'illegal characters in path.
I rolled back to 1.15.23 and all worked again.
I therefore started rolling forward.  1.15.24 worked.

1.15.25 gives error - Invalid URI: The URI scheme is not valid.
1.15.26 gives error - Invalid URI: The URI scheme is not valid.
1.15.27 gives error - Illegal characters in path
1.15.28 gives error - Illegal characters in path
1.15.29 gives error - Illegal characters in path
1.15.30 gives error - Illegal characters in path
1.15.31 gives error - Illegal characters in path

My test code is

ConstructFeedService createDocument = new ConstructFeedService(SellerID, "1.02");
var list = new List<InventoryMessage>();
list.Add(new InventoryMessage()
{
      SKU = "RAG001",
      Quantity = Convert.ToInt32(maskedTextBox1.Text),
     FulfillmentLatency = "1",
});
createDocument.AddInventoryMessage(list);
var xml = createDocument.GetXML();
var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_INVENTORY_AVAILABILITY_DATA);

So no different from your examples.  Could you please look to fix issue in latest.

**Comment by abuzuhri** [comment]
Please donwoad last version and call method name (SubmitFeedContent)
