### ISSUE TITLE
FikaAmazonAPI.AmazonSpApiSDK.Models.Orders.Order deserialize dates into DateTime instead of strings

### ISSUE THREAD

**Issue by Xriuk** [abuzuhri/Amazon-SP-API-CSharp#491]
Is it possible to deserialize Amazon response dates into DateTime instead of strings? Or create new properties which would convert to/from those (to avoid breaking existing APIs, even though they should become deprecated).

These should be mandatory so just `DateTime`
https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/6a54734a0e946ec7152ac8200edd45b2911cc397/Source/FikaAmazonAPI/AmazonSpApiSDK/Models/Orders/Order.cs#L335-L347

While these should be optional so `DateTime?`
https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/6a54734a0e946ec7152ac8200edd45b2911cc397/Source/FikaAmazonAPI/AmazonSpApiSDK/Models/Orders/Order.cs#L437-L463

**Comment by abuzuhri** [comment]
yes why not , you can fix that and submit new PR , and we will approve
