### ISSUE TITLE
Address Shipping

### ISSUE THREAD

**Issue by francescoz91** [abuzuhri/Amazon-SP-API-CSharp#497]
Hi everyone.
I'm testing the API thanks to this repository. I noticed that when I request an order with the Orders.GetOrders() function and both the single order Orders.GetOrderItems(), many fields are Null including the shipping address ones.
I tried to ask Orders.GetOrderAddress() and it only returns: City, postalcode and StateOrRegion.
Is there something I'm doing wrong?

**Comment by ThomasL1973** [comment]
This is because your api role doesn‘t Allow you to receive PII Data like Name, Shipping Address, etc

**Comment by francescoz91** [comment]
This are my roles:
![image](https://user-images.githubusercontent.com/109367871/215424105-2729ffdd-fb93-412f-8c65-b058a62155b0.png)

They are correct? Or do I need to do something else?

**Comment by Xriuk** [comment]
You need to look in the roles of your Developer Profile, cause that's what becomes visible in the roles assignable to the app, if you don't have access to restricted roles personal information like names, addresses are not visible. That's Amazon...

**Comment by francescoz91** [comment]
I checked my developer profile and Amazon didn't approve the answers given to your questions about application security. Does anyone know roughly how to pass PII checks?

**Comment by Xriuk** [comment]
> I checked my developer profile and Amazon didn't approve the answers given to your questions about application security. Does anyone know roughly how to pass PII checks?

https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/PII_QA.md

**Comment by smithburger** [comment]
You are missing the direct to consumer role which is what grants PII. Getting access is rigorous. You would know if you requested and got it. PII in SP-API has nothing to do with PII in MWS>

<img width="401" alt="image" src="https://user-images.githubusercontent.com/37640897/219159399-8716fcfe-28ac-4f20-b132-78fbd50bb417.png">

**Comment by abuzuhri** [comment]
we going to close this since its permission problem only
