### ISSUE TITLE
GetOrders

### ISSUE THREAD

**Issue by shawn313** [abuzuhri/Amazon-SP-API-CSharp#5]
Trying to call Get orders and i get 
"Exception thrown: 'AmazonSpApiSDK.Models.Exceptions.AmazonException' in FikaAmazonAPI.dll
An unhandled exception of type 'AmazonSpApiSDK.Models.Exceptions.AmazonException' occurred in FikaAmazonAPI.dll
Amazon Api didn't respond with Okay, see exception for more details"

Here is my code 

` ParameterOrderList serachOrderList = new ParameterOrderList();
            serachOrderList.CreatedAfter = DateTime.UtcNow.AddHours(-24);

            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Unshipped);

            var orders = amazonConnection.Orders.GetOrders(serachOrderList);`

**Comment by KristopherMackowiak** [comment]
For orders, you should also send MarketpalceIds in the parameters

**Comment by abuzuhri** [comment]
You need to add MarketplaceIds here here sample work for me
```CSharp
            ParameterOrderList serachOrderList = new ParameterOrderList();
            serachOrderList.CreatedAfter = DateTime.UtcNow.AddHours(-24);
            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Unshipped);
            serachOrderList.MarketplaceIds = new List<string> { MarketPlace.UnitedArabEmirates.ID };

            var orders = amazonConnection.Orders.GetOrders(serachOrderList);
```
