### ISSUE TITLE
Source/FikaAmazonAPI/Services/FeedService.cs throws exception

### ISSUE THREAD

**Issue by rfatica** [abuzuhri/Amazon-SP-API-CSharp#501]
Source/FikaAmazonAPI/Services/FeedService.cs calls Path.IsRootedPath, but this throws invalid Argument Exception in .net framework.

            if (System.IO.Path.IsPathRooted(contentOrFilePath))  // throws exception in .net 46, 4.7, 4.8 etc
            {
                // The string looks like a file path, so try to read the file
                if (System.IO.File.Exists(contentOrFilePath))
                {
                    bytes = System.IO.File.ReadAllBytes(contentOrFilePath);
                }
                else
                {
                    // The file does not exist, so treat the string as content
                    bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                }
            }

**Comment by rfatica** [comment]
I suggest replacing this: 
                if (System.IO.Path.IsPathRooted(contentOrFilePath))
                {
                    // The string looks like a file path, so try to read the file
                    if (System.IO.File.Exists(contentOrFilePath))
                    {
                        bytes = System.IO.File.ReadAllBytes(contentOrFilePath);
                    }
                    else
                    {
                        // The file does not exist, so treat the string as content
                        bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                    }
                }
                else if (Uri.IsWellFormedUriString(contentOrFilePath, UriKind.RelativeOrAbsolute))
                {
                    // The string looks like a URI, so try to parse it as a file URI
                    var uri = new Uri(contentOrFilePath);
                    if (uri.IsFile)
                    {
                        if (System.IO.File.Exists(uri.LocalPath))
                        {
                            bytes = System.IO.File.ReadAllBytes(uri.LocalPath);
                        }
                        else
                        {
                            // The file does not exist, so treat the string as content
                            bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                        }
                    }
                    else
                    {
                        // The URI is not a file URI, so treat the string as content
                        bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                    }
                }
                else
                {
                    // The string is not a file path or a URI, so treat it as content
                    bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                }

with this:

                if (System.IO.File.Exists(contentOrFilePath))
                {
                    bytes = System.IO.File.ReadAllBytes(contentOrFilePath);
                }
                else if (Uri.IsWellFormedUriString(contentOrFilePath, UriKind.RelativeOrAbsolute))
                {
                    // The string looks like a URI, so try to parse it as a file URI
                    var uri = new Uri(contentOrFilePath);
                    if (uri.IsFile)
                    {
                        if (System.IO.File.Exists(uri.LocalPath))
                        {
                            bytes = System.IO.File.ReadAllBytes(uri.LocalPath);
                        }
                        else
                        {
                            // The file does not exist, so treat the string as content
                            bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                        }
                    }
                    else
                    {
                        // The URI is not a file URI, so treat the string as content
                        bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                    }
                }
                else
                {
                    // The string is not a file path or a URI, so treat it as content
                    bytes = System.Text.Encoding.UTF8.GetBytes(contentOrFilePath);
                }

**Comment by abuzuhri** [comment]
we fix this in other issue
