### ISSUE TITLE
Serialization of orders objects

### ISSUE THREAD

**Issue by dansharpe83** [abuzuhri/Amazon-SP-API-CSharp#510]
i'm getting errors when sending requests to the orders endpoints, it seems because its including a load of null values for unset properties, it seems as though its using newtonsoft json to serialize this but the default setting for that is to include?
i can see the datamember attributes have been to to not include but these seem to be being ignored?

am i the only one with the problem? or is it set that way by default? i had to set the DefaultValueHandling = DefaultValueHandling.Ignore on all the optional properties to get it to work.

**Comment by abuzuhri** [comment]
we never facing this error , are you still facing the same error , can you debug and see which one made that error

**Comment by abuzuhri** [comment]
Please open new case with more details if you still facing the error
