### ISSUE TITLE
Use custom environment url

### ISSUE THREAD

**Issue by IcelandAlex** [abuzuhri/Amazon-SP-API-CSharp#520]
Is there any current functionality that would allow custom base urls? I can see in the request service it has a ternary operator to decide what the base URL should be based on the selected Environment: 

```
protected string ApiBaseUrl
{
    get
    {
        return AmazonCredential.Environment == Environments.Sandbox ? AmazonSandboxUrl : AmazonProductionUrl;
    }
}
``` 

Perhaps adding a new enum type in `Environments` for `Environments.Custom` and providing the URL in the `AmazonCredentials` class to bind to a new property `AmazonCustomUrl `

```
var amazonConnection = new AmazonConnection(new AmazonCredential()
{
    AccessKey = settings.AccessKey,
    SecretKey = settings.SecretKey,
    RoleArn = settings.RoleArn,
    ClientId = settings.ClientId,
    ClientSecret = settings.ClientSecret,
    RefreshToken = settings.RefreshToken,
    MarketPlace = MarketPlace.UnitedKingdom,
    Environment = Environments.Custom,
    AmazonCustomUrl = "https://localhost:8080"
});
```

Then ApiBaseUrl would be decided like so:

```
protected string ApiBaseUrl
{
    get
    {
        return AmazonCredential.Environment == Environments.Sandbox ? AmazonSandboxUrl 
		: AmazonCredential.Environment == Environments.Custom ? AmazonCredential.AmazonCustomUrl 
		: AmazonProductionUrl;
    }
}

``` 

This would aid mocking the API calls using a framework like WireMock and routing requests to an API gateway for additional control.

**Comment by abuzuhri** [comment]
@IcelandAlex why you need that if you have Sandbox

And also instead of URL you can made unit test
