### ISSUE TITLE
The sample for SmallAndLightFeePreviewRequest gives JsonSerializationException

### ISSUE THREAD

**Issue by SOELexicon** [abuzuhri/Amazon-SP-API-CSharp#522]
The sample for SmallAndLightFeePreview gives JsonSerializationException

```c#
var fbaEstimate =  objAmazon.amazonConnection.FbaSmallandLight.GetSmallAndLightFeePreview(new FikaAmazonAPI.AmazonSpApiSDK.Models.FbaSmallandLight.SmallAndLightFeePreviewRequest(MarketPlace.UnitedKingdom.ID, new List<FikaAmazonAPI.AmazonSpApiSDK.Models.FbaSmallandLight.Item>
            {
                new FikaAmazonAPI.AmazonSpApiSDK.Models.FbaSmallandLight.Item(objProducts.ASIN,
                new FikaAmazonAPI.AmazonSpApiSDK.Models.FbaSmallandLight.MoneyType("GBP",3.69m))
            }));

```

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'FikaAmazonAPI.AmazonSpApiSDK.Models.FbaSmallandLight.ErrorList' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path 'data[0].errors', line 1, position 82. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at

**Comment by SOELexicon** [comment]
To add to this. this happens when it deserialize's the below error response
`{"data":[{"price":{"amount":0,"currencyCode":"GBP"},"asin":"B00FW2CB94","errors":[{"code":"ITEM_MISSING_WEIGHT","message":"Unable to find weight information about the item from the catalog."}]}]}`

**Comment by SOELexicon** [comment]
for now ive fixed this by adding a naughty try catch in the ExecuteRequestTry function

`        protected async Task<T> ExecuteRequestTry<T>(RateLimitType rateLimitType = RateLimitType.UNSET, CancellationToken cancellationToken = default) where T : new()
        {
            RestHeader();
            AddAccessToken();
            AddShippingBusinessId();

            Request = await TokenGeneration.SignWithSTSKeysAndSecurityTokenAsync(Request, RequestClient.Options.BaseUrl.Host, AmazonCredential, cancellationToken);
            var response = await RequestClient.ExecuteAsync<T>(Request, cancellationToken);
            LogRequest(Request, response);
            SaveLastRequestHeader(response.Headers);
            await SleepForRateLimit(response.Headers, rateLimitType, cancellationToken);
            ParseResponse(response);

            if (response.StatusCode == HttpStatusCode.OK && !string.IsNullOrEmpty(response.Content) && response.Data == null)
            {
                try { 
                response.Data = JsonConvert.DeserializeObject<T>(response.Content);
                }
                catch (Exception e)
                {
                    return default(T);
                  //  throw new Exception(response.Content, e);
                    
                }
            }
            return response.Data;
        }`

**Comment by J-W-Chan** [comment]
> 
I think we should revise the entity class corresponding to the JSON response instead of catching exceptions.
