### ISSUE TITLE
RestClient not properly disposed causes memory / socket leaks 

### ISSUE THREAD

**Issue by techtwentyone** [abuzuhri/Amazon-SP-API-CSharp#523]
There is an issue with the `RestClient` not being disposed that causes sockets leak with CLOSE_WAIT. I tracked this down to the `RestClient` by `RestSharp` not being disposed. Each `RequestService` has a `RequestClient` that should be disposed (to close the underlying HttpClient). as well as the `LWAClient`

If you run a simple program on .net core 2.2 Ubuntu 18.04.6

```csharp
static void Main(string[] args)
{
	var credentials = new AmazonCredential(...);
	while(true)
	{
		var connection = new AmazonConnection(credentials);
		var feeds = d.Feed.GetFeeds(new ParameterGetFeed()
		{
			createdSince = DateTime.Now.AddDays(-7),
			marketplaceIds = new List<string>(){MarketPlace.Mexico.ID},
			feedTypes = new List<Constants.FeedType>() { Constants.FeedType.POST_PRODUCT_DATA }
		});
		Thread.Sleep(1000);
	}
}
```

after an hour you will see the leaked sockets:

> #ss | grep CLOSE-WAIT
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40413                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46345                                     34.196.239.45:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45999                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43393                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37425                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38067                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40261                                       34.192.99.7:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45527                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37101                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45379                                     52.94.231.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44401                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45003                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33817                                    34.202.167.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35909                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36991                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45495                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34833                                      3.215.114.43:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35359                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44417                                     54.160.31.189:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45459                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46487                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34633                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38593                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36645                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36755                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45249                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46787                                     54.160.31.189:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39629                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42349                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37141                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42017                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39541                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43459                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45823                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43063                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41505                                     34.196.239.45:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38755                                    52.202.227.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33945                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43433                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43205                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41231                                      34.233.67.41:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37993                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41197                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42705                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39553                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38221                                       34.192.99.7:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34705                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46529                                     34.196.239.45:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40321                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33595                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46381                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36773                                    34.202.167.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42395                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33427                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39135                                    34.232.212.200:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35913                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36815                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33351                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40195                                    52.202.227.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39741                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42875                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34573                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33639                                    34.232.212.200:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33651                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42193                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40993                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43855                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41989                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34329                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39311                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40521                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:32975                                       34.192.99.7:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35553                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39045                                     34.196.239.45:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35551                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33743                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46493                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38785                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41403                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33037                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38355                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44457                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37991                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41237                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43973                                    52.202.227.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36561                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43465                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34213                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42805                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45025                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41689                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43841                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44847                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33333                                      3.215.114.43:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38805                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36821                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45897                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37657                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41435                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44427                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36569                                    34.202.167.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38299                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37697                                      34.233.67.41:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46089                                     54.160.31.189:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40241                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44883                                    34.232.212.200:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33055                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40775                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40847                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40647                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39651                                      3.215.114.43:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35315                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37419                                     34.196.239.45:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36359                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37947                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38939                                    34.202.167.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37183                                     52.94.240.240:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33653                                       34.192.99.7:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43359                                    52.202.227.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33497                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39587                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45565                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:36643                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37915                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46339                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38601                                     54.160.31.189:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43675                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40791                                     54.160.31.189:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46535                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45917                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43561                                     54.160.31.189:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37079                                    34.202.167.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46823                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38005                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39841                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45201                                    34.232.212.200:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46287                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45053                                    34.202.167.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34491                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39351                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45753                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41857                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42063                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44239                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44303                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42307                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35511                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45375                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38901                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40069                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37705                                     34.196.239.45:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42491                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40975                                     18.211.25.229:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44771                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46579                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46483                                    34.234.102.147:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35071                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43339                                      52.21.12.184:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45411                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42527                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:42351                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34433                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45227                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35075                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33769                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40765                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34469                                    52.202.227.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46379                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45925                                      3.215.114.43:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44081                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38375                                    34.232.212.200:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:39243                                      3.215.114.43:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40411                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37575                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45055                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:35671                                     54.92.197.201:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43145                                     44.193.47.144:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43557                                     34.200.38.214:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45277                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44553                                    34.232.212.200:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45873                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33331                                    35.169.158.182:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33135                                     34.224.76.173:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44583                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:46311                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:34597                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:37029                                    18.232.206.203:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:38171                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33689                                     3.222.127.235:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:41843                                     54.86.248.231:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40443                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:43935                                     34.192.43.169:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:33701                                    52.202.227.112:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:45419                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:44237                                    54.164.250.120:https
tcp   CLOSE-WAIT  32      0                              127.0.0.1:40819                                     34.192.43.169:https

**Comment by techtwentyone** [comment]
I found a way to dispose the `RestClient` belonging to the `RequestService`s:
```
public class DisposableAmazonConnection : AmazonConnection, IDisposable
    {
        private static readonly PropertyInfo[] Fields = typeof(AmazonConnection)
            .GetProperties()
            .Where(x => typeof(RequestService).IsAssignableFrom(x.PropertyType))
            .ToArray();

        private static readonly PropertyInfo F_RestClient = typeof(RequestService).GetProperty("RequestClient", BindingFlags.NonPublic | BindingFlags.Instance);

        public DisposableAmazonConnection(AmazonCredential creds) : base(creds)
        {

        }

        public void Dispose()
        {
            var restClients = Fields
                .Select(x => x.GetValue(this))
                .Cast<RequestService>()
                .Select(x => F_RestClient.GetValue(x))
                .Cast<RestClient>()
                .ToList();
            foreach (var restClient in restClients)
            {
                restClient?.Dispose();
            }
        }
    }
```

but the `LWAClient` is inaccessible because its not stored in a property.

**Comment by J-W-Chan** [comment]
> I found a way to dispose the `RestClient` belonging to the `RequestService`s:
> 
> ```cs
> public class DisposableAmazonConnection : AmazonConnection, IDisposable
>     {
>         private static readonly PropertyInfo[] Fields = typeof(AmazonConnection)
>             .GetProperties()
>             .Where(x => typeof(RequestService).IsAssignableFrom(x.PropertyType))
>             .ToArray();
> 
>         private static readonly PropertyInfo F_RestClient = typeof(RequestService).GetProperty("RequestClient", BindingFlags.NonPublic | BindingFlags.Instance);
> 
>         public DisposableAmazonConnection(AmazonCredential creds) : base(creds)
>         {
> 
>         }
> 
>         public void Dispose()
>         {
>             var restClients = Fields
>                 .Select(x => x.GetValue(this))
>                 .Cast<RequestService>()
>                 .Select(x => F_RestClient.GetValue(x))
>                 .Cast<RestClient>()
>                 .ToList();
>             foreach (var restClient in restClients)
>             {
>                 restClient?.Dispose();
>             }
>         }
>     }
> ```
> 
> but the `LWAClient` is inaccessible because its not stored in a property.

Hi @techtwentyone . I have maked a  "[static HttpClient]"(https://github.com/abuzuhri/Amazon-SP-API-CSharp/tree/staticHttpClient) branch, to fix this problem. It works well in my local environment. Can you help me test it together?

**Comment by techtwentyone** [comment]
Tested and can confirm sockets are no longer leaking. thanks 🙏

**Comment by techtwentyone** [comment]
@abuzuhri Is this fix included in the published nuget packages?

**Comment by GuybrushX** [comment]
> @abuzuhri Is this fix included in the published nuget packages?

I wondered the same. After checking commit messages it doesn't look like and I think it was accidentally not merged. The branch is deleted as well so I can't compare it myself.

@J-W-Chan
Can you check/confirm if the fix is included?

**Comment by J-W-Chan** [comment]
> > @abuzuhri Is this fix included in the published nuget packages?
> 
> I wondered the same. After checking commit messages it doesn't look like and I think it was accidentally not merged. The branch is deleted as well so I can't compare it myself.
> 
> @J-W-Chan Can you check/confirm if the fix is included?

I resubmit the code for the staticHttp branch #538

**Comment by techtwentyone** [comment]
Looks like even though this was merged - it is not published in any release.. we ran into an issue when testing the branch with processes that run for longer than 15-45 minutes:
```
System.SystemException: Error getting LWA Access Token ---> System.IO.IOException: Unsuccessful LWA token exchange ---> System.Net.Http.HttpRequestException: Request failed with status code BadRequest
   --- End of inner exception stack trace ---
   at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.GetAccessTokenAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.GetAccessTokenAsync(CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.TokenGeneration.RefreshAccessTokenAsync(AmazonCredential credentials, TokenDataType tokenDataType, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.RequestService.RefreshTokenAsync(TokenDataType tokenDataType, CreateRestrictedDataTokenRequest requestPII, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.RequestService.CreateAuthorizedRequestAsync(String url, Method method, List`1 queryParameters, Object postJsonObj, TokenDataType tokenDataType, Object parameter, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.FeedService.GetFeedAsync(String feedId, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.FeedService.GetFeed(String feedId)
```

or 
```
FikaAmazonAPI.AmazonSpApiSDK.Models.Exceptions.AmazonException: Amazon Api didn't respond with Okay, see exception for more details
   at FikaAmazonAPI.Services.RequestService.ParseResponse(RestResponse response)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequestTry[T](RateLimitType rateLimitType, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequestAsync[T](RateLimitType rateLimitType, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.FeedService.GetFeedAsync(String feedId, CancellationToken cancellationToken)
   at FikaAmazonAPI.Services.FeedService.GetFeed(String feedId)
```

once we see this error, every subsequent request will fail with this error until we restart the process which fixes the issue. until another 15-45 minutes pass and the same errors come up again.

I'm not sure what the issue is (if it is with the underlying connection pool in the StandardSocketsHttpHandler library). it may relate to a connection after it hits a rate limit. to fix the issue I reverted LWAClient to not use singleton and instead disposes the RestClient.

we are running .net core 3.1 ubuntu 18.04.6 on gcp

**Comment by J-W-Chan** [comment]
Could you please provide your test code?

**Comment by techtwentyone** [comment]
I can't reproduce this in test code. perhaps I need to run the tests on GCP

**Comment by J-W-Chan** [comment]
We could use more people to help us out with the testing.
