### ISSUE TITLE
Getting exception illegal characters in path.

### ISSUE THREAD

**Issue by mehrdadsamadie** [abuzuhri/Amazon-SP-API-CSharp#525]
I am getting exception in PostFileDataAsync function on FeedService class. 
the line 271 System.IO.Path.IsPathRooted(contentOrFilePath) pop up this exception. 
I don't use a file. 
it seems this issue pop up in .net framework .

**Comment by JLOrdaz** [comment]
That happened to me and it was when I used .NET framework, if the project is with .NET 6 or 7 it works.

**Comment by JLOrdaz** [comment]
Another way is that if it is giving when you are sending a FEED, then put the contentFormat property: ContentFormate.Text) if you do not put that assumes Auto and there it gives the error. This is a workaround that worked for me.

**Comment by J-W-Chan** [comment]
If you specify arguments "ContentFormat contentFormat=ContentFormat. File".
Does it work correctly?

**Comment by JLOrdaz** [comment]
I think qe if it should work like that.
