### ISSUE TITLE
Company name is missing for orders by business customers

### ISSUE THREAD

**Issue by yscypress** [abuzuhri/Amazon-SP-API-CSharp#527]
When an order is placed by a business customer, the retrieved order has IsBusinessOrder set to True. However currently the company name of the customer does not appear to be available.

None of AmazonConnection.Order.GetOrders, Orders.GetOrderBuyerInfo, Orders.GetOrderAddress calls return info about the company name.  The returned address did show that ShippingAddress.AddressType was Commercial.

Naturally I am a valid PII developer.

Or I have missed anything?

**Comment by J-W-Chan** [comment]
Can you print the JSON response returned by the API?

**Comment by abuzuhri** [comment]
@yscypress please point to JSON to its easy to us find it and fix it

**Comment by yscypress** [comment]
I am sorry for the delay as I was away. I set IsDebugMode = true when creating a new AmazonCredential(). I am not able to find any logs that record JSON response. Where should I be looking for the log files which contain JSON responses?
