### ISSUE TITLE
System.MissingMethodException in GetOrders

### ISSUE THREAD

**Issue by indaldev** [abuzuhri/Amazon-SP-API-CSharp#532]
Hi, I have valid Amazon Credentials (work fine on Postman)

but I'm getting this exception when testing the GetOrders method (both in production and sandbox environments)

Any clue?

Thanks!

> $exception	{"Method not found: 'Void RestSharp.RestClient..ctor(System.String)'."}	System.MissingMethodException

FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient..ctor(LWAAuthorizationCredentials lwaAuthorizationCredentials)
   en FikaAmazonAPI.Services.TokenGeneration.<RefreshAccessTokenAsync>d__0.MoveNext()
   en FikaAmazonAPI.Services.RequestService.<RefreshTokenAsync>d__51.MoveNext()
   en FikaAmazonAPI.Services.RequestService.<CreateAuthorizedRequestAsync>d__36.MoveNext()
   en FikaAmazonAPI.Services.RequestService.<CreateRestrictedDataTokenAsync>d__55.MoveNext()
   en FikaAmazonAPI.Services.RequestService.<RefreshTokenAsync>d__51.MoveNext()
   en FikaAmazonAPI.Services.RequestService.<CreateAuthorizedRequestAsync>d__36.MoveNext()
   en FikaAmazonAPI.Services.OrderService.<GetOrdersAsync>d__2.MoveNext()
   en FikaAmazonAPI.Services.OrderService.GetOrders(ParameterOrderList searchOrderList)

**Comment by abuzuhri** [comment]
Yes it's totally different story how post man work and api work , but if you follow Amazon authorization instructions you will git it work

**Comment by indaldev** [comment]
Hi, I followed Amazon authorization instructions. Tested on Postman and I could retrieve orders, also tested on another C# SP Api library and worked fine. So, I guess it's not a credential/authorization issue.

Maybe a conflict in RestSharp versions/dependencies like this  [one](https://github.com/restsharp/RestSharp/issues/1198)?

**Comment by abuzuhri** [comment]
You need to read self authorization not postman ,many developer use this nuget without issue , this problem is common with all new developers , we can't help on that but I'm sour it's authorization problem

**Comment by indaldev** [comment]
Ok,thanks for your time. I will look further into the issue

I tried this other  [nuget package](https://github.com/jadanah/amazon-selling-partner-api-csharp-samples), and tested the same credentials and it worked fine on that library, I could retrieve orders and also restricted BuyerInfo/Shipping Address for each order, , so I'm bit confused why this should be an authorization issue

**Comment by indaldev** [comment]
Got it.. I uninstalled RestSharp nuget package and worked 👍
