### ISSUE TITLE
Add HTTP Proxy support?

### ISSUE THREAD

**Issue by GuybrushX** [abuzuhri/Amazon-SP-API-CSharp#536]
Small update:
Seems that Visual Studio was confused - I tried it again without changing the `TargetFramework` and it seems to work now which is much better, of course :-) Hence I've removed that part about changing the `TargetFramework`.

-- Original message --
I've successfully tested to use a HTTP proxy with the library.

The reason is that my application is accessing different accounts and I want to avoid issues with Amazon. Some companies also have very strict policies and make it necessary to use a proxy  for security reasons.

Is there a chance to get this feature added?

What I've tested successfully so far:
``` csharp
GetCatalogItem202204Async
GetMarketplaceParticipationsAsync
CreateReportAndDownloadFileAsync
```

I've also checked the outgoing IP with https://ident.me and confirmed that it is different.

The HTTP proxy software I'm using is https://privoxy.org - it is free, cross-platform and super easy to use and much more powerful than needed. It basically needs only an firewall exception and probably 1 change to the `config.txt`:
```
listen-address  192.168.x.y:1234
```

I've also used the following tool to see if `privoxy` is generating some traffic:
https://www.nirsoft.net/utils/app_network_counter.html

You can also use `WireShark` or `tcpdump` but it wasn't necessary for me so far.

RestSharp's `RestClient` is used in 2 places only and as a quick & dirty solution I've added a `ProxyAddress` property to the `AmazonCredentials` class to make this configurable as well:
``` csharp
public string ProxyAddress { get; set; }

// Updated constructor
public AmazonCredential(string AccessKey, string SecretKey, string RoleArn, string ClientId, string ClientSecret, string RefreshToken, string proxyAddress = null)
{
    this.AccessKey = AccessKey;
    this.SecretKey = SecretKey;
    this.RoleArn = RoleArn;
    this.ClientId = ClientId;
    this.ClientSecret = ClientSecret;
    this.RefreshToken = RefreshToken;
    this.ProxyAddress = proxyAddress;
    CacheTokenData = new CacheTokenData();
}
```

Here is the change in the LWAClient constructor -> I've added an optional parameter as well for backwards compatibility.

```csharp
public LWAClient(LWAAuthorizationCredentials lwaAuthorizationCredentials, string proxyAddress = null)
{
    LWAAuthorizationCredentials = lwaAuthorizationCredentials;
    LWAAccessTokenRequestMetaBuilder = new LWAAccessTokenRequestMetaBuilder();
    //RestClient = new RestClient(LWAAuthorizationCredentials.Endpoint.GetLeftPart(UriPartial.Authority));

    // Experiment: Proxy!
    if (string.IsNullOrWhiteSpace(proxyAddress))
    {
        RestClient = new RestClient(LWAAuthorizationCredentials.Endpoint.GetLeftPart(UriPartial.Authority));
    }
    else
    {
        var options = new RestClientOptions(LWAAuthorizationCredentials.Endpoint.GetLeftPart(UriPartial.Authority))
        {
            Proxy = new System.Net.WebProxy()
            {
                Address = new Uri(proxyAddress)
            }
        };

        RestClient = new RestClient(options);
    }
}
```

`TokenGeneration.cs`:
```csharp
// Before
var Client = new LWAClient(lwaCredentials);

// After
var Client = new LWAClient(lwaCredentials, credentials.ProxyAddress);
```

Similar change in the `RequestService.cs`:
``` csharp
private void CreateRequest(string url, RestSharp.Method method)
{
    if (string.IsNullOrWhiteSpace(AmazonCredential.ProxyAddress))
    {
        RequestClient = new RestClient(ApiBaseUrl);
    }
    else
    {
        var options = new RestClientOptions(ApiBaseUrl)
        {
            Proxy = new System.Net.WebProxy()
            {
                Address = new Uri(AmazonCredential.ProxyAddress)
            }
        };

        RequestClient = new RestClient(options);
    }

    RequestClient.UseNewtonsoftJson();
    Request = new RestRequest(url, method);
}
```

**Comment by simeyla** [comment]
@abuzuhri what about a proxy that needs credentials?

I've tried using `"http://username:password@xx.xx.xxx.xx:xxxxx"`

but I think we need to set `Credentials` on `WebProxy`
