### ISSUE TITLE
Not working with Restsharp 109.0.1

### ISSUE THREAD

**Issue by ThomasL1973** [abuzuhri/Amazon-SP-API-CSharp#540]
Amazon-SP-Api_CSharp 1.6.2 ist not working with Current Version 109.0.1 of RestSharp. With Restsharp 108.0.3 all is working fine.

Reports.GetReport throws following exception:

System.MissingMethodException
  HResult=0x80131513
  Nachricht = Method not found: 'Void RestSharp.RestClient..ctor(System.String)'.
  Quelle = FikaAmazonAPI
  Stapelüberwachung:
   bei FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient..ctor(LWAAuthorizationCredentials lwaAuthorizationCredentials)
   bei FikaAmazonAPI.Services.TokenGeneration.<RefreshAccessTokenAsync>d__0.MoveNext()
   bei FikaAmazonAPI.Services.RequestService.<RefreshTokenAsync>d__51.MoveNext()
   bei FikaAmazonAPI.Services.RequestService.<CreateAuthorizedRequestAsync>d__36.MoveNext()
   bei FikaAmazonAPI.Services.ReportService.<GetReportsAsync>d__2.MoveNext()
   bei FikaAmazonAPI.Services.ReportService.GetReports(ParameterReportList parameterReportList)
   bei myAmazonImporterCore.Program.Get_REPORTS(String type) in D:\OneDrive\Documents\Repos\myAmazonImporterCore\myAmazonImporterCore\Program.cs: Zeile320
   bei myAmazonImporterCore.Program.Main(String[] args) in D:\OneDrive\Documents\Repos\myAmazonImporterCore\myAmazonImporterCore\Program.cs: Zeile119

**Comment by J-W-Chan** [comment]
Why does Restsharp version 109.0.1 appear in the project? Have you referenced Restsharp version 109.0.1 in other projects?

**Comment by marketlabdev** [comment]
I am using RestSharp for other things in my project and I am getting the same error.

**Comment by RGoen** [comment]
Had the same issue with the current version of 1.6.4.  Rolled back the RestSharp library to 108.0.3 and that worked.
