### ISSUE TITLE
POST_PRODUCT_DATA throws Invalid URI exception

### ISSUE THREAD

**Issue by Foozinator** [abuzuhri/Amazon-SP-API-CSharp#545]
I'm trying to build a POST_PRODUCT_DATA feed.  I've tried a number of different ways to build the feed XML itself, but I think there's an underlying problem.  I call:
`amazonConnection.Feed.SubmitFeed( xmlString, FikaAmazonAPI.Utils.Constants.FeedType.POST_PRODUCT_DATA );`

and I get 

> Invalid URI: The URI scheme is not valid.
>
>   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
>   at System.Uri..ctor(String uriString)
>   at FikaAmazonAPI.Services.FeedService.<PostFileDataAsync>d__22.MoveNext()
>   at FikaAmazonAPI.Services.FeedService.<SubmitFeedAsync>d__20.MoveNext()
>   at FikaAmazonAPI.Services.FeedService.SubmitFeed(String XmlContentOrFilePath, FeedType feedType, List`1 marketPlaceIds, FeedOptions feedOptions, ContentType contentType)

I don't know where to start troubleshooting this library configuration.

**Comment by abuzuhri** [comment]
Which version you are using , if it's last version please share code you use to check

**Comment by Foozinator** [comment]
I was using 1.5.26.  I upgraded to 1.6.2, and now that call is succeeding.  Thank you for your work on this library.
