### ISSUE TITLE
Wrong named constant `POST_FLAT_FILE_BOOKLOADER_DATA`.

### ISSUE THREAD

**Issue by Baro82** [abuzuhri/Amazon-SP-API-CSharp#547]
The reference file is this: `Amazon-SP-API-CSharp/Source/FikaAmazonAPI/Utils/Constants.cs`

```
    public enum FeedType
    {
        ...
        POST_FLAT_FILE_BOOKLOADER_DATA_,
        ...
    }
```
The correct name is: `POST_FLAT_FILE_BOOKLOADER_DATA`.

I had to import the sources to modify and test it, it works without final underscore.

**Comment by ProNotion** [comment]
@Baro82  You could fix it and submit a pull request which can be merged back into the repo 👍
