### ISSUE TITLE
POST_ORDER_FULFILLMENT_DATA Feed

### ISSUE THREAD

**Issue by kevinvenclovas** [abuzuhri/Amazon-SP-API-CSharp#57]
Is there an example for the Feed: POST_ORDER_FULFILLMENT_DATA ?

**Comment by abuzuhri** [comment]
Hello @kevinvenclovas 
Right now no we don't support it 

But i know @gcuadrado working in this part maybe both of you folk the project and add merge your work after finish

**Comment by gcuadrado** [comment]
Yes, I am working on it. I have created the classes based on XSD and I am testing it right now, I am going to merge when it is ready.

**Comment by kevinvenclovas** [comment]
@abuzuhri Thank you!
@gcuadrado Nice! how long do you need to finish it? Weeks? Months?

**Comment by gcuadrado** [comment]
@kevinvenclovas I have it working now, I am going to make a pull request with the changes.

**Comment by abuzuhri** [comment]
Thanks 👍

**Comment by abuzuhri** [comment]
@kevinvenclovas 

Please check NuGet v1.0.32
