### ISSUE TITLE
SubmitFeed issues

### ISSUE THREAD

**Issue by azer-lev** [abuzuhri/Amazon-SP-API-CSharp#573]
Hello,
I'm currently working on uploading invoices. No matter what I try, every time I try to call SubmitFeed or CreateFeed I'm getting a **403** error from Amazon '_Access to the resource is forbidden_'. To upload invoices I need to use the FeedType '_UPLOAD_VAT_INVOICE_'. I'm currently using version **1.6.2**. You can find my current code below, any help or suggestion is appreciated.

```
                var options = new FeedOptions
                {
                    { "DocumentType", "Invoice" },
                    { "InvoiceNumber", element.InvoiceNumber },
                    { "OrderId", element.OrderId}
                };

                var feedId = await con.Feed.SubmitFeedAsync(
                    element.Path,
                    Constants.FeedType.UPLOAD_VAT_INVOICE,
                    new List<string>() { MarketPlace.Germany.ID },
                    options,
                    Constants.ContentType.PDF);

                var result = await con.Feed.GetFeedAsync(feedId);

                while (result.ProcessingStatus == Feed.ProcessingStatusEnum.INPROGRESS)
                {
                    await Task.Delay(5000);
                    result = await con.Feed.GetFeedAsync(feedId);
                }
```

Are there maybe additional permissions needed, as the data beeing processed should underlay **PII** standards?

**Comment by J-W-Chan** [comment]
You should first apply for the role of Tax Invoicing [](https://developer-docs.amazon.com/sp-api/docs/tax-invoicing-restricted-role)

**Comment by azer-lev** [comment]
The RoleArn I am using has the permissions for Tax Invoicing. Is there any solution I could try?

**Comment by zinsmeik** [comment]
see https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/546#issuecomment-1618288567
You should use  options as 
```
options.Add("metadata:documenttype", "Invoice");
options.Add("metadata:invoicenumber", <YOUR_INVOICE_NUMBER>);
options.Add("metadata:orderid", <YOUR_AMAZON_ORDERID>);
```

**Comment by abuzuhri** [comment]
Personally I have no time to keep updating this package but I'm open any developer need to fix or add feature on it its take many times from me to get it live , and I need other developer help to add the fix for new features by submit new Pull requests , I will try to review and accept within 2 days  .


Please try fork our rep and then submit your change to review and merge with our code
