### ISSUE TITLE
Latest version imports a dll which causes conflicts

### ISSUE THREAD

**Issue by antonycartwright** [abuzuhri/Amazon-SP-API-CSharp#586]
My project is .net 4.8, but the nuget tries to force .net core 2.0.

The error is:

Copying file

packages\Microsoft.Extensions.DependencyInjection.Abstractions.7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets

to

C:\Users\Administrator\AppData\Local\Temp\2\WebSitePublish\EPHB2--227909753\obj\Debug\Package\PackageTmp\packages\Microsoft.Extensions.DependencyInjection.Abstractions.7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets

failed.

Could not find a part of the path

'C:\Users\Administrator\AppData\Local\Temp\2\WebSitePublish\EPHB2--227909753\obj\Debug\Package\PackageTmp\packages\Microsoft.Extensions.DependencyInjection.Abstractions.7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstractions.targets'.

A nuget package has imported this file on my behalf. When I look in the path, it's correct that the file 'Microsoft.Extensions.DependencyInjection.Abstractions.targets' doesn't exist.

**Comment by TechyChap** [comment]
Looks like that is coming in via Microsoft.Extensions.Http

https://www.nuget.org/packages/Microsoft.Extensions.Http#dependencies-body-tab

But that does claim to be compatible with .Net Framework.

**Comment by abuzuhri** [comment]
@antonycartwright Do you solve your problem ?

**Comment by antonycartwright** [comment]
> @antonycartwright Do you solve your problem ?

Yes, there was a breaking change in one of your releases. I fixed it by downgrading to a supported package. :-D
