### ISSUE TITLE
FeedAmazonEnvelope

### ISSUE THREAD

**Issue by ferrarinim** [abuzuhri/Amazon-SP-API-CSharp#598]
Hi, I have created a FeedAmazonEnvelope object, but I don't know how to sent it to Amazon.
Can you please provide me an example?
Here my code

      `FeedAmazonEnvelope feed = new FeedAmazonEnvelope();
            feed.Header = new FeedHeader();
            feed.Header.DocumentVersion = "1.01";
            feed.Header.MerchantIdentifier = AmazonCredentials.Default.VendorId;
            feed.MessageType = FeedMessageType.Product;
            List <BaseMessage> messages = new List<BaseMessage>();
            int cont = 1;
            foreach(string sku in parStylesToDelete)
            {
                BaseMessage mess = new BaseMessage();
                mess.MessageID = cont;
                mess.OperationType = OperationType.Delete;
                ProductMessage product = new ProductMessage();
                product.SKU = sku;
                mess.Product = product;

                messages.Add(mess);
                cont++;
            }
            feed.Message = messages;`

**Comment by abuzuhri** [comment]
do you see our code sample

**Comment by ferrarinim** [comment]
I searched for “FeedAmazonEnvelope” buy I didn’t get any  result

**Comment by J-W-Chan** [comment]
You can refer to using this method [https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/77cdf4fa901202f0b78c8e74f99764152a16013c/Source/FikaAmazonAPI.SampleCode/FeedsSample.cs#L158C70-L158C70](url)
