### ISSUE TITLE
Lowercase change from propercase in model according to AMZ support (GetfulfillmentPreview at least)

### ISSUE THREAD

**Issue by Paul-J-Barrett** [abuzuhri/Amazon-SP-API-CSharp#614]
My fulfillmentoutbound.getfulfillmentpreview broke. I opened a ticket with Amz Dev Support and they basically told me that the properties on the model should be lowercase. I checked https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-api-v2020-07-01-model which shows that it changed three months ago. The model for getfulfillmentPreview hasn't changed in two years. So Amz obviously made some kind of breaking change. My code had been working before I noticed that our MCF program had stopped working.

Amz support pointed me to the above document and said that quantity and items needs to be lowercase at least. Busy with other project today so haven't had time to test it further

**Comment by Paul-J-Barrett** [comment]
How hard is it to get swagger to update the models or would it break things?

**Comment by J-W-Chan** [comment]
You can update the model classes at any time, and at this stage, disruptive updates are also unavoidable

**Comment by Paul-J-Barrett** [comment]
PR in  fixes amz submission issues #620
