### ISSUE TITLE
Error reading some Amazon AU orders with value "Amazon Commercial Services Pty Ltd" in Orders.TaxCollection+ResponsiblePartyEnum

### ISSUE THREAD

**Issue by nickgoodmanuk** [abuzuhri/Amazon-SP-API-CSharp#629]
Error converting value "Amazon Commercial Services Pty Ltd" to type 'System.Nullable`1[FikaAmazonAPI.AmazonSpApiSDK.Models.Orders.TaxCollection+ResponsiblePartyEnum]'. Path 'payload.OrderItems[0].TaxCollection.ResponsibleParty', line 1, position 123.

**Comment by tank104** [comment]
I have a PR for this: https://github.com/abuzuhri/Amazon-SP-API-CSharp/pull/633

Looks like an undocumented Enum.  @abuzuhri can complete it and then build a package that will sort it.

**Comment by nickgoodmanuk** [comment]
@tank104   Thanks.  I didn't realise the issue had been reported already.

**Comment by tank104** [comment]
@nickgoodmanuk I don't think it had been - we just got it recently too (only for one account though out of hundreds), so needed to fix it ASAP.

**Comment by abuzuhri** [comment]
PR MERGED AND RELEASED
