### ISSUE TITLE
Update inventory stocks

### ISSUE THREAD

**Issue by abuzuhri** [abuzuhri/Amazon-SP-API-CSharp#65]
### Discussed in https://github.com/abuzuhri/Amazon-SP-API-CSharp/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **ferrarinim** December 25, 2021</sup>
Error When try to submit feed for update inventory to not existing SKU

</div>

Used Code

```Csharp
ConstructFeedService createDocument = new ConstructFeedService("{SellerID}", "1.02");

var list = new List<InventoryMessage>();
list.Add(new InventoryMessage()
  {
    SKU = "82010312061.22...",
    Quantity = 2,
    FulfillmentLatency = "11",
 });

createDocument.AddInventoryMessage(list);

var xml = createDocument.GetXML();

var feedID = amazonConnection.Feed.SubmitFeed(xml, FeedType.POST_INVENTORY_AVAILABILITY_DATA);

Thread.Sleep(1000*30);

var feedOutput=amazonConnection.Feed.GetFeed(feedID);

var outPut=amazonConnection.Feed.GetFeedDocument(feedOutput.ResultFeedDocumentId);

var reportOutpit = outPut.Url;

var processingReport = amazonConnection.Feed.GetFeedDocumentProcessingReport(outPut.Url);
```

**Comment by abuzuhri** [comment]
Hello @wheelersf 

Can you help with open bug in Amazon Selling Center

**Comment by wheelersf** [comment]
Hi @abuzuhri 

It might actually be a while if I am to do it.  I'm executing this against someone else's account and the app is not yet installed.  So, opening a case with Amazon isn't going to be a priority for them.  With as many developers as there are banging on the Seller API, I can't imagine that someone else hasn't already opened a case.

Scott

**Comment by abuzuhri** [comment]
I open case now , hopefully the will look soon to it
https://github.com/amzn/selling-partner-api-docs/issues/1910
