### ISSUE TITLE
GetOrders filter Unshipped

### ISSUE THREAD

**Issue by shawn313** [abuzuhri/Amazon-SP-API-CSharp#7]
I have a call to GetOrders with the filter set to Unshipped here is the code 
`            AmazonConnection amazonConnection = new AmazonConnection(creds);
            ParameterOrderList serachOrderList = new ParameterOrderList();
            serachOrderList.CreatedAfter = DateTime.UtcNow.AddMinutes(-120);
            serachOrderList.OrderStatuses = new List<OrderStatuses>();
            serachOrderList.OrderStatuses.Add(OrderStatuses.Unshipped);
            serachOrderList.MarketplaceIds = new List<string> { MarketPlace.US.ID };
            var orders = amazonConnection.Orders.GetOrders(serachOrderList);
`

i should not get anything back for 120 mins as the last order waS 17 hours ago I get a list back of  7 orders

**Comment by abuzuhri** [comment]
> DateTime.UtcNow.AddMinutes(-120);

Do you compare your local time with UTC time ?

` DateTime.UtcNow.AddMinutes(-120);`

**Comment by abuzuhri** [comment]
Change this line ` serachOrderList.CreatedAfter = DateTime.UtcNow.AddMinutes(-120); `  to ` serachOrderList.CreatedAfter = DateTime.Now.AddMinutes(-120); `
