### ISSUE TITLE
Missing PII (name, address) in orders

### ISSUE THREAD

**Issue by Tajanos** [abuzuhri/Amazon-SP-API-CSharp#702]
I updated to the latest version 1.7.11.0 and things are weird. When I get more than a couple of hours' worth of orders, they seem to be missing restricted data (name and address). Not all orders are missing this info though. If I get one hour's worth, they seem to have it.

Is this a bug/change in the library or has Amazon changed something recently? This used to work in the past - I get 24 hours' worth of orders every night just to be sure.

Maybe it has to do with the number of records - the first page of 100 records might have the data but the subsequent ones don't? Does the restricted token have to get re-applied?

**Comment by Smyrcu** [comment]
I have the same error, from 101 order inclusive I don't get address data (Name, Address).

**Comment by Tajanos** [comment]
Can you take a look, @faizanahmad1094? Orders 0-99 have PII but anything 100+ is missing shipping addresses etc.

**Comment by miroslavpopovic** [comment]
In the latest version, 1.7.17, it also doesn't work. I had to revert to 1.7.9 too.

Only the first page of 100 orders contains PII data.
