### ISSUE TITLE
BuyerCompanyName

### ISSUE THREAD

**Issue by Tajanos** [abuzuhri/Amazon-SP-API-CSharp#704]
It appears that this field is available in the API, can it be added to Orders?

**Comment by kevinvenclovas** [comment]
Where exactly should the field be? Any link to the documentation?

**Comment by Tajanos** [comment]
It seems to be mentioned here:

https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json

**Comment by kevinvenclovas** [comment]
@abuzuhri this issue can be closed
