### ISSUE TITLE
How to get the list of orders without uploaded invoices in European FBA orders?

### ISSUE THREAD

**Issue by kdfhhao** [abuzuhri/Amazon-SP-API-CSharp#721]
What parameters should I use to get the list of orders in European FBA orders that have not uploaded invoices? I tried using ElectronicInvoiceStatuses and OrderStatuses but failed to obtain them.
thanks.

**Comment by J-W-Chan** [comment]
[https://developer-docs.amazon.com/sp-api/lang-zh_CN/docs/report-type-values-invoice-data](https://developer-docs.amazon.com/sp-api/lang-zh_CN/docs/report-type-values-invoice-data)

**Comment by optitsolutions** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






Closed #721 as completed.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/721#event-12293319512
