### ISSUE TITLE
Get early access to New Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by ouzhiman** [abuzuhri/Amazon-SP-API-CSharp#723]
New API updated

**Comment by optitsolutions** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






New API updated

-- 
Reply to this email directly or view it on GitHub:
https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/723

**Comment by kdfhhao** [comment]
times?

**Comment by abuzuhri** [comment]
No still I don’t work on this .

/Tareq

**Comment by ouzhiman** [comment]
> @ouzhiman Do you mean you have updated this library or that the update needs implementing?

I'm waiting too

**Comment by J-W-Chan** [comment]
Amazon-SP-API-CSharp is an open-source SDK project. We hope that everyone can contribute

**Comment by kevinvenclovas** [comment]
@abuzuhri Close
