### ISSUE TITLE
Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by pacton** [abuzuhri/Amazon-SP-API-CSharp#729]
I see everything we are currently using in Fulfillment Inbound will be deprecated 12/4/2024. Are there plans to bring [Amazon-SP-API-CSharp] up to date with these changes? (https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-faq) Here is the list that is being dropped in Fulfillment Inbound - 

createInboundShipmentPlan
updateInboundShipment
createInboundShipment
getPreorderInfo
confirmPreorder
getTransportDetails
putTransportDetails
voidTransport
estimateTransport
confirmTransport
getShipments
getShipmentItemsByShipmentId
getShipmentItems

**Comment by kevinvenclovas** [comment]
@abuzuhri Close

**Comment by ProNotion** [comment]
> I see everything we are currently using in Fulfillment Inbound will be deprecated 12/4/2024. Are there plans to bring [Amazon-SP-API-CSharp] up to date with these changes? (https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-faq) Here is the list that is being dropped in Fulfillment Inbound -
> 
> createInboundShipmentPlan updateInboundShipment createInboundShipment getPreorderInfo confirmPreorder getTransportDetails putTransportDetails voidTransport estimateTransport confirmTransport getShipments getShipmentItemsByShipmentId getShipmentItems

It states that the following are not being deprecated but everything else is:

- getLabels
- getBillOfLading
- getPrepInstructions
- getShipments
- getShipmentItemsByShipmentId
- getShipmentItems
