### ISSUE TITLE
Error when Calling CatalogItem.GetCatalogItem()

### ISSUE THREAD

**Issue by bartuszekj** [abuzuhri/Amazon-SP-API-CSharp#92]
Calling CatalogItem.GetCatalogItem with any ASIN is causing the following error:

Amazon Api didn't respond with Okay, see exception for more details{
  "errors": [
    {
     "message": "Missing or invalid request parameters: [marketplaceIds]",
     "code": "InvalidInput"
    }
  ]
}

This is happening with the latest release - 1.0.42.0. This functionality works properly with 1.0.1.18.

**Comment by cxnet1** [comment]
Hi, i have the same issue with GetOrder.  I tried "MarketPlace.Turkey" and "MarketPlace.GetMarketPlaceByID("A33AVAJ2PDY3EV")" but nothing changed.

**Comment by abuzuhri** [comment]
Error came from Amazon change this parameter to required , I'm working with fix now....

**Comment by abuzuhri** [comment]
I confirm this bug And working to solve this , its related to change in Amazon API

**Comment by abuzuhri** [comment]
After checking documentation https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v0-reference
Amazon request **[marketplaceIds]** but in documentation request **marketplaceId**

**Comment by abuzuhri** [comment]
Hello @cxnet1  and @bartuszekj 

**Bug fixed in version  v1.0.43**

**Install-Package CSharpAmazonSpAPI -Version 1.0.43**

**Comment by bartuszekj** [comment]
Thank you for fixing this, I will test it as soon as I can.

I do want to point out that the 1.0.1.18 version does still currently work with respect to this API call. Identifying why that is and what and when the breaking change happened in the codebase might identify other possible places where it is currently broken. For instance, #94 might be also a manifestation of this problem.

**Comment by bartuszekj** [comment]
Further note: I did test 1.0.43 and it works fine. I also tested 1.0.41 from nuget and that works fine as well. So the breaking change was introduced somewhere in 1.0.42.

**Comment by abuzuhri** [comment]
Yes I confirm it's was internal bug and it's fixed in last version
